package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class AmgmRelationsTest {
 private long root(long value){for(long x=1;x*x<=value;x++)if(x*x==value)return x;throw new AssertionError("not a positive square: "+value);}
 private List<Long> values(Question q){Matcher m=Pattern.compile("x>0일 때 (\\d*)x\\+(\\d+)/x(?:\\+\\((-?\\d+)\\))?의 최솟값은\\?").matcher(q.prompt);assertTrue(m.matches());long p=m.group(1).isEmpty()?1:Long.parseLong(m.group(1)),n=Long.parseLong(m.group(2)),c=m.group(3)==null?0:Long.parseLong(m.group(3)),point=root(n/p),min=2*p*point+c;assertEquals(n,p*point*point);assertEquals(min,p*point+n/point+c);
  // Exact nonnegative identity: f(x)-f(r) = p*(x-r)^2/x for every positive rational x.
  for(int denominator=1;denominator<=12;denominator++)for(int numerator=1;numerator<=120;numerator++){Rational x=Rational.of(numerator,denominator),f=Rational.of(p).mul(x).add(Rational.of(n).div(x)).add(Rational.of(c)),diff=x.sub(Rational.of(point));assertEquals(f.sub(Rational.of(min)),Rational.of(p).mul(diff).mul(diff).div(x));assertTrue(f.compareTo(Rational.of(min))>=0);}
  return List.of(p,n,c,p*n,root(p*n),n/p,point,2*root(p*n),min);
 }
 private void verify(Question q,List<Long> v){assertTrue(new Checker().check(q,List.of(),List.of(v.get(8).toString())).correct());String id=q.id,prompt=q.prompt,signature=q.signature();Arrays.fill(q.answers,"999");q.givenNumbers.replaceAll((k,x)->"999");q.choiceInputs=new Rational[]{Rational.of(999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(9,p.size());assertFalse(p.canTransfer());assertEquals(id,q.id);assertEquals(prompt,q.prompt);assertEquals(signature,q.signature());for(int i=0;i<9;i++){assertTrue(p.step(i).accepts(v.get(i).toString()));assertFalse(p.step(i).accepts(Long.toString(v.get(i)+1)));assertEquals("",p.step(i).after);assertFalse(p.step(i).before.matches(".*[0-9].*"));}}
 @Test public void allPublicPromptsHaveAttainedMinimumAndBlankHelp(){Generator g=new Generator(new Random(2901));Set<String> prompts=new HashSet<>();Set<Integer> positions=new HashSet<>();Set<Long> constants=new HashSet<>();Map<String,List<Long>> solved=new HashMap<>();for(int i=0;i<4000;i++){Question q=g.next("sec_amgm_minimum",List.of(),i%2==0);prompts.add(q.prompt);if(!q.choices.isEmpty())positions.add(q.correctChoice);List<Long> v=solved.computeIfAbsent(q.prompt,k->values(q));assertTrue(v.get(1)<=81);assertTrue(v.get(3)<=256);constants.add(v.get(2));verify(q,v);}assertEquals(120,prompts.size());assertEquals(Set.of(0,1,2,3),positions);assertEquals(Set.of(-2L,-1L,0L,1L,2L),constants);}
 @Test public void savedUnweightedQuestionsAndDraftsKeepIdentity(){for(int n:List.of(1,4,81)){Question q=new Question("sec_amgm_minimum","x>0일 때 x+"+n+"/x의 최솟값은?","",Long.toString(2*root(n)));q.studyGuide=new StudyGuide().step("옛 도움","2√"+n+" = ","",Long.toString(2*root(n)));verify(q,values(q));HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft draft=new HelpPlan.Draft();draft.questionId=q.id;draft.stage=1;draft.entries=new ArrayList<>(List.of("9"));assertEquals(0,p.restore(draft,q.id).stage);draft.entries.set(0,"1");draft.stage=1;assertEquals(1,HelpPlan.forQuestion(q).restore(draft.copy(),q.id).stage);}}
}
