package com.gomgomapps.math.core;
import org.junit.Test;
import java.util.*;
import java.util.regex.*;
import static org.junit.Assert.*;
public class BrazilPowerRootTest {
 private static final String PACK="br-bncc-fundamental-2017-v1";
 @Test public void signedBasesAndAllIntegerExponentSignsSupply100DistinctProblems(){
  Generator g=new Generator(new Random(20261006861L));Set<String> seen=new LinkedHashSet<>();Set<Integer> signs=new HashSet<>(),bases=new HashSet<>(),positions=new HashSet<>();
  for(int i=0;i<100;i++){Question q=g.next("integerPowerValue",seen,i%2==0,GlobalCurriculum.limits(PACK,"integerPowerValue",8));assertTrue(seen.add(q.signature()));Matcher m=Pattern.compile("\\((-?\\d+)\\)\\^\\((-?\\d+)\\)\\n.*").matcher(q.prompt);assertTrue(q.prompt,m.matches());long base=Long.parseLong(m.group(1));int exponent=Integer.parseInt(m.group(2));long power=1;for(int j=0;j<Math.abs(exponent);j++)power*=base;Rational answer=exponent<0?Rational.of(1,power):Rational.of(power);verify(q,List.of(answer.toString()));assertEquals(exponent<0?2:1,q.studyGuide.frames.size());assertEquals(String.valueOf(power),q.studyGuide.frames.get(0).expected);if(exponent<0)assertEquals(answer.toString(),q.studyGuide.frames.get(1).expected);signs.add(Integer.signum(exponent));bases.add(Long.signum(base));choices(q,positions);}
  assertEquals(Set.of(-1,0,1),signs);assertEquals(Set.of(-1,1),bases);assertEquals(Set.of(0,1,2,3),positions);
 }
 @Test public void rootsAndFractionalPowersSupply100DistinctNumericalRelations(){
  Generator g=new Generator(new Random(20261006862L));Set<String> seen=new LinkedHashSet<>();Set<Integer> degrees=new HashSet<>(),powers=new HashSet<>(),positions=new HashSet<>();
  for(int i=0;i<100;i++){Question q=g.next("rootPowerLink",seen,i%2==0,GlobalCurriculum.limits(PACK,"rootPowerLink",8));assertTrue(seen.add(q.signature()));Matcher m=Pattern.compile("(\\d+)\\^\\((\\d+)/(\\d+)\\) = \\(([√∛])(\\d+)\\)\\^(\\d+)\\n.*").matcher(q.prompt);assertTrue(q.prompt,m.matches());long given=Long.parseLong(m.group(1));int power=Integer.parseInt(m.group(2)),degree=Integer.parseInt(m.group(3)),root=0;assertEquals(given,Long.parseLong(m.group(5)));assertEquals(power,Integer.parseInt(m.group(6)));assertEquals(degree==2?"√":"∛",m.group(4));for(int candidate=1;candidate<=100;candidate++){long value=1;for(int j=0;j<degree;j++)value*=candidate;if(value==given){root=candidate;break;}}assertTrue(root>0);long answer=1;for(int j=0;j<power;j++)answer*=root;verify(q,List.of(String.valueOf(answer)));assertEquals(String.valueOf(root),q.studyGuide.frames.get(0).expected);assertEquals(String.valueOf(answer),q.studyGuide.frames.get(1).expected);degrees.add(degree);powers.add(power);choices(q,positions);}
  assertEquals(Set.of(2,3),degrees);assertEquals(Set.of(1,2,3,4),powers);assertEquals(Set.of(0,1,2,3),positions);
 }
 @Test public void pureSquareEquationsIncludeZeroAndBothRealRootOrders(){
  Generator g=new Generator(new Random(20261006863L));Set<String> seen=new LinkedHashSet<>();boolean zero=false,negativeCoefficient=false;
  for(int i=0;i<100;i++){Question q=g.next("pureSquareEquation",seen,false,GlobalCurriculum.limits(PACK,"pureSquareEquation",8));assertTrue(seen.add(q.signature()));Matcher m=Pattern.compile("(-?\\d+)x² = (-?\\d+)\\n.*").matcher(q.prompt);assertTrue(q.prompt,m.matches());long a=Long.parseLong(m.group(1)),b=Long.parseLong(m.group(2));List<String> answer=new ArrayList<>();for(int candidate=-100;candidate<=100;candidate++)if(a*candidate*candidate==b)answer.add(String.valueOf(candidate));assertFalse(answer.isEmpty());verify(q,answer);Collections.reverse(answer);assertTrue(new Checker().check(q,List.of(),answer).correct());if(answer.size()==2)assertFalse(new Checker().check(q,List.of(),List.of(answer.get(0),answer.get(0))).correct());assertEquals(String.valueOf(b/a),q.studyGuide.frames.get(0).expected);long root=Math.round(Math.sqrt(b/a));assertEquals(String.valueOf(root),q.studyGuide.frames.get(1).expected);if(root>0)assertEquals(String.valueOf(-root),q.studyGuide.frames.get(2).expected);zero|=b==0;negativeCoefficient|=a<0;}
  assertTrue(zero);assertTrue(negativeCoefficient);
 }
 @Test public void eighthGradeDiagnosisDoesNotIncludeTheThreeNewUnits(){Learning.Profile p=new Learning.Profile();GlobalCurriculum.chooseCountry(p,"BR");GlobalCurriculum.choosePack(p,PACK);p.grade=8;for(String id:List.of("integerPowerValue","rootPowerLink","pureSquareEquation")){assertTrue(GlobalCurriculum.pack(p).inGrade(id,8));assertFalse(GlobalCurriculum.scope(p).stream().anyMatch(s->s.id.equals(id)));}}
 @Test public void brazilMappingsDoNotMoveKoreanPowerAndQuadraticGradeMetadata(){assertEquals(Catalog.get("negativePower").grade,Catalog.get("integerPowerValue").grade);assertEquals(Catalog.get("negativePower").grade,Catalog.get("rootPowerLink").grade);assertEquals(Catalog.get("quadratic").grade,Catalog.get("pureSquareEquation").grade);Learning.Profile p=new Learning.Profile();p.grade=9;p.term=1;List<Catalog.Skill> scope=Learning.diagnosticScope(p);assertTrue(scope.stream().anyMatch(s->s.id.equals("linear")));for(String id:List.of("integerPowerValue","rootPowerLink","pureSquareEquation"))assertFalse(id,scope.stream().anyMatch(s->s.id.equals(id)));}
 private static void verify(Question q,List<String> solved){assertArrayEquals(q.prompt,solved.toArray(String[]::new),q.answers);assertTrue(new Checker().check(q,List.of(),solved).correct());List<String> wrong=new ArrayList<>(solved);wrong.set(0,Expression.number(wrong.get(0)).add(Rational.ONE).toString());assertFalse(new Checker().check(q,List.of(),wrong).correct());assertFalse(q.studyGuide.transfer);assertFalse(HelpPlan.forQuestion(q).canTransfer());}
 private static void choices(Question q,Set<Integer> positions){if(q.choices.isEmpty())return;assertEquals(4,new HashSet<>(q.choices).size());assertEquals(q.answers[0],q.choices.get(q.correctChoice));positions.add(q.correctChoice);}
}
