package com.gomgomapps.math.core;
import org.junit.Test;
import java.util.*;
import java.util.regex.*;
import static org.junit.Assert.*;
public class BrazilCountingSequenceTest {
 private static final String PACK="br-bncc-fundamental-2017-v1";
 @Test public void independentStagesProduce100UniquePublicProblems(){Generator g=new Generator(new Random(20261006871L));Set<String> seen=new LinkedHashSet<>();Set<Integer> positions=new HashSet<>(),stages=new HashSet<>();for(int i=0;i<100;i++){Question q=g.next("choiceProduct",seen,i%2==0,GlobalCurriculum.limits(PACK,"choiceProduct",8));assertTrue(seen.add(q.signature()));Matcher m=Pattern.compile("([0-9]+)가지").matcher(q.prompt);List<Integer> counts=new ArrayList<>();while(m.find())counts.add(Integer.parseInt(m.group(1)));assertTrue(counts.size()==2||counts.size()==3);assertTrue(q.prompt.contains("선택은 제한되지 않습니다"));long total=0;for(int a=0;a<counts.get(0);a++)for(int b=0;b<counts.get(1);b++){if(counts.size()==2)total++;else for(int c=0;c<counts.get(2);c++)total++;}verify(q,total,positions);assertEquals(String.valueOf(counts.get(0)*counts.get(1)),q.studyGuide.frames.get(0).expected);if(counts.size()==3)assertEquals(String.valueOf(total),q.studyGuide.frames.get(1).expected);stages.add(counts.size());}assertEquals(Set.of(2,3),stages);assertEquals(Set.of(0,1,2,3),positions);}
 @Test public void directRulesAreIndependentlyEvaluatedFromPublicFormula(){Generator g=new Generator(new Random(20261006872L));Set<String> seen=new LinkedHashSet<>();Set<Integer> positions=new HashSet<>(),signs=new HashSet<>();for(int i=0;i<100;i++){Question q=g.next("directTermRule",seen,i%2==0,GlobalCurriculum.limits(PACK,"directTermRule",8));assertTrue(seen.add(q.signature()));Matcher m=Pattern.compile("a_n = [(](-?[0-9]+)[)] × n [+] [(](-?[0-9]+)[)]\\nn = ([0-9]+)일 때 a_n의 값을 구하세요[.]").matcher(q.prompt);assertTrue(q.prompt,m.matches());long coefficient=Long.parseLong(m.group(1)),offset=Long.parseLong(m.group(2)),product=0;int n=Integer.parseInt(m.group(3));for(int k=0;k<n;k++)product+=coefficient;long result=product+offset;verify(q,result,positions);assertEquals(String.valueOf(product),q.studyGuide.frames.get(0).expected);assertEquals(String.valueOf(result),q.studyGuide.frames.get(1).expected);signs.add(Long.signum(coefficient));}assertEquals(Set.of(-1,1),signs);assertEquals(Set.of(0,1,2,3),positions);}
 @Test public void recursiveRulesAdvanceExactlyOneTermPerFrame(){Generator g=new Generator(new Random(20261006873L));Set<String> seen=new LinkedHashSet<>();Set<Integer> positions=new HashSet<>(),lengths=new HashSet<>(),multipliers=new HashSet<>();for(int i=0;i<100;i++){Question q=g.next("recursiveTermRule",seen,i%2==0,GlobalCurriculum.limits(PACK,"recursiveTermRule",8));assertTrue(seen.add(q.signature()));Matcher m=Pattern.compile("a_1 = (-?[0-9]+)\\na_[(]n[+]1[)] = ([0-9]+) × a_n [+] [(](-?[0-9]+)[)]\\na_([0-9]+)의 값을 구하세요[.]").matcher(q.prompt);assertTrue(q.prompt,m.matches());long value=Long.parseLong(m.group(1)),factor=Long.parseLong(m.group(2)),offset=Long.parseLong(m.group(3));int n=Integer.parseInt(m.group(4));assertEquals(n-1,q.studyGuide.frames.size());for(int k=2;k<=n;k++){long next=offset;for(int t=0;t<factor;t++)next+=value;value=next;assertEquals(String.valueOf(value),q.studyGuide.frames.get(k-2).expected);}assertNotEquals(q.answers[0],q.expression);assertEquals(Rational.of(value),Expression.number(q.expression));verify(q,value,positions);lengths.add(n);multipliers.add((int)factor);}assertEquals(Set.of(2,3,4,5),lengths);assertEquals(Set.of(1,2,3),multipliers);assertEquals(Set.of(0,1,2,3),positions);}
 @Test public void brazilGradeEightDoesNotShiftKoreanDefaultOrEarlierDiagnosis(){Learning.Profile p=new Learning.Profile();GlobalCurriculum.chooseCountry(p,"BR");GlobalCurriculum.choosePack(p,PACK);p.grade=8;for(String id:List.of("choiceProduct","directTermRule","recursiveTermRule")){assertTrue(GlobalCurriculum.pack(p).inGrade(id,8));assertFalse(GlobalCurriculum.scope(p).stream().anyMatch(s->s.id.equals(id)));}assertEquals(Catalog.get("probability").grade,Catalog.get("choiceProduct").grade);assertEquals(Catalog.get("arithmeticSeq").grade,Catalog.get("directTermRule").grade);assertEquals(Catalog.get("arithmeticSeq").grade,Catalog.get("recursiveTermRule").grade);Learning.Profile korean=new Learning.Profile();korean.grade=8;korean.term=2;assertFalse(Learning.diagnosticScope(korean).stream().anyMatch(x->x.id.equals("choiceProduct")));korean.grade=9;korean.term=1;assertTrue(Learning.diagnosticScope(korean).stream().anyMatch(x->x.id.equals("choiceProduct")));}
 private static void verify(Question q,long answer,Set<Integer> positions){assertEquals(String.valueOf(answer),q.answers[0]);assertTrue(new Checker().check(q,List.of(),List.of(String.valueOf(answer))).correct());assertFalse(new Checker().check(q,List.of(),List.of(String.valueOf(answer+1))).correct());assertFalse(q.studyGuide.transfer);assertFalse(HelpPlan.forQuestion(q).canTransfer());if(!q.choices.isEmpty()){assertEquals(4,new HashSet<>(q.choices).size());assertEquals(q.answers[0],q.choices.get(q.correctChoice));positions.add(q.correctChoice);}}
}
