package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class CombinedCountingRelationsTest {
 private List<Rational> values(Question q){
  String n="[+-]?\\d+(?:\\.\\d+)?(?:/\\d+)?";Matcher m;
  if(q.skillId.equals("sec_quadratic_inequality_system")){
   m=Pattern.compile("\\(x-\\(("+n+")\\)\\)\\(x-\\(("+n+")\\)\\)≤0이고 x>("+n+")를 모두 만족하는 정수 x는 몇 개인가요\\?").matcher(q.prompt);assertTrue(m.matches());
   Rational a=Expression.number(m.group(1)),b=Expression.number(m.group(2)),c=Expression.number(m.group(3));int firstA=100,firstC=100,lastB=-100,count=0;
   for(int x=-100;x<=100;x++){Rational v=Rational.of(x);if(v.compareTo(a)>=0)firstA=Math.min(firstA,x);if(v.compareTo(c)>0)firstC=Math.min(firstC,x);if(v.compareTo(b)<=0)lastB=Math.max(lastB,x);if(v.sub(a).mul(v.sub(b)).compareTo(Rational.ZERO)<=0&&v.compareTo(c)>0)count++;}
   return List.of(a,b,c,Rational.of(firstA),Rational.of(firstC),Rational.of(Math.max(firstA,firstC)),Rational.of(lastB),Rational.of(count));
  }
  boolean add=q.skillId.equals("sec_count_addition");m=Pattern.compile(add?"서로 겹치지 않는 A 방법이 ("+n+")가지, B 방법이 ("+n+")가지입니다\\. A 또는 B를 고르는 방법은\\?":"상의 ("+n+")벌과 하의 ("+n+")벌 중 각각 하나씩 고르는 방법은\\?").matcher(q.prompt);assertTrue(m.matches());Rational a=Expression.number(m.group(1)),b=Expression.number(m.group(2));int aa=Integer.parseInt(a.toString()),bb=Integer.parseInt(b.toString());Set<String> outcomes=new HashSet<>();if(add){for(int i=0;i<aa;i++)outcomes.add("A"+i);for(int i=0;i<bb;i++)outcomes.add("B"+i);}else for(int i=0;i<aa;i++)for(int j=0;j<bb;j++)outcomes.add(i+":"+j);return List.of(a,b,Rational.of(outcomes.size()));
 }
 private void verify(Question q,List<Rational> v){String id=q.id,sig=q.signature(),prompt=q.prompt;StudyDiagram diagram=q.diagram;Arrays.fill(q.answers,"999999");q.choiceInputs=new Rational[]{Rational.of(999999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(v.size(),p.size());assertFalse(p.canTransfer());assertEquals(id,q.id);assertEquals(sig,q.signature());assertEquals(prompt,q.prompt);assertSame(diagram,q.diagram);for(int i=0;i<p.size();i++){assertTrue(p.step(i).accepts(v.get(i).toString()));assertFalse(p.step(i).accepts(v.get(i).add(Rational.ONE).toString()));assertEquals("",p.step(i).after);}}
 @Test public void independentOutcomeAndIntegerEnumerationChecksGeneratedProblems(){Generator g=new Generator(new Random(2100));Set<String> cases=new HashSet<>();for(String skill:List.of("sec_quadratic_inequality_system","sec_count_addition","sec_count_multiplication")){Set<String> prompts=new HashSet<>();Set<Integer> positions=new HashSet<>();for(int i=0;i<1200;i++){Question q=g.next(skill,List.of(),i%2==0);List<Rational> v=values(q);Rational answer=v.get(v.size()-1);if(skill.equals("sec_quadratic_inequality_system"))cases.add(v.get(2).compareTo(v.get(0))<0?"full":v.get(2).compareTo(v.get(1))>=0?"empty":"partial");prompts.add(q.prompt);if(q.correctChoice>=0)positions.add(q.correctChoice);assertTrue(new Checker().check(q,List.of(),List.of(answer.toString())).correct());assertFalse(new Checker().check(q,List.of(),List.of(answer.add(Rational.ONE).toString())).correct());verify(q,v);}assertTrue(skill+prompts.size(),prompts.size()>100);assertEquals(Set.of(0,1,2,3),positions);}assertEquals(Set.of("full","partial","empty"),cases);}
 @Test public void savedFractionBoundariesEmptyIntervalsAndDrafts(){for(Question q:List.of(new Question("sec_quadratic_inequality_system","(x-(-3/2))(x-(5/2))≤0이고 x>-1/2를 모두 만족하는 정수 x는 몇 개인가요?","","3"),new Question("sec_quadratic_inequality_system","(x-(-3))(x-(2))≤0이고 x>3를 모두 만족하는 정수 x는 몇 개인가요?","","0"),new Question("sec_count_addition","서로 겹치지 않는 A 방법이 2가지, B 방법이 3가지입니다. A 또는 B를 고르는 방법은?","","5"),new Question("sec_count_multiplication","상의 2벌과 하의 3벌 중 각각 하나씩 고르는 방법은?","","6"))){List<Rational> v=values(q);verify(q,v);HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of(v.get(0).toString()));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));assertTrue(d.teachingVersion.endsWith("relations-v1"));d.entries.set(0,v.get(0).toString());d.stage=1;assertEquals(1,HelpPlan.forQuestion(q).restore(d.copy(),q.id).stage);}}
}
