package com.gomgomapps.math.core;
import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class CombinedEqualityPracticeTest {
 static int eval(int a,int b,int op){return switch(op){case 0->a+b;case 1->a-b;case 2->a*b;default->a/b;};}
 @Test public void everyVisibleConditionIsIndependentlySolvedAndKeysIgnored(){for(String id:List.of(CombinedEqualityPractice.STORY,CombinedEqualityPractice.EQUAL)){Set<String> distinct=new HashSet<>();Set<Integer> modes=new HashSet<>();Set<String> operations=new HashSet<>();assertTrue(CombinedEqualityPractice.count(id)>100);for(int i=0;i<CombinedEqualityPractice.count(id);i++){Question q=CombinedEqualityPractice.at(id,i);assertTrue(q.prompt,distinct.add(q.signature()));int[] v=CombinedEqualityPractice.read(q);assertNotNull(v);int result;if(id.equals(CombinedEqualityPractice.STORY)){modes.add(v[0]);int initial=v[0]<2?v[1]*v[2]:v[2];result=v[0]%2==0?initial+v[3]:initial-v[3];}else{operations.add(v[2]+":"+v[4]);int left=eval(v[0],v[1],v[2]);result=Integer.parseInt(q.answers[0]);assertEquals(left,eval(result,v[3],v[4]));if(v[4]==3)assertEquals(0,result%v[3]);}assertEquals(""+result,q.answers[0]);q.answers=new String[]{"poison"};q.expression="poison";assertTrue(new Checker().check(q,List.of(),List.of(""+result)).correct());assertEquals(Checker.Status.WRONG_ANSWER,new Checker().check(q,List.of(),List.of(""+(result+1))).status);}if(id.equals(CombinedEqualityPractice.STORY))assertEquals(Set.of(0,1,2,3),modes);else assertEquals(16,operations.size());}}
 @Test public void helpUsesOnlyBlankRelationshipsAndCheckedStudentReferences(){for(String id:List.of(CombinedEqualityPractice.STORY,CombinedEqualityPractice.EQUAL))for(int i=0;i<CombinedEqualityPractice.count(id);i+=61){Question q=CombinedEqualityPractice.at(id,i);HelpPlan plan=HelpPlan.forQuestion(q);assertEquals(5,plan.size());assertFalse(plan.canTransfer());int[] v=CombinedEqualityPractice.read(q);int a,b,first,c,last=Integer.parseInt(q.answers[0]);if(id.equals(CombinedEqualityPractice.STORY)){a=v[0]<2?v[1]:v[1]*v[2];b=v[0]<2?v[2]:v[1];first=v[0]<2?a*b:a/b;c=v[3];}else{a=v[0];b=v[1];first=eval(a,b,v[2]);c=v[3];}int[] expected={a,b,first,c,last};for(int j=0;j<5;j++){assertTrue(plan.step(j).accepts(""+expected[j]));assertFalse(plan.step(j).accepts(""));assertFalse(plan.step(j).before.matches(".*\\d.*"));assertEquals("",plan.step(j).after);for(int r:CombinedEqualityPractice.referenceIndices(j))assertTrue(r<j);}}}
 @Test public void freshSuppliesAndExplicitYearFivePlacement(){var pack=GlobalCurriculum.packs("GB").stream().filter(p->p.id.equals("england-primary-2021-v1")).findFirst().orElseThrow();for(String id:List.of(CombinedEqualityPractice.STORY,CombinedEqualityPractice.EQUAL)){assertTrue(pack.inGrade(id,5));assertFalse(pack.inGrade(id,4));assertFalse(Curriculum.inCurriculum(Catalog.get(id),2022));Generator gen=new Generator(new Random(173));List<String> recent=new ArrayList<>();Set<Integer> positions=new HashSet<>();for(int i=0;i<100;i++){Question q=gen.next(id,recent,i%2==0,GlobalCurriculum.limits(pack.id,id,5));assertFalse(recent.contains(q.signature()));recent.add(q.signature());assertNotNull(CombinedEqualityPractice.read(q));if(!q.choices.isEmpty()){assertEquals(4,new HashSet<>(q.choices).size());assertEquals(q.answers[0],q.choices.get(q.correctChoice));positions.add(q.correctChoice);}}assertEquals(Set.of(0,1,2,3),positions);}}
 @Test public void equalityRejectsNonintegralOrInvalidGivensAndZeroIsValid(){Question q=new Question(CombinedEqualityPractice.EQUAL,"양쪽 값이 같도록 빈칸을 채우세요.\n12 − 12 = □ × 2","poison","poison");assertTrue(new Checker().check(q,List.of(),List.of("0")).correct());for(String line:List.of("12 ÷ 5 = □ + 2","12 − 12 = □ + 2","12 + 2 = □ × 3","1 − 12 = □ ÷ 2","12 + 2 = □ ÷ 0")){q.prompt="양쪽 값이 같도록 빈칸을 채우세요.\n"+line;assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(q,List.of(),List.of("1")).status);}q=CombinedEqualityPractice.at(CombinedEqualityPractice.STORY,0);for(String raw:List.of("","1/2","1.5","1234567"))assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(q,List.of(),List.of(raw)).status);assertEquals(Checker.Status.WRONG_ANSWER,new Checker().check(q,List.of(),List.of("−1")).status);}
}
