package com.gomgomapps.math.core;
import java.math.*;import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class ComparisonRelationsTest {
 private void check(Question q){String original=q.signature();HelpPlan p=HelpPlan.forQuestion(q);assertNotNull(p);assertFalse(p.canTransfer());assertEquals(original,q.signature());List<String> expected=new ArrayList<>();int cmp;
  if(q.skillId.equals("el_decimal_compare")){String[] parts=q.prompt.split("\\s+□\\s+");BigDecimal l=new BigDecimal(parts[0]),r=new BigDecimal(parts[1]);cmp=l.compareTo(r);expected.add(l.toBigInteger().toString());expected.add(r.toBigInteger().toString());if(l.toBigInteger().equals(r.toBigInteger())){int places=Math.max(l.scale(),r.scale());for(int i=1;i<=places;i++){int ld=l.movePointRight(i).toBigInteger().mod(BigInteger.TEN).intValue(),rd=r.movePointRight(i).toBigInteger().mod(BigInteger.TEN).intValue();expected.add(""+ld);expected.add(""+rd);if(ld!=rd)break;}}}
  else{Matcher m=Pattern.compile("\\d+").matcher(q.prompt);List<Long> v=new ArrayList<>();while(m.find())v.add(Long.parseLong(m.group()));long a=v.get(0),b=v.get(1),c=v.get(2),d=v.get(3);cmp=BigInteger.valueOf(a).multiply(BigInteger.valueOf(d)).compareTo(BigInteger.valueOf(c).multiply(BigInteger.valueOf(b)));if(q.skillId.equals("fracCompare"))expected.addAll(List.of(""+b,""+a,""+c));else expected.addAll(List.of(""+a,""+b,""+c,""+d,""+(b*d),""+(a*d),""+(c*b)));}
  expected.add(cmp<0?"<":cmp>0?">":"=");assertEquals(expected.size(),p.size());for(int i=0;i<p.size()-1;i++){assertTrue(p.step(i).accepts(expected.get(i)));assertFalse(p.step(i).accepts(""));assertFalse(p.step(i).accepts(new BigDecimal(expected.get(i)).add(BigDecimal.ONE).toPlainString()));assertEquals("",p.step(i).after);if(!q.skillId.equals("el_decimal_compare"))assertFalse(p.step(i).before.matches(".*[0-9].*"));}
  for(String sign:List.of("<","=",">"))assertEquals(sign.equals(expected.get(expected.size()-1)),p.step(p.size()-1).accepts(sign));HelpPlan.Draft draft=new HelpPlan.Draft();draft.stage=p.size();draft.entries=expected;assertEquals(expected.get(expected.size()-1),p.enteredAnswer(draft));List<String> prior=q.studyGuide.frames.stream().map(f->f.expected).toList();q.expression="999";q.answers=new String[]{"999"};q.givenNumbers.put("answer","999");HelpPlan.forQuestion(q);assertEquals(prior,q.studyGuide.frames.stream().map(f->f.expected).toList());
 }
 @Test public void threeComparisonsHaveDistinctPromptsAndAllSigns(){Generator g=new Generator(new Random(710310));for(String id:List.of("fracCompare","el_fraction_compare","el_decimal_compare")){Set<String> seen=new HashSet<>(),signs=new HashSet<>();for(int i=0;i<4000;i++){Question q=g.next(id,List.of(),false);seen.add(q.prompt);signs.add(q.answers[0]);check(q);}assertTrue(id+" "+seen.size(),seen.size()>100);assertTrue(signs.containsAll(List.of("<",">")));if(!id.equals("el_decimal_compare"))assertTrue(signs.contains("="));}}
 @Test public void decimalComparisonStopsAtFirstDifferentPlaceAndHandlesEqualValues(){for(String text:List.of("7.4  □  7.38","7.03  □  7.09","7.4  □  7.40","7  □  7.00","0.003  □  0.004","9.99  □  10"))check(new Question("el_decimal_compare",text,"","?"));}
 @Test public void draftsKeepCheckedInputsAndResetOldGuides(){Question q=new Generator(new Random(710311)).next("el_fraction_compare",List.of(),false);HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft draft=new HelpPlan.Draft();draft.questionId=q.id;draft.stage=1;draft.entries=new ArrayList<>(List.of("old"));draft=p.restore(draft,q.id);assertEquals(0,draft.stage);draft.entries.set(0,q.studyGuide.frames.get(0).expected);draft.stage=1;assertEquals(1,p.restore(draft,q.id).stage);}
}
