package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class ConditionRelationsTest {
 private long[] publicNumbers(Question q){Matcher m=Pattern.compile("(?:실수 x에 대해 )?p: (.+), q: (.+)일 때.*").matcher(q.prompt);assertTrue(m.matches());String linear=m.group(1).startsWith("x=")?m.group(1):m.group(2),square=m.group(1).startsWith("x=")?m.group(2):m.group(1);long c=Long.parseLong(linear.substring(2));Matcher s=Pattern.compile("(?:x|\\(x-\\((-?\\d+)\\)\\))²=(\\d+)").matcher(square);assertTrue(s.matches());return new long[]{s.group(1)==null?0:Long.parseLong(s.group(1)),c,Long.parseLong(s.group(2))};}
 private List<Long> values(Question q){long[] n=publicNumbers(q);long h=n[0],c=n[1],s=n[2];boolean necessary=q.prompt.contains("필요조건"),linearP=q.prompt.contains("p: x=");boolean valid=true;for(int x=-30;x<=30;x++){boolean p=linearP?x==c:(x-h)*(x-h)==s,r=linearP?(x-h)*(x-h)==s:x==c;if(necessary?r&&!p:p&&!r)valid=false;}return List.of(necessary?0L:1L,h,c,s,c-h,(c-h)*(c-h),h-(c-h),valid?1L:0L);}
 private void verify(Question q){List<Long> v=values(q);assertTrue(new Checker().check(q,List.of(),List.of(v.get(7).toString())).correct());String id=q.id,prompt=q.prompt;Arrays.fill(q.answers,"999");q.givenNumbers.replaceAll((k,x)->"999");q.choiceInputs=new Rational[]{Rational.of(999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(8,p.size());assertFalse(p.canTransfer());assertEquals(id,q.id);assertEquals(prompt,q.prompt);for(int i=0;i<8;i++){assertTrue(p.step(i).accepts(v.get(i).toString()));assertFalse(p.step(i).accepts(Long.toString(p.step(i).options.isEmpty()?v.get(i)+1:1-v.get(i))));assertEquals("",p.step(i).after);assertFalse(p.step(i).before.matches(".*[0-9].*"));}}
 @Test public void necessarySufficientBothDirectionsZeroAndVariedPublicConditions(){Generator g=new Generator(new Random(2801));Set<String> prompts=new HashSet<>();Set<String> kinds=new HashSet<>();Set<Integer> positions=new HashSet<>();int zeros=0;for(int i=0;i<16000;i++){Question q=g.next("sec_sufficient_condition",List.of(),i%2==0);prompts.add(q.prompt);positions.add(q.correctChoice);kinds.add((q.prompt.contains("필요조건")?"necessary":"sufficient")+(q.prompt.contains("p: x=")?"linear":"square")+values(q).get(7));if(publicNumbers(q)[0]==publicNumbers(q)[1])zeros++;verify(q);}assertEquals(684,prompts.size());assertEquals(6,kinds.size());assertEquals(Set.of(0,1),positions);assertTrue(zeros>0);}
 @Test public void savedLegacyHelpIsReplacedWithoutChangingQuestionOrNewDraft(){for(Question q:List.of(new Question("sec_sufficient_condition","p: x=-3, q: x²=9일 때 p가 q이기 위한 충분조건인지 고르세요.","","1"),new Question("sec_sufficient_condition","p: x²=9, q: x=-3일 때 p가 q이기 위한 충분조건인지 고르세요.","","0"),new Question("sec_sufficient_condition","p: x²=0, q: x=0일 때 p가 q이기 위한 충분조건인지 고르세요.","","1"))){q.studyGuide=new StudyGuide().step("옛 도움","-3² = ","","9");verify(q);HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft draft=new HelpPlan.Draft();draft.questionId=q.id;draft.stage=1;draft.entries=new ArrayList<>(List.of("9"));assertEquals(0,p.restore(draft,q.id).stage);draft.entries.set(0,"1");draft.stage=1;assertEquals(1,HelpPlan.forQuestion(q).restore(draft.copy(),q.id).stage);}}
}
