package com.gomgomapps.math.core;
import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class ConvenientNumberMentalTest {
 private int nearest(int b,int unit){int lower=b/unit*unit,upper=lower+unit;return b-lower<upper-b?lower:upper;}
 private void verify(Question q){String[] lines=q.prompt.split("\n"),parts=lines[0].split(" ");int a=Integer.parseInt(parts[0]),b=Integer.parseInt(parts[2]),u=Integer.parseInt(lines[1].substring(ConvenientNumberMental.UNIT.length())),round=nearest(b,u),gap=Math.abs(round-b);boolean add=parts[1].equals("+");int result=add?a+b:a-b;int provisional=add?a+round:a+round-b;int[] entries={a,round,gap,provisional,result};assertTrue(provisional>=0&&result>=0);q.answers=new String[]{"poison"};q.expression="poison";assertTrue(new Checker().check(q,List.of(),List.of(""+result)).correct());assertEquals(Checker.Status.WRONG_ANSWER,new Checker().check(q,List.of(),List.of(""+(result+1))).status);HelpPlan h=HelpPlan.forQuestion(q);assertEquals(5,h.size());assertFalse(h.canTransfer());assertTrue(h.restore(null,q.id).entries.stream().allMatch(String::isEmpty));for(int i=0;i<entries.length;i++){assertTrue(h.step(i).accepts(""+entries[i]));assertFalse(h.step(i).accepts(""+(entries[i]+1)));assertFalse(h.step(i).before.matches(".*[0-9].*"));}}
 @Test public void actualSupplyUsesEveryUnitAndBothCorrectionDirections(){for(String id:List.of(ConvenientNumberMental.ADD,ConvenientNumberMental.SUB)){CurriculumLimits limits=GlobalCurriculum.limits("england-primary-2021-v1",id,5);assertTrue(limits.allows(ConvenientNumberMental.make(id,999999,999991,1000000)));Generator g=new Generator(new Random(159));List<String> recent=new ArrayList<>();Set<Boolean> directions=new HashSet<>();for(int i=0;i<300;i++){Question q=g.next(id,recent,false,limits);assertFalse(recent.contains(q.signature()));recent.add(q.signature());int[] v=ConvenientNumberMental.read(q);directions.add(v[3]>v[1]);assertTrue(q.choices.isEmpty());verify(q);}assertEquals(Set.of(true,false),directions);}for(int u:new int[]{10,100,1000,10000,100000,1000000})for(String id:List.of(ConvenientNumberMental.ADD,ConvenientNumberMental.SUB))verify(ConvenientNumberMental.make(id,999999,1000000-1,u));verify(ConvenientNumberMental.make(ConvenientNumberMental.SUB,1005,1005,10));verify(ConvenientNumberMental.make(ConvenientNumberMental.ADD,1000,1001,1000));}
 @Test public void independentSmallDomainExhaustionAndIndexedEdges(){for(String id:List.of(ConvenientNumberMental.ADD,ConvenientNumberMental.SUB)){Set<String> expected=new HashSet<>();for(int a=1000;a<=1014;a++)for(int b=1000;b<=1014;b++)for(int u:new int[]{10,100,1000,10000,100000,1000000}){int gap=Math.abs(nearest(b,u)-b);if(gap>=1&&gap<=9&&(id.equals(ConvenientNumberMental.ADD)||a>=b))expected.add(ConvenientNumberMental.make(id,a,b,u).signature());}assertEquals(expected.size(),ConvenientNumberMental.count(id,1014));Set<String> indexed=new HashSet<>();for(long i=0;i<expected.size();i++){Question q=ConvenientNumberMental.indexed(id,1014,i);assertTrue(indexed.add(q.signature()));verify(q);}assertEquals(expected,indexed);CurriculumLimits limits=new CurriculumLimits("wholeDigits=4;secondDigits=4;maxGiven=1014;maxResult=2028;nonnegative=true");Generator g=new Generator(new Random(159));List<String> recent=new ArrayList<>();for(int i=0;i<expected.size();i++){Question q=g.next(id,recent,false,limits);assertFalse(recent.contains(q.signature()));recent.add(q.signature());}assertEquals(expected,new HashSet<>(recent));assertEquals(recent.get(0),g.next(id,recent,false,limits).signature());long count=ConvenientNumberMental.count(id,999999);assertTrue(count>Integer.MAX_VALUE);for(long i:new long[]{0,1,100000,count/2,count-2,count-1})verify(ConvenientNumberMental.indexed(id,999999,i));}}
 @Test public void malformedPublicInstructionsCannotUseHiddenKeys(){for(String text:List.of("1000 + 1001\n편한 수의 단위: 11","1000 + 1050\n편한 수의 단위: 100","1000 + 1000\n편한 수의 단위: 1000","1000 + 999\n편한 수의 단위: 1000","1000 + 1001\n편한 수의 단위: 100000000000000000000")){Question q=ConvenientNumberMental.make(ConvenientNumberMental.ADD,1000,1001,1000);q.prompt=text;assertNull(ConvenientNumberMental.read(q));assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(q,List.of(),List.of("2001")).status);}assertFalse(Curriculum.inCurriculum(Catalog.get(ConvenientNumberMental.ADD),2022));}
}
