package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class CoordinatePolygonTest {
 private int[][] points(String prompt){Matcher m=Pattern.compile("[ABCDEF]\\((-?\\d+), (-?\\d+)\\)").matcher(prompt);int[][] p=new int[6][2];for(int i=0;i<6;i++){assertTrue(m.find());p[i][0]=Integer.parseInt(m.group(1));p[i][1]=Integer.parseInt(m.group(2));}assertFalse(m.find());return p;}
 private int area(int[][] p){int total=0;for(int i=0;i<6;i++)total+=p[i][0]*p[(i+1)%6][1]-p[(i+1)%6][0]*p[i][1];assertEquals(0,total%2);return Math.abs(total)/2;}
 private int[] edges(int[][] p){int[] edges=new int[6];for(int i=0;i<6;i++){int[] a=p[i],b=p[(i+1)%6];assertTrue(a[0]==b[0]||a[1]==b[1]);for(int x=a[0];x!=b[0];x+=Integer.signum(b[0]-a[0]))edges[i]++;for(int y=a[1];y!=b[1];y+=Integer.signum(b[1]-a[1]))edges[i]++;assertTrue(edges[i]>=2);}return edges;}
 @Test public void twoHundredUniqueProblemsIndependentlySolvedWithTeachingAndShuffledOptions(){Generator g=new Generator(new Random(831));for(String id:List.of(CoordinatePolygon.AREA,CoordinatePolygon.PERIM)){Set<String> seen=new HashSet<>();Set<Integer> positions=new HashSet<>();for(int i=0;i<100;i++){Question q=g.next(id,seen,true);assertTrue(seen.add(q.signature()));int[][] p=points(q.prompt);int[] e=edges(p);int n=id.equals(CoordinatePolygon.AREA)?area(p):Arrays.stream(e).sum();assertTrue(new Checker().check(q,List.of(),List.of(""+n)).correct());assertFalse(new Checker().check(q,List.of(),List.of(""+(n+1))).correct());assertEquals(4,new HashSet<>(q.choices).size());assertEquals(""+n,q.choices.get(q.correctChoice));positions.add(q.correctChoice);HelpPlan help=HelpPlan.forQuestion(q);assertFalse(help.canTransfer());assertEquals(7,help.size());int[] values=id.equals(CoordinatePolygon.AREA)?new int[]{e[0],e[1],e[0]*e[1],e[4],e[3],e[4]*e[3],n}:new int[]{e[0],e[1],e[2],e[3],e[4],e[5],n};for(int k=0;k<7;k++){assertTrue(help.step(k).accepts(""+values[k]));assertFalse(help.step(k).accepts(""+(values[k]+1)));}}assertEquals(Set.of(0,1,2,3),positions);}}
 @Test public void sixThousandPolygonsAreConcaveInAllEightOrientationsAndDiagramUsesOnlyPublicGeometry(){Random r=new Random(832);Set<String> directions=new HashSet<>();for(int i=0;i<6000;i++){Question q=CoordinatePolygon.create(Catalog.get(CoordinatePolygon.AREA),r);int[][] p=points(q.prompt);edges(p);for(int[] corner:p)for(int n:corner)assertTrue(n>=-8&&n<=8);int pos=0,neg=0;for(int k=0;k<6;k++){int[] a=p[k],b=p[(k+1)%6],c=p[(k+2)%6];int cross=(b[0]-a[0])*(c[1]-b[1])-(b[1]-a[1])*(c[0]-b[0]);if(cross>0)pos++;else neg++;}assertTrue(pos==1&&neg==5||pos==5&&neg==1);directions.add(Integer.signum(p[1][0]-p[0][0])+","+Integer.signum(p[1][1]-p[0][1])+","+Integer.signum(p[2][0]-p[1][0])+","+Integer.signum(p[2][1]-p[1][1]));double[] geometry=q.diagram.values.clone();for(int k=0;k<6;k++){assertEquals(p[k][0],geometry[2*k],0);assertEquals(p[k][1],geometry[2*k+1],0);}int[] g={(int)geometry[12],(int)geometry[13]};assertEquals(0,(g[0]-p[5][0])*(p[0][1]-p[5][1])-(g[1]-p[5][1])*(p[0][0]-p[5][0]));assertTrue(g[0]>=Math.min(p[5][0],p[0][0])&&g[0]<=Math.max(p[5][0],p[0][0]));assertTrue(g[1]>=Math.min(p[5][1],p[0][1])&&g[1]<=Math.max(p[5][1],p[0][1]));assertEquals(area(p),Integer.parseInt(q.answers[0]));Arrays.fill(q.answers,"999");assertArrayEquals(geometry,q.diagram.values,0);}assertEquals(8,directions.size());}
}
