package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class CoordinateRegionTest {
 private int[][] points(String prompt){Matcher m=Pattern.compile("[ABCD]\\((-?\\d+), (-?\\d+)\\)").matcher(prompt);int[][] result=new int[4][2];for(int i=0;i<4;i++){assertTrue(m.find());result[i][0]=Integer.parseInt(m.group(1));result[i][1]=Integer.parseInt(m.group(2));}assertFalse(m.find());return result;}
 private int boundary(int[][] p){int total=0;for(int i=0;i<4;i++){int[] a=p[i],b=p[(i+1)%4];assertTrue(a[0]==b[0]||a[1]==b[1]);for(int x=a[0];x!=b[0];x+=Integer.signum(b[0]-a[0]))total++;for(int y=a[1];y!=b[1];y+=Integer.signum(b[1]-a[1]))total++;}return total;}
 private int cells(int[][] p){int count=0;for(int x=p[0][0];x<p[1][0];x++)for(int y=p[0][1];y<p[3][1];y++)count++;return count;}
 @Test public void hundredIndependentPerimetersAndAreasWithShuffledOptions(){Generator g=new Generator(new Random(121));for(String id:List.of(CoordinateRegion.PERIM,CoordinateRegion.AREA)){Set<String> seen=new HashSet<>();Set<Integer> positions=new HashSet<>();for(int i=0;i<100;i++){Question q=g.next(id,seen,true);assertTrue(seen.add(q.signature()));int[][] p=points(q.prompt);int n=id.equals(CoordinateRegion.PERIM)?boundary(p):cells(p);assertTrue(new Checker().check(q,List.of(),List.of(""+n)).correct());assertFalse(new Checker().check(q,List.of(),List.of(""+(n+1))).correct());assertEquals(4,new HashSet<>(q.choices).size());assertEquals(""+n,q.choices.get(q.correctChoice));positions.add(q.correctChoice);HelpPlan help=HelpPlan.forQuestion(q);assertEquals(id.equals(CoordinateRegion.PERIM)?5:3,help.size());assertFalse(help.canTransfer());int w=p[1][0]-p[0][0],h=p[3][1]-p[0][1];int[] frames=id.equals(CoordinateRegion.AREA)?new int[]{w,h,n}:new int[]{w,h,w,h,n};for(int stage=0;stage<frames.length;stage++){assertTrue(help.step(stage).accepts(""+frames[stage]));assertFalse(help.step(stage).accepts(""+(frames[stage]+1)));}}assertEquals(Set.of(0,1,2,3),positions);}}
 @Test public void sixThousandPublicRectanglesHaveCorrectGeometry(){Random r=new Random(122);for(String id:List.of(CoordinateRegion.PERIM,CoordinateRegion.AREA))for(int i=0;i<3000;i++){Question q=CoordinateRegion.create(Catalog.get(id),r);int[][] p=points(q.prompt);for(int[] v:p)for(int n:v)assertTrue(n>=-8&&n<=8);assertEquals(p[0][0],p[3][0]);assertEquals(p[1][0],p[2][0]);assertEquals(p[0][1],p[1][1]);assertEquals(p[2][1],p[3][1]);assertTrue(p[1][0]>p[0][0]);assertTrue(p[3][1]>p[0][1]);assertEquals(4,q.diagram.values.length);double[] given=q.diagram.values.clone();Arrays.fill(q.answers,"999");assertArrayEquals(given,q.diagram.values,0);assertEquals("coordinateRectangle",q.diagram.type);}}
}
