package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class CoordinateTriangleTest {
 private int[][] points(Question q){Matcher m=Pattern.compile("[ABC]\\((-?\\d+), (-?\\d+)\\)").matcher(q.prompt);int[][] p=new int[3][2];for(int i=0;i<3;i++){assertTrue(m.find());for(int k=0;k<2;k++)p[i][k]=Integer.parseInt(m.group(k+1));}assertFalse(m.find());return p;}
 private int leg(int[] a,int[] b){assertTrue(a[0]==b[0]||a[1]==b[1]);int n=0;for(int k=0;k<2;k++)for(int x=a[k];x!=b[k];x+=Integer.signum(b[k]-a[k]))n++;return n;}
 private int[] root(int n){int coefficient=1,inside=1;for(int p=2;n>1;p++){int count=0;while(n%p==0){n/=p;count++;}for(int k=0;k<count/2;k++)coefficient*=p;if(count%2==1)inside*=p;}return new int[]{coefficient,inside};}
 @Test public void hundredPerSkillPublicSolutionsChoicesAndCheckedTeaching(){Generator g=new Generator(new Random(941));for(String id:List.of(CoordinateTriangle.AREA,CoordinateTriangle.PERIM)){Set<String> seen=new HashSet<>();Set<Integer> positions=new HashSet<>();for(int i=0;i<100;i++){Question q=g.next(id,seen,true);assertTrue(seen.add(q.signature()));int[][] p=points(q);int w=leg(p[0],p[1]),h=leg(p[0],p[2]),n=w*w+h*h;int[] root=root(n);boolean area=id.equals(CoordinateTriangle.AREA);String answer=area?w*h+"/2":root[1]==1?""+(w+h+root[0]):(w+h)+"+"+(root[0]==1?"":root[0]+"*")+"sqrt("+root[1]+")";assertTrue(q.prompt+" / "+answer+" / "+new Checker().check(q,List.of(),List.of(answer)),new Checker().check(q,List.of(),List.of(answer)).correct());assertFalse(new Checker().check(q,List.of(),List.of("999")).correct());assertEquals(4,new HashSet<>(q.choices).size());assertEquals(Radical.parse(answer),Radical.parse(q.choices.get(q.correctChoice)));positions.add(q.correctChoice);for(String choice:q.choices)assertTrue(Radical.parse(answer).sameShape(Radical.parse(choice)));HelpPlan help=HelpPlan.forQuestion(q);assertFalse(help.canTransfer());int[] entries=area?new int[]{w,h,w*h,2}:new int[]{w,h,w*w,h*h,n,root[0]*root[0],root[1],root[0],w+h};assertEquals(entries.length,help.size());HelpPlan.Draft d=help.restore(null,q.id);for(int k=0;k<entries.length;k++){assertTrue(help.step(k).accepts(""+entries[k]));assertFalse(help.step(k).accepts(""+(entries[k]+1)));d.entries.set(k,""+entries[k]);d.stage++;d.entries.add("");}Arrays.fill(q.answers,"999");assertEquals(Radical.parse(answer),Radical.parse(help.enteredAnswer(d)));d.entries.set(area?2:8,"999");try{help.enteredAnswer(d);fail("Unchecked result component");}catch(IllegalStateException expected){}}assertEquals(Set.of(0,1,2,3),positions);}}
 @Test public void sixThousandPublicTrianglesCoverOrientationsAndExactForms(){Random r=new Random(942);Set<String> orientations=new HashSet<>();boolean half=false,whole=false,irrational=false,integer=false;for(int i=0;i<6000;i++){Question q=CoordinateTriangle.create(Catalog.get(CoordinateTriangle.AREA),r);int[][] p=points(q);int w=leg(p[0],p[1]),h=leg(p[0],p[2]);int dx=p[1][0]-p[0][0],dy=p[1][1]-p[0][1],ex=p[2][0]-p[0][0],ey=p[2][1]-p[0][1];assertEquals(0,dx*ex+dy*ey);orientations.add(Integer.signum(dx)+","+Integer.signum(dy)+","+Integer.signum(ex)+","+Integer.signum(ey));int cross=0;for(int k=0;k<3;k++){cross+=p[k][0]*p[(k+1)%3][1]-p[(k+1)%3][0]*p[k][1];for(int j=0;j<2;j++){assertTrue(p[k][j]>=-8&&p[k][j]<=8);assertEquals(p[k][j],q.diagram.values[2*k+j],0);}}assertEquals(Rational.of(Math.abs(cross)).div(Rational.of(2)),Expression.number(q.answers[0]));assertEquals(w*h,Math.abs(cross));half|=w*h%2==1;whole|=w*h%2==0;int[] root=root(w*w+h*h);integer|=root[1]==1;irrational|=root[1]>1;double[] geometry=q.diagram.values.clone();Arrays.fill(q.answers,"999");assertArrayEquals(geometry,q.diagram.values,0);}assertEquals(8,orientations.size());assertTrue(half&&whole&&integer&&irrational);}
 @Test public void answerScaffoldsStayBlankAndComposeOnlyEnteredFields(){Question area=CoordinateTriangle.create(Catalog.get(CoordinateTriangle.AREA),new Random(3));assertTrue(FractionInput.defaultFraction(area));assertArrayEquals(new String[]{"",""},FractionInput.parts(""));assertEquals("",RadicalAnswerFrame.compose(List.of("","","")));assertEquals("",RadicalAnswerFrame.compose(List.of("7","2","")));assertEquals(Radical.parse("7+2*sqrt(5)"),Radical.parse(RadicalAnswerFrame.compose(List.of("7","2","5"))));assertEquals(Radical.parse("12"),Radical.parse(RadicalAnswerFrame.compose(List.of("7","5","1"))));}

 @Test public void integerPerimeterFrameAcceptedWithoutBroadeningRootSimplification(){Question q=CoordinateTriangle.create(Catalog.get(CoordinateTriangle.PERIM),new Random(3));q.answers=new String[]{"12"};String entered=RadicalAnswerFrame.compose(List.of("7","5","1"));assertTrue(new Checker().check(q,List.of(),List.of(entered)).correct());assertTrue(new Checker().check(q,List.of(),List.of("7+5")).correct());assertFalse(new Checker().check(q,List.of(),List.of("7+6")).correct());assertFalse(new Checker().check(q,List.of(),List.of("7+sqrt(25)")).correct());q.skillId="rootAddSub";assertFalse(new Checker().check(q,List.of(),List.of(entered)).correct());}
}
