package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class CoordinateCalculationRelationsTest {
 private List<Rational> values(Question q){
  List<Rational> numbers=new ArrayList<>();Matcher m=Pattern.compile("[+-]?\\d+(?:\\.\\d+)?(?:/\\d+)?").matcher(q.prompt);while(m.find())numbers.add(Expression.number(m.group()));
  if(q.skillId.equals("sec_line_equation")){assertEquals(3,numbers.size());Rational a=numbers.get(0),b=numbers.get(1),x=numbers.get(2);return List.of(a,b,x,a.mul(x),a.mul(x).add(b));}
  assertEquals(q.skillId.equals("sec_point_distance")?4:6,numbers.size());Rational ax=numbers.get(0),ay=numbers.get(1),bx=numbers.get(2),by=numbers.get(3),dx=bx.sub(ax),dy=by.sub(ay);
  if(q.skillId.equals("sec_point_distance")){Rational u=dx.mul(dx),v=dy.mul(dy),sum=u.add(v);return List.of(dx,dy,u,v,sum,sum.sqrt());}
  Rational ratioA=numbers.get(4),ratioB=numbers.get(5),total=ratioA.add(ratioB),ux=dx.div(total),uy=dy.div(total),ox=ux.mul(ratioA),oy=uy.mul(ratioA);
  // Independently solve the final coordinates by weighted averages, not the movement chain.
  Rational px=ratioB.mul(ax).add(ratioA.mul(bx)).div(total),py=ratioB.mul(ay).add(ratioA.mul(by)).div(total);
  assertEquals(px,ax.add(ox));assertEquals(py,ay.add(oy));return List.of(ratioA,ratioB,total,dx,ux,ox,px,dy,uy,oy,py);
 }
 private void verify(Question q,List<Rational> expected){String id=q.id,sig=q.signature(),prompt=q.prompt;StudyDiagram diagram=q.diagram;Arrays.fill(q.answers,"999999");q.choiceInputs=new Rational[]{Rational.of(999999)};q.givenNumbers.replaceAll((k,x)->"999999");HelpPlan p=HelpPlan.forQuestion(q);assertEquals(expected.size(),p.size());assertFalse(p.canTransfer());assertEquals(id,q.id);assertEquals(sig,q.signature());assertEquals(prompt,q.prompt);assertSame(diagram,q.diagram);for(int i=0;i<p.size();i++){assertTrue(p.step(i).accepts(expected.get(i).toString()));assertFalse(p.step(i).accepts(expected.get(i).add(Rational.ONE).toString()));assertEquals("",p.step(i).after);assertFalse("No calculated numerical frame "+p.step(i).before,Pattern.compile("\\d").matcher(p.step(i).before).find());}}
 @Test public void publicCoordinatesAndSignedLineDecideGeneratedSteps(){Generator g=new Generator(new Random(2201));for(String skill:List.of("sec_point_distance","sec_internal_division","sec_line_equation")){Set<String> prompts=new HashSet<>();Set<Integer> choices=new HashSet<>();boolean negative=false,positive=false;for(int i=0;i<1000;i++){Question q=g.next(skill,List.of(),i%2==0);List<Rational> v=values(q);List<String> result=skill.equals("sec_internal_division")?List.of(v.get(6).toString(),v.get(10).toString()):List.of(v.get(v.size()-1).toString());assertTrue(skill,new Checker().check(q,List.of(),result).correct());List<String> wrong=new ArrayList<>(result);wrong.set(0,Expression.number(result.get(0)).add(Rational.ONE).toString());assertFalse(new Checker().check(q,List.of(),wrong).correct());prompts.add(q.prompt);if(q.correctChoice>=0)choices.add(q.correctChoice);negative|=v.stream().anyMatch(x->x.compareTo(Rational.ZERO)<0);positive|=v.stream().anyMatch(x->x.compareTo(Rational.ZERO)>0);verify(q,v);}assertTrue(skill+prompts.size(),prompts.size()>100);if(!skill.equals("sec_internal_division"))assertEquals(Set.of(0,1,2,3),choices);assertTrue(negative&&positive);}}
 @Test public void savedFractionsZeroDisplacementsAndDraftVersions(){for(Question q:List.of(new Question("sec_point_distance","두 점 (-1/2, 2), (1, 4) 사이의 거리는?","","5/2"),new Question("sec_point_distance","두 점 (0, 0), (0, 0) 사이의 거리는?","","0"),new Question("sec_internal_division","A(-1/2, 2)와 B(3/2, 2)를 AP:PB=1:2로 내분하는 P의 좌표는?","","1/6","2"),new Question("sec_line_equation","직선 y=-1/2x+3/2 위에서 x=3일 때 y는?","","0"))){List<Rational> v=values(q);verify(q,v);HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of(v.get(0).toString()));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));assertTrue(d.teachingVersion.endsWith("relations-v1"));d.entries.set(0,v.get(0).toString());d.stage=1;assertEquals(1,HelpPlan.forQuestion(q).restore(d.copy(),q.id).stage);}}
}
