package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class CoordinateAltitudeAreaTest {
 private int[][] points(Question q){Matcher m=Pattern.compile("[ABCD]\\((-?\\d+), (-?\\d+)\\)").matcher(q.prompt);int[][] p=new int[4][2];for(int i=0;i<4;i++){assertTrue(m.find());for(int k=0;k<2;k++)p[i][k]=Integer.parseInt(m.group(k+1));}assertFalse(m.find());return p;}
 private int distance(int[] a,int[] b){assertTrue(a[0]==b[0]||a[1]==b[1]);int n=0;for(int k=0;k<2;k++)for(int x=a[k];x!=b[k];x+=Integer.signum(b[k]-a[k]))n++;return n;}
 private int twiceArea(int[][] p){int n=0;for(int k=0;k<3;k++)n+=p[k][0]*p[(k+1)%3][1]-p[(k+1)%3][0]*p[k][1];return Math.abs(n);}
 @Test public void hundredUniqueIndependentAreasChoicesAndSevenTeachingEntries(){Generator g=new Generator(new Random(951));Set<String> seen=new HashSet<>();Set<Integer> positions=new HashSet<>();for(int i=0;i<100;i++){Question q=g.next(CoordinateAltitudeArea.ID,seen,true);assertTrue(seen.add(q.signature()));int[][] p=points(q);int a=distance(p[0],p[3]),b=distance(p[3],p[1]),h=distance(p[2],p[3]),twice=twiceArea(p);String answer=twice+"/2";assertTrue(new Checker().check(q,List.of(),List.of(answer)).correct());assertFalse(new Checker().check(q,List.of(),List.of((twice+1)+"/2")).correct());assertEquals(4,new HashSet<>(q.choices).size());assertEquals(Expression.number(answer),Expression.number(q.choices.get(q.correctChoice)));positions.add(q.correctChoice);for(String choice:q.choices)assertTrue(Radical.parse(answer).sameShape(Radical.parse(choice)));int[] entries={a,b,h,a*h,b*h,a*h+b*h,2};HelpPlan plan=HelpPlan.forQuestion(q);assertEquals(7,plan.size());assertFalse(plan.canTransfer());HelpPlan.Draft d=plan.restore(null,q.id);for(int k=0;k<7;k++){assertTrue(plan.step(k).accepts(""+entries[k]));assertFalse(plan.step(k).accepts(""+(entries[k]+1)));d.entries.set(k,""+entries[k]);d.stage++;d.entries.add("");}Arrays.fill(q.answers,"999");assertEquals(Expression.number(answer),Expression.number(plan.enteredAnswer(d)));d.entries.set(5,"999");try{plan.enteredAnswer(d);fail("Unchecked rectangle sum");}catch(IllegalStateException expected){}}assertEquals(Set.of(0,1,2,3),positions);}
 @Test public void sixThousandPublicAltitudesAreInteriorPerpendicularAndNonRight(){Random r=new Random(952);Set<String> orientations=new HashSet<>();boolean half=false,whole=false,acute=false,obtuse=false;for(int i=0;i<6000;i++){Question q=CoordinateAltitudeArea.create(Catalog.get(CoordinateAltitudeArea.ID),r);int[][] p=points(q);int a=distance(p[0],p[3]),b=distance(p[3],p[1]),h=distance(p[2],p[3]);assertTrue(a>0&&b>0&&h>0);assertEquals(a+b,distance(p[0],p[1]));int ux=p[1][0]-p[0][0],uy=p[1][1]-p[0][1],vx=p[2][0]-p[3][0],vy=p[2][1]-p[3][1];assertEquals(0,ux*vx+uy*vy);orientations.add(Integer.signum(ux)+","+Integer.signum(uy)+","+Integer.signum(vx)+","+Integer.signum(vy));int corner=(p[0][0]-p[2][0])*(p[1][0]-p[2][0])+(p[0][1]-p[2][1])*(p[1][1]-p[2][1]);assertNotEquals(0,corner);acute|=corner>0;obtuse|=corner<0;for(int k=0;k<4;k++)for(int j=0;j<2;j++){assertTrue(p[k][j]>=-8&&p[k][j]<=8);assertEquals(p[k][j],q.diagram.values[2*k+j],0);}int n=twiceArea(p);assertEquals((a+b)*h,n);assertEquals(Rational.of(n).div(Rational.of(2)),Expression.number(q.answers[0]));half|=n%2==1;whole|=n%2==0;double[] geometry=q.diagram.values.clone();Arrays.fill(q.answers,"999");assertArrayEquals(geometry,q.diagram.values,0);}assertEquals(8,orientations.size());assertTrue(half&&whole&&acute&&obtuse);}
 @Test public void blankFractionInputAvailable(){Question q=CoordinateAltitudeArea.create(Catalog.get(CoordinateAltitudeArea.ID),new Random(953));assertTrue(FractionInput.defaultFraction(q));assertArrayEquals(new String[]{"",""},FractionInput.parts(""));}
}
