package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class CoordinateObliqueAreaTest {
 private int[][] points(Question q){Matcher m=Pattern.compile("[ABC]\\((-?\\d+), (-?\\d+)\\)").matcher(q.prompt);int[][] p=new int[3][2];for(int i=0;i<3;i++){assertTrue(m.find());for(int k=0;k<2;k++)p[i][k]=Integer.parseInt(m.group(k+1));}assertFalse(m.find());return p;}
 private int area2(int[][] p){int n=0;for(int i=0;i<3;i++)n+=p[i][0]*p[(i+1)%3][1]-p[(i+1)%3][0]*p[i][1];return Math.abs(n);}
 private int[] entries(int[][] p){int base=Math.min(p[0][1],Math.min(p[1][1],p[2][1])),u=p[1][0]-p[0][0],v=p[2][0]-p[1][0],w=u+v,a=p[0][1]-base,b=p[1][1]-base,c=p[2][1]-base,ab=u*(a+b),bc=v*(b+c),ac=w*(a+c);return new int[]{u,v,w,a,b,c,a+b,ab,b+c,bc,a+c,ac,ab+bc,Math.abs(ab+bc-ac),2};}
 @Test public void hundredUniqueAreasChoicesAndCheckedTeaching(){Generator g=new Generator(new Random(1051));Set<String> seen=new HashSet<>();Set<Integer> positions=new HashSet<>();for(int i=0;i<100;i++){Question q=g.next(CoordinateObliqueArea.ID,seen,true);assertTrue(seen.add(q.signature()));int[][] p=points(q);String answer=area2(p)+"/2";assertTrue(new Checker().check(q,List.of(),List.of(answer)).correct());assertFalse(new Checker().check(q,List.of(),List.of((area2(p)+1)+"/2")).correct());assertEquals(4,new HashSet<>(q.choices).size());assertEquals(Expression.number(answer),Expression.number(q.choices.get(q.correctChoice)));positions.add(q.correctChoice);for(String option:q.choices)assertTrue(Radical.parse(answer).sameShape(Radical.parse(option)));int[] expected=entries(p);assertEquals(area2(p),expected[13]);HelpPlan plan=HelpPlan.forQuestion(q);assertEquals(15,plan.size());assertFalse(plan.canTransfer());HelpPlan.Draft d=plan.restore(null,q.id);for(int k=0;k<15;k++){assertTrue(plan.step(k).accepts(""+expected[k]));assertFalse(plan.step(k).accepts(""+(expected[k]+1)));d.entries.set(k,""+expected[k]);d.stage++;d.entries.add("");}Arrays.fill(q.answers,"999");assertEquals(Expression.number(answer),Expression.number(plan.enteredAnswer(d)));d.entries.set(13,"999");try{plan.enteredAnswer(d);fail("Unchecked difference");}catch(IllegalStateException expectedError){}}assertEquals(Set.of(0,1,2,3),positions);}
 @Test public void sixThousandPublicTrianglesCoverAllVerticalOrdersAndBothDifferences(){Random r=new Random(1052);Set<String> orders=new HashSet<>();Set<Integer> zeroHeight=new HashSet<>();boolean addPathLarger=false,singlePathLarger=false,half=false,whole=false;for(int i=0;i<6000;i++){Question q=CoordinateObliqueArea.create(Catalog.get(CoordinateObliqueArea.ID),r);int[][] p=points(q);assertTrue(p[0][0]<p[1][0]&&p[1][0]<p[2][0]);Integer[] ranks={0,1,2};Arrays.sort(ranks,Comparator.comparingInt(k->p[k][1]));orders.add(Arrays.toString(ranks));for(int k=0;k<3;k++){int j=(k+1)%3;assertNotEquals(p[k][1],p[j][1]);for(int axis=0;axis<2;axis++){assertTrue(p[k][axis]>=-8&&p[k][axis]<=8);assertEquals(p[k][axis],q.diagram.values[2*k+axis],0);}}int[] e=entries(p);for(int k=0;k<3;k++)if(e[3+k]==0)zeroHeight.add(k);addPathLarger|=e[12]>e[11];singlePathLarger|=e[11]>e[12];int n=area2(p);assertTrue(n>=8);assertEquals(n,e[13]);assertEquals(Rational.of(n).div(Rational.of(2)),Expression.number(q.answers[0]));half|=n%2==1;whole|=n%2==0;double[] geometry=q.diagram.values.clone();Arrays.fill(q.answers,"999");assertArrayEquals(geometry,q.diagram.values,0);}assertEquals(6,orders.size());assertEquals(Set.of(0,1,2),zeroHeight);assertTrue(addPathLarger&&singlePathLarger&&half&&whole);}
 @Test public void blankFractionInput(){Question q=CoordinateObliqueArea.create(Catalog.get(CoordinateObliqueArea.ID),new Random(1053));assertTrue(FractionInput.defaultFraction(q));assertArrayEquals(new String[]{"",""},FractionInput.parts(""));}
}
