package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import java.io.*;import org.junit.Test;import static org.junit.Assert.*;
public class CoordinateDiagonalTest {
 private int[] points(String prompt){Matcher m=Pattern.compile("[AB]\\((-?\\d+), (-?\\d+)\\)").matcher(prompt);int[] out=new int[4];for(int i=0;i<2;i++){assertTrue(m.find());out[2*i]=Integer.parseInt(m.group(1));out[2*i+1]=Integer.parseInt(m.group(2));}return out;}
 private int[] exact(int n){int coefficient=1,inside=1;for(int prime=2;prime<=n;prime++){int count=0;while(n%prime==0){n/=prime;count++;}for(int k=0;k<count/2;k++)coefficient*=prime;if(count%2==1)inside*=prime;}return new int[]{coefficient,inside};}
 private String format(int c,int inside){return inside==1?""+c:(c==1?"":c+"*")+"sqrt("+inside+")";}
 @Test public void hundredIndependentDistancesAndTeachingFrames(){Generator generator=new Generator(new Random(123));Set<String> seen=new HashSet<>();Set<Integer> positions=new HashSet<>();boolean integer=false,irrational=false;for(int i=0;i<100;i++){Question q=generator.next(CoordinateDiagonal.ID,seen,true);assertTrue(seen.add(q.signature()));int[] p=points(q.prompt);int dx=Math.abs(p[2]-p[0]),dy=Math.abs(p[3]-p[1]),n=dx*dx+dy*dy;int[] pair=exact(n);String answer=format(pair[0],pair[1]);assertEquals(Radical.parse(answer),Radical.parse(q.answers[0]));integer|=pair[1]==1;irrational|=pair[1]>1;assertTrue(new Checker().check(q,List.of(),List.of(answer)).correct());assertFalse(new Checker().check(q,List.of(),List.of(""+(dx+dy))).correct());Set<Radical> choices=new HashSet<>();for(String choice:q.choices)assertTrue(choices.add(Radical.parse(choice)));assertEquals(4,choices.size());assertEquals(Radical.parse(answer),Radical.parse(q.choices.get(q.correctChoice)));positions.add(q.correctChoice);
 HelpPlan help=HelpPlan.forQuestion(q);assertEquals(8,help.size());assertFalse(help.canTransfer());int[] frames={dx,dy,dx*dx,dy*dy,n,pair[0]*pair[0],pair[1],pair[0]};HelpPlan.Draft draft=help.restore(null,q.id);for(int stage=0;stage<8;stage++){assertTrue(help.step(stage).accepts(""+frames[stage]));assertFalse(help.step(stage).accepts(""+(frames[stage]+1)));draft.entries.set(stage,""+frames[stage]);draft.stage++;draft.entries.add("");}Arrays.fill(q.answers,"999");assertEquals(Radical.parse(answer),Radical.parse(help.enteredAnswer(draft)));draft.entries.set(6,"999");try{help.enteredAnswer(draft);fail("Must not assemble an unchecked radicand");}catch(IllegalStateException expected){} }
 assertTrue(integer);assertTrue(irrational);assertEquals(Set.of(0,1,2,3),positions);}
 @Test public void sixThousandObliqueEndpointsRemainWithinGrid(){Random r=new Random(124);Set<String> directions=new HashSet<>();for(int i=0;i<6000;i++){Question q=CoordinateDiagonal.create(Catalog.get(CoordinateDiagonal.ID),r);int[] p=points(q.prompt);for(int n:p)assertTrue(n>=-8&&n<=8);int dx=p[2]-p[0],dy=p[3]-p[1];assertNotEquals(0,dx);assertNotEquals(0,dy);directions.add(Integer.signum(dx)+","+Integer.signum(dy));int n=dx*dx+dy*dy;assertEquals(Radical.parse(""+n),Radical.parse(q.answers[0]).mul(Radical.parse(q.answers[0])));assertEquals(0,q.diagram.values[6],0);}assertEquals(4,directions.size());}
 @Test public void serializedNumericFramesRestoreAssembledRoot()throws Exception{Question q=CoordinateDiagonal.create(Catalog.get(CoordinateDiagonal.ID),new Random(125));ByteArrayOutputStream bytes=new ByteArrayOutputStream();new ObjectOutputStream(bytes).writeObject(q);Question restored=(Question)new ObjectInputStream(new ByteArrayInputStream(bytes.toByteArray())).readObject();assertEquals(Integer.valueOf(7),restored.studyGuide.resultCoefficientFrame);assertEquals(Integer.valueOf(6),restored.studyGuide.resultRadicandFrame);assertNull(new StudyGuide().resultCoefficientFrame);HelpPlan help=HelpPlan.forQuestion(restored);HelpPlan.Draft draft=help.restore(null,restored.id);assertEquals(0,draft.stage);assertEquals("",draft.entries.get(0));assertFalse(help.canTransfer());}
}
