package com.gomgomapps.math.core;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.*;
import java.time.LocalDate;
import java.util.*;

public class CoreTest {
    @Test public void exactFractionsAndDecimals(){assertEquals(Rational.of(3,10),Expression.number("0.1+0.2"));assertEquals(Rational.of(-4),Expression.number("-2^2"));assertEquals(Rational.of(1,8),Expression.number("2^(-3)"));assertEquals(Rational.of(3),Expression.number("√(9)"));}
    @Test public void equivalentPolynomialsAndEquations(){assertTrue(Expression.equivalent("(x+2)(x-3)","x^2-x-6"));assertTrue(Expression.equivalent("2x+4=10","x=3"));assertFalse(Expression.equivalent("x^2=4","x=2"));assertThrows(IllegalArgumentException.class,()->Expression.equivalent("x/x","1"));}
    @Test public void processChecksFirstWrongAndNeverRepairsAnswer(){Question q=new Question("mixed","2+3*4","2+3*4","14");Checker.Result r=new Checker().check(q,List.of("5*4","14"),List.of("14"),List.of(Checker.StepKind.FULL,Checker.StepKind.FULL));assertEquals(Checker.Status.WRONG_STEP,r.status);assertEquals(0,r.index);assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(q,List.of("?"),List.of("14")).status);assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(q,List.of(),List.of("2+3*4")).status);assertTrue(new Checker().check(q,List.of("2+12"),List.of("14")).correct());}
    @Test public void generatedQuestionsHaveUniqueCorrectChoicesAndSolve(){Generator g=new Generator(new Random(77213));Checker checker=new Checker();for(Catalog.Skill skill:Catalog.ALL)for(int i=0;i<120;i++){Question q=g.next(skill.id,List.of(),true);assertTrue(skill.id+": "+q.prompt+" -> "+Arrays.toString(q.answers),checker.check(q,List.of(),Arrays.asList(q.answers)).correct());if(!q.expression.isEmpty()&&!q.expression.contains("=")&&q.kind.equals("number"))assertEquals(skill.id,Expression.number(q.answers[0]),Expression.number(q.expression));if(!q.choices.isEmpty()){assertEquals(q.choiceLabels==null||q.choiceLabels.isEmpty()?4:q.choiceLabels.size(),new HashSet<>(q.choices).size());Object expected=q.kind.equals("radical")?Radical.parse(q.answers[0]):Expression.number(q.answers[0]);assertEquals(expected,q.kind.equals("radical")?Radical.parse(q.choices.get(q.correctChoice)):Expression.number(q.choices.get(q.correctChoice)));int count=0;for(String choice:q.choices)if(expected.equals(q.kind.equals("radical")?Radical.parse(choice):Expression.number(choice)))count++;assertEquals(1,count);}}}
    @Test public void optionsAreNeitherRotatingNorForcedToAlternate(){Generator g=new Generator(new Random(444));int[] buckets=new int[4];int previous=-1,repeats=0;Set<String> results=new HashSet<>();for(int i=0;i<2000;i++){Question q=g.next("add100",List.of(),true);buckets[q.correctChoice]++;if(previous==q.correctChoice)repeats++;previous=q.correctChoice;results.add(q.answers[0]);}for(int count:buckets)assertTrue(count>350&&count<650);assertTrue(repeats>350);assertTrue(results.size()>100);}
    @Test public void diagnosticExcludesCurrentAndFutureContent(){Learning.Profile p=new Learning.Profile();p.grade=4;p.term=2;assertTrue(Learning.diagnosticScope(p).stream().allMatch(s->s.order()<420));p.currentSkill="decimalAdd";assertFalse(Learning.diagnosticScope(p).stream().anyMatch(s->s.id.equals("decimalAdd")||s.id.equals("decimalSub")));p.excluded.add("fracAddLike");assertFalse(Learning.diagnosticScope(p).stream().anyMatch(s->s.id.equals("fracAddLike")));p.grade=1;p.term=1;p.currentSkill="";assertTrue(Learning.diagnosticScope(p).stream().allMatch(s->s.grade==0));}
    @Test public void highSchoolUsesLearnedCoursesRatherThanAssumedGrade(){Learning.Profile p=new Learning.Profile();p.grade=12;p.learnedCourses.add("공통수학 1");p.currentSkill="log";Set<String> ids=new HashSet<>();for(Catalog.Skill s:Learning.diagnosticScope(p))ids.add(s.id);assertTrue(ids.contains("combination"));assertFalse(ids.contains("derivative"));assertFalse(ids.contains("log"));}
    @Test public void repeatedMathematicalErrorsCheckLowerFoundationsAndKeepActualGrade(){Learning.State state=new Learning.State();state.profile.grade=5;state.profile.term=2;state.profile.ready=true;Random random=new Random(4);Learning.beginDiagnostic(state,random);Generator generator=new Generator(random);Learning.ensureQuestion(state,generator);int start=state.session.stageGrade;for(int i=0;i<4;i++){Learning.ensureQuestion(state,generator);Learning.markError(state);Learning.finishQuestion(state,false,LocalDate.of(2026,9,7),random);}Learning.ensureQuestion(state,generator);assertEquals(start-1,state.session.stageGrade);assertEquals(5,state.profile.grade);assertFalse(state.session.finished);assertFalse(state.needsPractice.isEmpty());}
    @Test public void recordingIsIdempotentAndSessionRestoresQuestionOptionsAndInk()throws Exception{
        Learning.State state=new Learning.State();Random r=new Random(9);Learning.beginPractice(state,"homework",List.of("decimalMul"),20,true,r);Question q=Learning.ensureQuestion(state,new Generator(r));state.session.answers.set(0,"1.2");state.session.scratch.add(new float[]{1,2,3,4});ByteArrayOutputStream bytes=new ByteArrayOutputStream();new ObjectOutputStream(bytes).writeObject(state);Learning.State loaded=(Learning.State)new ObjectInputStream(new ByteArrayInputStream(bytes.toByteArray())).readObject();assertEquals(q.id,Learning.ensureQuestion(loaded,new Generator()).id);assertEquals(q.choices,loaded.session.question.choices);assertEquals("1.2",loaded.session.answers.get(0));assertEquals(1,loaded.session.scratch.size());Learning.finishQuestion(loaded,false,LocalDate.now(),r);Learning.finishQuestion(loaded,false,LocalDate.now(),r);assertEquals(1,loaded.session.completed);assertEquals(1,loaded.progress("decimalMul").attempts);
    }
}
