package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class CuboidSurfaceRelationsTest {
 @Test public void publicEdgesDetermineNetAndAllThreeSurfacePaths(){Generator g=new Generator(new Random(1870));for(String id:List.of("cuboidNetArea","cuboidSurfacePath"))for(int i=0;i<600;i++){Question q=g.next(id,List.of(),i%2==0);Matcher m=Pattern.compile("a=(.*?), b=(.*?), c=(.*?)cm").matcher(q.prompt);assertTrue(m.find());Rational a=Expression.number(m.group(1)),b=Expression.number(m.group(2)),c=Expression.number(m.group(3));List<Rational> expected=expected(id,a,b,c);assertTrue(new Checker().check(q,List.of(),List.of(expected.get(expected.size()-1).toString())).correct());if(id.equals("cuboidSurfacePath")){assertTrue(q.prompt.contains("마주 보는 꼭짓점")&&q.prompt.contains("표면"));assertTrue(expected.get(6).compareTo(a.pow(2).add(b.pow(2)).add(c.pow(2)))>0);assertTrue(q.expression.isEmpty());assertFalse(q.stepSupport);}verify(q,expected);}}
 @Test public void savedFractionalEdgesRemainExact(){for(String id:List.of("cuboidNetArea","cuboidSurfacePath")){Rational a=Rational.ONE,b=Rational.ONE,c=Rational.of(3,2);Question q=question(id,"1","1","3/2");verify(q,expected(id,a,b,c));}}
 @Test public void tiedShortestPathsStillUseTheirSharedMinimum(){Question q=question("cuboidSurfacePath","1","3","3");List<Rational> values=expected(q.skillId,Rational.ONE,Rational.of(3),Rational.of(3));assertEquals(values.get(3),values.get(4));assertEquals(Rational.of(25),values.get(6));assertEquals(Rational.of(5),values.get(7));verify(q,values);}
 @Test public void oldCalculatedDraftsCannotBecomeNewEdgeValues(){for(String id:List.of("cuboidNetArea","cuboidSurfacePath")){Question q=question(id,"1","1","3/2");HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of("6",""));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));d.entries.set(0,"1");d.stage=1;HelpPlan.Draft restored=HelpPlan.forQuestion(q).restore(d.copy(),q.id);assertEquals(1,restored.stage);assertEquals("1",restored.entries.get(0));}}
 private Question question(String id,String a,String b,String c){return new Question(id,"직육면체: a="+a+", b="+b+", c="+c+"cm\n"+(id.equals("cuboidNetArea")?"전개도의 전체 넓이는 몇 cm²인가요?":"A와 B는 마주 보는 꼭짓점입니다.\n표면을 따라가는 최단거리는 몇 cm인가요?"),"","999999");}
 private List<Rational> expected(String id,Rational a,Rational b,Rational c){List<Rational> values=new ArrayList<>(List.of(a,b,c));if(id.equals("cuboidNetArea")){Rational ab=a.mul(b),ac=a.mul(c),bc=b.mul(c);values.addAll(List.of(ab,ac,bc,ab.add(ac).add(bc).mul(Rational.of(2))));}else{Rational first=a.add(b).pow(2).add(c.pow(2)),second=a.add(c).pow(2).add(b.pow(2)),third=b.add(c).pow(2).add(a.pow(2)),minimum=Collections.min(List.of(first,second,third));values.addAll(List.of(first,second,third,minimum,minimum.sqrt()));}return values;}
 private void verify(Question q,List<Rational> expected){String signature=q.signature();Arrays.fill(q.answers,"999999");q.choiceInputs=new Rational[]{Rational.of(999999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(signature,q.signature());assertEquals(expected.size(),p.size());assertFalse(p.canTransfer());for(int k=0;k<p.size();k++){assertTrue(p.step(k).accepts(expected.get(k).toString()));assertFalse(p.step(k).accepts(expected.get(k).add(Rational.ONE).toString()));assertFalse(p.step(k).before.replace("2","").replace("²","").matches("(?s).*\\d.*"));}}
}
