package com.gomgomapps.math.core;
import java.math.*;import java.util.*;import java.util.regex.*;import java.io.*;import org.junit.Test;import static org.junit.Assert.*;
public class DecimalArithmeticRelationsTest {
 private static String t(BigDecimal n){return n.stripTrailingZeros().toPlainString();}
 private void check(Question q){String signature=q.signature();Matcher m=Pattern.compile("(\\d+(?:\\.\\d+)?) ([+*/-]) (\\d+(?:\\.\\d+)?)").matcher(q.prompt);assertTrue(m.matches());BigDecimal x=new BigDecimal(m.group(1)),y=new BigDecimal(m.group(3));String op=m.group(2);BigDecimal result=switch(op){case "+"->x.add(y);case "-"->x.subtract(y);case "*"->x.multiply(y);default->x.divide(y);};List<String> values=new ArrayList<>(List.of(t(x),t(y)));int px=x.scale(),py=y.scale();
  if(op.equals("*")){BigDecimal a=x.movePointRight(px),b=y.movePointRight(py);if(py==0)values.addAll(List.of(""+px,t(a),t(a.multiply(y)),t(result)));else values.addAll(List.of(""+px,""+py,t(a),t(b),t(a.multiply(b)),""+(px+py),t(result)));}
  else{boolean divide=op.equals("/"),whole=q.skillId.equals("decimalDivInt");int places=divide?(whole?px:py):Math.max(px,py);BigDecimal unit=BigDecimal.TEN.pow(places),a=x.multiply(unit),b=y.multiply(unit);values.addAll(List.of(""+places,t(unit),t(a)));if(whole)values.addAll(List.of(t(a.divide(y)),t(result)));else{values.add(t(b));if(!divide)values.add(t(op.equals("+")?a.add(b):a.subtract(b)));values.add(t(result));}}
  HelpPlan p=HelpPlan.forQuestion(q);assertNotNull(p);assertFalse(p.canTransfer());assertEquals(signature,q.signature());assertEquals(values.size(),p.size());for(int i=0;i<p.size();i++){assertTrue(values.get(i),p.step(i).accepts(values.get(i)));assertFalse(p.step(i).accepts(""));assertFalse(p.step(i).accepts(t(new BigDecimal(values.get(i)).add(BigDecimal.ONE))));assertEquals("",p.step(i).after);assertFalse(p.step(i).before.matches(".*[0-9].*"));if("decimalValue".equals(q.studyGuide.frames.get(i).inputFormat))assertFalse(p.step(i).accepts(Expression.number(values.get(i)).toString().contains("/")?Expression.number(values.get(i)).toString():values.get(i)+"/1"));}
  HelpPlan.Draft d=new HelpPlan.Draft();d.stage=p.size();d.entries=values;assertEquals(0,result.compareTo(new BigDecimal(p.enteredAnswer(d))));assertEquals(0,result.compareTo(new BigDecimal(Expression.number(q.answers[0]).decimalText())));List<String> old=q.studyGuide.frames.stream().map(f->f.expected).toList();q.expression="999";q.answers=new String[]{"999"};q.givenNumbers.put("answer","999");HelpPlan.forQuestion(q);assertEquals(old,q.studyGuide.frames.stream().map(f->f.expected).toList());
 }
 @Test public void fiveUnitsHaveMoreThan100DistinctPromptsAndExactEnteredWork(){Generator g=new Generator(new Random(710410));for(String id:List.of("decimalAdd","decimalSub","decimalMul","decimalDiv","decimalDivInt")){Set<String> seen=new HashSet<>();for(int i=0;i<4000;i++){Question q=g.next(id,List.of(),i%2==0);seen.add(q.prompt);check(q);}assertTrue(id+" "+seen.size(),seen.size()>100);}}
 @Test public void integerMultiplierCurriculaKeepTheirOperandLimits(){for(String pack:List.of("jp-mext-primary-2017-v1","br-bncc-fundamental-2017-v1")){Catalog.Skill skill=Catalog.get("decimalMul");Generator g=new Generator(new Random(710411));for(int i=0;i<200;i++){Question q=g.next(skill.id,List.of(),i%2==0,GlobalCurriculum.limits(pack,"decimalMul",pack.startsWith("jp")?4:5));assertTrue(q.prompt.split(" \\* ")[1].matches("\\d+"));check(q);assertEquals(6,q.studyGuide.frames.size());}}}
 @Test public void serializedWorkKeepsFormatsAndNewDraftsRestore()throws Exception{Question q=new Generator(new Random(710412)).next("decimalMul",List.of(),false);ByteArrayOutputStream out=new ByteArrayOutputStream();new ObjectOutputStream(out).writeObject(q);Question saved=(Question)new ObjectInputStream(new ByteArrayInputStream(out.toByteArray())).readObject();check(saved);HelpPlan p=HelpPlan.forQuestion(saved);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of("old"));d=p.restore(d,q.id);assertEquals(0,d.stage);d.entries.set(0,saved.studyGuide.frames.get(0).expected);d.stage=1;assertEquals(1,p.restore(d,q.id).stage);}
}
