package com.gomgomapps.math.core;
import java.math.*;import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class DecimalMeasureStoriesTest {
 @Test public void boundaryStoriesKeepUnitsAndExactSamePlaceCalculations(){
  for(String unit:List.of("m","L"))for(String id:List.of(DecimalMeasureStories.ADD,DecimalMeasureStories.SUB))for(String[] pair:new String[][]{{"0.000","0.00"},{"1.005","0.09"},{"10.000","9.999"},{"99.999","99.999"}}){Question q=DecimalMeasureStories.make(id,pair[0],pair[1],unit);var v=DecimalMeasureStories.read(q);assertNotNull(v);assertEquals(unit,v.unit());BigDecimal x=new BigDecimal(pair[0]),y=new BigDecimal(pair[1]),r=id.equals(DecimalMeasureStories.ADD)?x.add(y):x.subtract(y);assertTrue(new Checker().check(q,List.of(),List.of(r.toPlainString())).correct());assertFalse(new Checker().check(q,List.of(),List.of(r.add(new BigDecimal("0.001")).toPlainString())).correct());assertEquals("",q.expression);assertFalse(q.stepSupport);}
 }
 @Test public void poisonedAnswerCannotSupplyTheRelationOrArithmeticHelp(){
  for(String id:List.of(DecimalMeasureStories.ADD,DecimalMeasureStories.SUB))for(String unit:List.of("m","L")){Question original=DecimalMeasureStories.make(id,"1.005","0.09",unit),q=new Question(id,original.prompt,"poison","999");HelpPlan h=HelpPlan.forQuestion(q);assertEquals(9,h.size());assertFalse(h.canTransfer());boolean add=id.equals(DecimalMeasureStories.ADD);List<String> inputs=List.of(add?"add":"sub","1.005","0.09","3","1000","1005","90",add?"1095":"915",add?"1.095":"0.915");for(int i=0;i<inputs.size();i++)assertTrue(h.step(i).accepts(inputs.get(i)));assertFalse(h.step(0).accepts(add?"sub":"add"));}
 }
 @Test public void gradeFiveSuppliesIncludeThirdPlacesBothContextsAndFreshHundred(){
  var pack=GlobalCurriculum.packs("GB").stream().filter(p->p.id.equals("england-primary-2021-v1")).findFirst().orElseThrow();Generator g=new Generator(new Random(86));for(String id:List.of(DecimalMeasureStories.ADD,DecimalMeasureStories.SUB,"decimalAdd","decimalSub")){assertTrue(pack.inGrade(id,5));var limits=GlobalCurriculum.limits(pack.id,id,5);assertEquals(3,limits.decimalPlaces(1));List<String> recent=new ArrayList<>();boolean third=false;Set<String> units=new HashSet<>();for(int i=0;i<150;i++){Question q=g.next(id,recent,false,limits);assertFalse(recent.contains(q.signature()));recent.add(q.signature());String a,b;boolean add=id.equals(DecimalMeasureStories.ADD)||id.equals("decimalAdd");if(DecimalMeasureStories.supports(id)){var v=DecimalMeasureStories.read(q);assertNotNull(v);a=v.first();b=v.second();units.add(v.unit());}else{String[] bits=q.prompt.split(" [+-] ");a=bits[0];b=bits[1];}BigDecimal x=new BigDecimal(a),y=new BigDecimal(b);third|=x.scale()==3||y.scale()==3;assertTrue(new Checker().check(q,List.of(),List.of((add?x.add(y):x.subtract(y)).toPlainString())).correct());}assertTrue(third);if(DecimalMeasureStories.supports(id)){assertEquals(Set.of("m","L"),units);assertFalse(pack.inGrade(id,4));assertFalse(Curriculum.inCurriculum(Catalog.get(id),2022));}}
 }
}
