package com.gomgomapps.math.core;
import java.util.*;import java.math.BigDecimal;import org.junit.Test;import static org.junit.Assert.*;
public class EnglishDecimalWordsTest {
 @Test public void wholePartsAndInnerZerosAreReadAsFullNumbers(){
  Map<Integer,String> known=new LinkedHashMap<>();known.put(101,"one hundred and one");known.put(110,"one hundred and ten");known.put(999,"nine hundred and ninety-nine");known.put(1001,"one thousand and one");known.put(1010,"one thousand and ten");known.put(1100,"one thousand one hundred");known.put(123456,"one hundred and twenty-three thousand four hundred and fifty-six");known.put(1000000,"one million");
  String[] digit={"zero","one","two","three","four","five","six","seven","eight","nine"};for(var e:known.entrySet())assertEquals(e.getValue(),EnglishDecimalWords.wholeWords(e.getKey()));for(int whole:List.of(0,41,1000000))for(int n=0;n<1000;n++){String raw=whole+"."+String.format(Locale.ROOT,"%03d",n),word=(whole==0?"zero":whole==41?"forty-one":"one million")+" point "+digit[n/100]+" "+digit[n/10%10]+" "+digit[n%10];assertEquals(word,EnglishDecimalWords.words(raw));assertEquals(raw,EnglishDecimalWords.numeral(word));}
  assertEquals("0.007",EnglishDecimalWords.numeral("nought point oh oh seven"));assertTrue(EnglishDecimalWords.matches("Nought point zero seven zero","zero point zero seven zero"));assertFalse(EnglishDecimalWords.matches("zero point seven","zero point zero seven"));assertFalse(EnglishDecimalWords.matches("zero point zero seven","zero point zero seven zero"));
  for(String invalid:List.of("one two point three","one point ten","one point one two three four","one point","point two","one million one point two")){try{EnglishDecimalWords.numeral(invalid);fail(invalid);}catch(IllegalArgumentException expected){}}
 }
 @Test public void bothOrdinaryGeneratorsUseFreshProblemsAndRealAnswersWithoutChoices(){
  var pack=GlobalCurriculum.packs("GB").stream().filter(p->p.id.equals("england-primary-2021-v1")).findFirst().orElseThrow();Generator g=new Generator(new Random(85));for(String id:List.of(EnglishDecimalWords.READ,EnglishDecimalWords.WRITE)){assertTrue(pack.inGrade(id,5));assertFalse(pack.inGrade(id,4));assertFalse(Curriculum.inCurriculum(Catalog.get(id),2022));List<String> recent=new ArrayList<>();for(int i=0;i<100;i++){Question q=g.next(id,recent,true,GlobalCurriculum.limits(pack.id,id,5));assertFalse(recent.contains(q.signature()));recent.add(q.signature());assertTrue(q.choices.isEmpty());String given=q.prompt.split("\n")[1];String answer=id.equals(EnglishDecimalWords.WRITE)?EnglishDecimalWords.words(given):EnglishDecimalWords.numeral(given);assertTrue(new Checker().check(q,List.of(),List.of(answer)).correct());if(id.equals(EnglishDecimalWords.READ))assertFalse(new Checker().check(q,List.of(),List.of(new BigDecimal(answer).add(BigDecimal.ONE).toPlainString())).correct());}}
 }
 @Test public void visibleWholeAndEachFractionDigitRestoreWithoutHiddenAnswer(){
  for(String id:List.of(EnglishDecimalWords.READ,EnglishDecimalWords.WRITE)){Question original=EnglishDecimalWords.make(id,"1001.007");Question q=new Question(id,original.prompt,"poison","999");HelpPlan h=HelpPlan.forQuestion(q);assertEquals(5,h.size());assertFalse(h.canTransfer());List<String> entries=List.of("1001","3","0","0","7");for(int i=0;i<5;i++)assertTrue(h.step(i).accepts(entries.get(i)));}
  Question q=EnglishDecimalWords.make(EnglishDecimalWords.WRITE,"0.070");assertTrue(new Checker().check(q,List.of(),List.of("nought point zero seven zero")).correct());assertFalse(new Checker().check(q,List.of(),List.of("zero point seven zero")).correct());
 }
}
