package com.gomgomapps.math.core;
import java.math.*;import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class EquivalentQuantityStoriesTest {
 @Test public void fractionConditionsAndThreeEquivalentFormsKeepTotalAndUnit(){Checker checker=new Checker();Set<String> conditions=new HashSet<>();for(int i=0;i<FractionPercentEquivalence.domainSize();i++){var v=FractionPercentEquivalence.conditionAt(i);Question q=EquivalentQuantityStories.make(EquivalentQuantityStories.FRACTION,100,"L",v.numerator()+"/"+v.denominator());assertTrue(conditions.add(q.signature()));assertEquals(Rational.of(100L*v.numerator(),v.denominator()),Expression.number(q.answers[0]));assertNotNull(EquivalentQuantityStories.read(q));}assertEquals(2345,conditions.size());for(String unit:List.of("m","L"))for(int total:new int[]{10,100})for(String[] raw:new String[][]{{"0/1000","0.000","0.0"},{"1/40","0.025","2.5"},{"233/500","0.466","46.6"},{"1/1","1.000","100.0"}}){BigDecimal rate=new BigDecimal(raw[1]);int index=0;for(String id:List.of(EquivalentQuantityStories.FRACTION,EquivalentQuantityStories.DECIMAL,EquivalentQuantityStories.PERCENT)){String given=raw[index++];if(given.equals("1/1"))given="1000/1000";Question q=EquivalentQuantityStories.make(id,total,unit,given);assertEquals(unit,EquivalentQuantityStories.read(q).unit());BigDecimal answer=rate.multiply(BigDecimal.valueOf(total));assertTrue(checker.check(q,List.of(),List.of(answer.toPlainString())).correct());assertFalse(checker.check(q,List.of(),List.of(answer.add(new BigDecimal(".01")).toPlainString())).correct());assertEquals("",q.expression);assertFalse(q.stepSupport);}}}
 @Test public void helpReadsPublicStoryWithoutTransferringAnswers(){int index=0;for(String id:List.of(EquivalentQuantityStories.FRACTION,EquivalentQuantityStories.DECIMAL,EquivalentQuantityStories.PERCENT)){String rate=List.of("1/40","0.025","2.5").get(index++);Question original=EquivalentQuantityStories.make(id,80,"m",rate),q=new Question(id,original.prompt,"poison","999");HelpPlan h=HelpPlan.forQuestion(q);List<String> fields=id.equals(EquivalentQuantityStories.FRACTION)?List.of("80","1","40","0.025","2"):id.equals(EquivalentQuantityStories.DECIMAL)?List.of("80","0.025","2"):List.of("80","2.5","0.025","2");assertEquals(fields.size(),h.size());assertFalse(h.canTransfer());for(int i=0;i<fields.size();i++)assertTrue(h.step(i).accepts(fields.get(i)));}assertNull(EquivalentQuantityStories.read(new Question(EquivalentQuantityStories.FRACTION,"물 999999999999 L의 1/40를 사용했습니다.\n사용한 물은 몇 L인가요?","","999")));}
 @Test public void fourTypesHaveReviewedPlacementAndFreshSupply(){var pack=GlobalCurriculum.packs("GB").stream().filter(p->p.id.equals("england-primary-2021-v1")).findFirst().orElseThrow();for(String id:List.of(EquivalentQuantityStories.FRACTION,EquivalentQuantityStories.DECIMAL,EquivalentQuantityStories.PERCENT,DecimalPercentReverse.ID)){assertTrue(pack.inGrade(id,5));assertFalse(pack.inGrade(id,4));assertFalse(Curriculum.inCurriculum(Catalog.get(id),2022));Generator generator=new Generator(new Random(89));List<String> recent=new ArrayList<>();Set<String> units=new HashSet<>();for(int i=0;i<150;i++){Question q=generator.next(id,recent,true,GlobalCurriculum.limits(pack.id,id,5));assertFalse(recent.contains(q.signature()));recent.add(q.signature());assertTrue(q.choices.isEmpty());assertNotNull(q.studyGuide);if(EquivalentQuantityStories.supports(id))units.add(EquivalentQuantityStories.read(q).unit());}if(EquivalentQuantityStories.supports(id))assertEquals(Set.of("m","L"),units);}assertEquals(46900,EquivalentQuantityStories.domainSize(EquivalentQuantityStories.FRACTION));assertEquals(20020,EquivalentQuantityStories.domainSize(EquivalentQuantityStories.DECIMAL));assertEquals(20020,EquivalentQuantityStories.domainSize(EquivalentQuantityStories.PERCENT));}
 @Test public void oldSavedStoriesRemainReadableAndDoNotBecomeNewConditions(){String id=EquivalentQuantityStories.FRACTION;Generator g=new Generator(new Random(89));Question first=g.next(id,List.of(),false);String oldPrompt=first.prompt.replace("만큼을","를");Question saved=new Question(id,oldPrompt,"poison","999");assertNotNull(EquivalentQuantityStories.read(saved));assertEquals(first.signature(),EquivalentQuantityStories.identity(saved.signature()));assertEquals(5,HelpPlan.forQuestion(saved).size());Question next=new Generator(new Random(89)).next(id,List.of(saved.signature()),false);assertNotEquals(first.signature(),next.signature());}

}
