package com.gomgomapps.math.core;
import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class FactorPairMentalTest {
 @Test public void everyPublicFactorPairAndConvenientTripleChecksWithoutHiddenKeys(){
  Checker c=new Checker();Set<String> signatures=new HashSet<>(),independent=new HashSet<>();int pairs=0;
  for(int n=2;n<=144;n++){int rank=0;for(int a=1;a<=n/a;a++)if(n%a==0){int b=n/a;Question q=FactorPairMental.pairQuestion(n,++rank);pairs++;assertTrue(signatures.add(q.signature()));q.answers=new String[]{"poison"};q.expression="poison";assertArrayEquals(new int[]{n,rank,a,b},FactorPairMental.read(q));assertTrue(c.check(q,List.of(),List.of(""+a,""+b)).correct());assertEquals(0,c.check(q,List.of(),List.of(""+(a+1),""+b)).index);assertEquals(1,c.check(q,List.of(),List.of(""+a,""+(b+1))).index);HelpPlan h=HelpPlan.forQuestion(q);assertEquals(3,h.size());assertFalse(h.canTransfer());assertTrue(h.restore(null,q.id).entries.stream().allMatch(String::isEmpty));assertTrue(h.step(0).accepts(""+a));assertTrue(h.step(1).accepts(""+b));assertTrue(h.step(2).accepts(""+n));for(int j=0;j<h.size();j++)assertFalse(h.step(j).before.matches("(?s).*[0-9].*"));}}
  assertEquals(pairs,FactorPairMental.PAIR_DOMAIN.size());assertTrue(pairs>100);signatures.clear();
  for(int i=0;i<FactorPairMental.MENTAL_DOMAIN.size();i++){Question q=FactorPairMental.indexed(FactorPairMental.MENTAL,i);assertTrue(signatures.add(q.signature()));int[] v=FactorPairMental.read(q);assertNotNull(v);int product=v[0]*v[1]*v[2];int[] sorted={v[0],v[1],v[2]};Arrays.sort(sorted);independent.add(Arrays.toString(sorted));q.answers=new String[]{"poison"};q.expression="poison";assertTrue(c.check(q,List.of(),List.of(""+product)).correct());assertEquals(Checker.Status.WRONG_ANSWER,c.check(q,List.of(),List.of(""+(product+1))).status);HelpPlan h=HelpPlan.forQuestion(q);assertEquals(4,h.size());assertFalse(h.canTransfer());assertTrue(h.restore(null,q.id).entries.stream().allMatch(String::isEmpty));for(String code:List.of("12","13","23"))assertEquals(code.equals(""+v[4]),h.step(0).accepts(code));assertTrue(h.step(1).accepts(""+v[3]));assertTrue(h.step(2).accepts(""+v[5]));assertTrue(h.step(3).accepts(""+product));for(int j=1;j<h.size();j++)assertFalse(h.step(j).before.matches("(?s).*[0-9].*"));}
  assertTrue(independent.size()>100);
 }
 @Test public void realGrade4SupplyIsFreshThenOldestAndLowerGradesRetainTheirOwnContent(){
  Learning.Profile profile=new Learning.Profile();GlobalCurriculum.chooseCountry(profile,"GB");GlobalCurriculum.choosePack(profile,"england-primary-2021-v1");GlobalCurriculum.Pack pack=GlobalCurriculum.pack(profile);Generator gen=new Generator(new Random(147));for(String id:List.of(FactorPairMental.PAIRS,FactorPairMental.MENTAL)){assertTrue(pack.inGrade(id,4));assertFalse(pack.inGrade(id,3));List<String> history=new ArrayList<>();CurriculumLimits limits=GlobalCurriculum.limits(pack.id,id,4);for(int i=0;i<200;i++){Question q=gen.next(id,history,false,limits);assertFalse(history.contains(q.signature()));history.add(q.signature());assertNotNull(FactorPairMental.read(q));}Map<String,Integer> recent=new LinkedHashMap<>();int count=id.equals(FactorPairMental.PAIRS)?FactorPairMental.PAIR_DOMAIN.size():FactorPairMental.MENTAL_DOMAIN.size();String oldest=FactorPairMental.indexed(id,0).signature();for(int i=0;i<count;i++)recent.put(FactorPairMental.indexed(id,i).signature(),i);assertEquals(oldest,FactorPairMental.next(id,new Random(1),limits,recent).signature());}assertTrue(pack.inGrade(ProductOrder.ID,2));assertFalse(pack.inGrade(ProductOrder.ID,4));
 }
 @Test public void squarePairsPrimePairsAndCorruptPublicInputsStayBounded(){
  assertArrayEquals(new int[]{144,8,12,12},FactorPairMental.read(FactorPairMental.pairQuestion(144,8)));assertArrayEquals(new int[]{137,1,1,137},FactorPairMental.read(FactorPairMental.pairQuestion(137,1)));assertNull(FactorPairMental.read(new Question(FactorPairMental.PAIRS,"곱해서 144이 되는 두 수를 찾으세요.\n작은 수부터 9번째 곱셈짝\n작은 수 ≤ 큰 수","","12")));assertNull(FactorPairMental.read(new Question(FactorPairMental.MENTAL,"2 × 5 × 5 = □\n목표 수: 10\n먼저 곱해서 목표 수가 되는 두 수를 찾아 계산하세요.","","50")));assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(FactorPairMental.pairQuestion(12,2),List.of(),List.of("2","")).status);
 }
}
