package com.gomgomapps.math.core;
import org.junit.Test;import static org.junit.Assert.*;import java.util.*;
public class FactorTeachingTest {
 private Rational[] pair(Expression.Poly p){for(int u=-20;u<=20;u++)for(int v=u;v<=20;v++)if(Rational.of(u+v).equals(p.coefficient(1))&&Rational.of(u*v).equals(p.coefficient(0)))return new Rational[]{Rational.of(u),Rational.of(v)};throw new AssertionError(p.toString());}
 @Test public void fourHundredDistinctMappedProblemsAndTheirFramesAreSolvedFromPublicExpressions(){for(String id:List.of("expand","factor","commonFactorFrame","quadratic")){Generator g=new Generator(new Random(91));Set<String> seen=new HashSet<>();boolean repeated=false,zero=false;for(int i=0;i<100;i++){Question q=g.next(id,seen,false,GlobalCurriculum.limits("br-bncc-fundamental-2017-v1",id,9));assertTrue(id,seen.add(q.signature()));Expression.Poly p=id.equals("quadratic")?Expression.equation(q.expression):Expression.parse(q.expression);List<String> answers=new ArrayList<>();List<Rational> frames=new ArrayList<>();
  if(id.equals("commonFactorFrame")){long a=p.coefficient(1).intValue(),b=p.coefficient(0).intValue(),k=java.math.BigInteger.valueOf(a).gcd(java.math.BigInteger.valueOf(b)).longValueExact();answers=List.of(""+k,""+(a/k),""+(b/k));frames=List.of(Rational.of(k),Rational.of(a/k),Rational.of(b/k));}
  else{Rational[] pair=pair(p);Rational b=p.coefficient(1),c=p.coefficient(0);if(id.equals("expand")){answers.add(Expression.parse("x^2+("+b+")x+("+c+")").toString());frames=List.of(Rational.ONE,b,c);}else{frames.addAll(List.of(b,c,pair[0],pair[1]));if(id.equals("factor"))answers.add("(x+("+pair[0]+"))(x+("+pair[1]+"))");else{assertEquals(Rational.ONE,p.coefficient(2));Set<String> roots=new LinkedHashSet<>();for(int r=-20;r<=20;r++)if(p.at(Rational.of(r)).isZero())roots.add(""+r);assertEquals(new HashSet<>(Arrays.asList(q.answers)),roots);answers.addAll(roots);frames.add(pair[0].neg());if(!pair[0].equals(pair[1]))frames.add(pair[1].neg());repeated|=roots.size()==1;zero|=roots.contains("0");}}}
  assertTrue(id,new Checker().check(q,List.of(),answers).correct());HelpPlan plan=HelpPlan.forQuestion(q);assertNotNull(plan);assertFalse(plan.canTransfer());assertEquals(frames.size(),plan.size());for(int j=0;j<frames.size();j++){assertTrue(id,plan.step(j).accepts(frames.get(j).toString()));assertFalse(plan.step(j).accepts(frames.get(j).add(Rational.ONE).toString()));}if(id.equals("commonFactorFrame"))assertNull(FactorTeaching.inputTemplate(q));else assertNotNull(FactorTeaching.inputTemplate(q));
 }if(id.equals("quadratic"))assertTrue(repeated&&zero);}}
 @Test public void oldGuidesStayIntactAndNewGuidesIgnoreTheAnswerKey(){Question q=new Question("factor","인수분해하세요.\nx^2+3x-10","x^2+3x-10","bogus");FactorTeaching.attach(q);assertEquals("-2",q.studyGuide.frames.get(2).expected);assertEquals("5",q.studyGuide.frames.get(3).expected);assertEquals("(x + (-2))(x + (5))",FactorTeaching.completedText(q,List.of("3","-10","-2","5")));StudyGuide old=new StudyGuide().step("old","","","1");q.studyGuide=old;FactorTeaching.attach(q);assertSame(old,q.studyGuide);}
 @Test public void generalRealQuadraticsKeepAFormulaScaffold(){Question q=new Question("quadratic","방정식을 푸세요.\n2x^2-3x-1=0","2x^2-3x-1=0","bogus");q.kind="roots";FactorTeaching.attach(q);assertEquals(List.of("2","-3","-1","17","3","4"),q.studyGuide.frames.stream().map(f->f.expected).toList());assertEquals("x = (3 ± √(17)) / (4)",FactorTeaching.completedText(q,List.of("2","-3","-1","17","3","4")));assertEquals("x = (−b ± √D) ÷ (2a)",FactorTeaching.inputTemplate(q));}
 @Test public void mappingSelectsFourTypesAndDoesNotConstrainOtherPacks(){Learning.Profile p=new Learning.Profile();GlobalCurriculum.chooseCountry(p,"BR");GlobalCurriculum.choosePack(p,"br-bncc-fundamental-2017-v1");for(String id:List.of("expand","factor","commonFactorFrame","quadratic"))assertTrue(GlobalCurriculum.pack(p).inGrade(id,9));Question general=new Question("quadratic","","2x^2-3x-1=0","(3-√17)/4","(3+√17)/4");general.kind="roots";assertFalse(GlobalCurriculum.limits("br-bncc-fundamental-2017-v1","quadratic",9).allows(general));assertTrue(CurriculumLimits.NONE.allows(general));}
}
