package com.gomgomapps.math.core;
import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class FactorPowerStoriesTest {
 static final List<String> IDS=List.of(FactorPowerStories.FACTOR,FactorPowerStories.MULTIPLE,FactorPowerStories.SQUARE,FactorPowerStories.CUBE);
 @Test public void everyPublicConditionHasExactAnswer(){for(String id:IDS){assertTrue(FactorPowerStories.count(id)>=100);for(int i=0;i<FactorPowerStories.count(id);i++){Question q=FactorPowerStories.at(id,i);int[] n=FactorPowerStories.read(q);int expected;if(id.equals(FactorPowerStories.FACTOR)){int divisor=n[0]%n[1]==0?n[1]:n[2];assertTrue(n[0]%divisor==0);expected=n[0]/divisor;}else if(id.equals(FactorPowerStories.MULTIPLE)){expected=0;while(expected<n[1])expected+=n[0];}else if(id.equals(FactorPowerStories.SQUARE))expected=n[0]*n[0]*n[1];else expected=n[0]*n[0]*n[0]/n[1];assertEquals(""+expected,q.answers[0]);q.answers=new String[]{"poison"};q.expression="poison";assertTrue(new Checker().check(q,List.of(),List.of(""+expected)).correct());assertEquals(Checker.Status.WRONG_ANSWER,new Checker().check(q,List.of(),List.of(""+(expected+1))).status);}}}
 @Test public void blankHelpRelationshipsAndNoTransfer(){for(String id:IDS){Question q=FactorPowerStories.at(id,55);int[] n=FactorPowerStories.read(q);List<Integer> answers=new ArrayList<>();if(id.equals(FactorPowerStories.FACTOR))answers.addAll(List.of(n[0],n[1],n[2],n[0]%n[1],n[0]%n[2],n[0]%n[1]==0?n[1]:n[2],FactorPowerStories.answer(id,n)));else if(id.equals(FactorPowerStories.MULTIPLE))answers.addAll(List.of(n[0],n[1],n[1]/n[0],n[1]%n[0]==0?0:1,FactorPowerStories.answer(id,n)));else{answers.addAll(List.of(n[0],n[1],n[0]*n[0]));if(id.equals(FactorPowerStories.CUBE))answers.add(n[0]*n[0]*n[0]);answers.add(FactorPowerStories.answer(id,n));}HelpPlan plan=HelpPlan.forQuestion(q);assertFalse(plan.canTransfer());assertEquals(answers.size(),plan.size());for(int i=0;i<plan.size();i++){assertTrue(plan.step(i).accepts(""+answers.get(i)));assertFalse(plan.step(i).accepts(""));}assertFalse(plan.step(plan.size()-1).before.contains(""+FactorPowerStories.answer(id,n)));}}
 @Test public void freshConditionsAndExplicitGradeOnly(){var pack=GlobalCurriculum.packs("GB").stream().filter(p->p.id.equals("england-primary-2021-v1")).findFirst().orElseThrow();for(String id:IDS){assertTrue(pack.inGrade(id,5));assertFalse(Curriculum.inCurriculum(Catalog.get(id),2022));Generator gen=new Generator(new Random(172));List<String> recent=new ArrayList<>();for(int i=0;i<100;i++){Question q=gen.next(id,recent,false,GlobalCurriculum.limits(pack.id,id,5));assertFalse(recent.contains(q.signature()));recent.add(q.signature());assertFalse(HelpPlan.forQuestion(q).canTransfer());}}}
 @Test public void exactThresholdsAndInvalidGivens(){assertEquals("12",FactorPowerStories.make(FactorPowerStories.MULTIPLE,6,12,0).answers[0]);assertEquals("18",FactorPowerStories.make(FactorPowerStories.MULTIPLE,6,13,0).answers[0]);assertEquals("6",FactorPowerStories.make(FactorPowerStories.MULTIPLE,6,1,0).answers[0]);assertEquals("9",FactorPowerStories.make(FactorPowerStories.CUBE,3,3,0).answers[0]);for(int[] v:List.of(new int[]{12,2,3},new int[]{13,2,3}))try{FactorPowerStories.make(FactorPowerStories.FACTOR,v[0],v[1],v[2]);fail();}catch(IllegalArgumentException expected){}Question q=FactorPowerStories.make(FactorPowerStories.SQUARE,2,3,0);for(String raw:List.of("","1/2","1.5","1234567"))assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(q,List.of(),List.of(raw)).status);assertEquals(Checker.Status.WRONG_ANSWER,new Checker().check(q,List.of(),List.of("−1")).status);q.prompt=q.prompt.replace("2줄","3줄");assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(q,List.of(),List.of("12")).status);}
}
