package com.gomgomapps.math.core;
import java.math.*;import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class FractionPercentEquivalenceTest {
 private static final int[] DENOMINATORS={2,4,5,10,20,25,40,50,100,125,200,250,500,1000};
 @Test public void entireFiniteDomainIsExactAndEachAnswerHasItsOwnError(){Checker check=new Checker();Set<String> identities=new HashSet<>();for(int d:DENOMINATORS)for(int n=0;n<=d;n++){
  Question q=FractionPercentEquivalence.make(n,d);assertTrue(identities.add(q.signature()));assertEquals(Rational.of(n,d),Expression.number(q.answers[0]));assertEquals(Rational.of(n*100L,d),Expression.number(q.answers[1]));assertEquals("",q.expression);assertFalse(q.stepSupport);assertFalse(FractionInput.available(q));assertTrue(check.check(q,List.of(),Arrays.asList(q.answers)).correct());
  BigDecimal v=new BigDecimal(q.answers[0]),p=new BigDecimal(q.answers[1]);assertEquals(0,check.check(q,List.of(),List.of(v.add(new BigDecimal(".001")).toPlainString(),p.toPlainString())).index);assertEquals(1,check.check(q,List.of(),List.of(v.toPlainString(),p.add(new BigDecimal(".01")).toPlainString())).index);assertFalse(check.check(q,List.of(),List.of(n+"/"+d,p.toPlainString())).correct());
 }assertEquals(2345,identities.size());assertEquals(2345,FractionPercentEquivalence.domainSize());for(String[] anchor:new String[][]{{"1","2","0.5","50"},{"1","4","0.25","25"},{"1","5","0.2","20"},{"2","5","0.4","40"},{"4","5","0.8","80"},{"23","40","0.575","57.5"},{"1","125","0.008","0.8"},{"0","1000","0","0"},{"1000","1000","1","100"}}){Question q=FractionPercentEquivalence.make(Integer.parseInt(anchor[0]),Integer.parseInt(anchor[1]));assertArrayEquals(new String[]{anchor[2],anchor[3]},q.answers);}}
 @Test public void fiveStudentFramesAreRebuiltFromThePublicFraction(){Question original=FractionPercentEquivalence.make(23,40),q=new Question(FractionPercentEquivalence.ID,original.prompt,"poison","999","999");HelpPlan h=HelpPlan.forQuestion(q);assertEquals(5,h.size());assertFalse(h.canTransfer());List<String> inputs=List.of("40","23","0.025","0.575","57.5");for(int i=0;i<inputs.size();i++)assertTrue(h.step(i).accepts(inputs.get(i)));assertFalse(h.step(4).accepts("0.575"));assertFalse(h.step(2).accepts("1/40"));}
 @Test public void supplyUsesNewConditionsThenOldestAndReviewedYearFiveOnly(){var pack=GlobalCurriculum.packs("GB").stream().filter(p->p.id.equals("england-primary-2021-v1")).findFirst().orElseThrow();String id=FractionPercentEquivalence.ID;assertTrue(pack.inGrade(id,5));assertFalse(pack.inGrade(id,4));assertFalse(Curriculum.inCurriculum(Catalog.get(id),2022));var limits=GlobalCurriculum.limits(pack.id,id,5);Generator g=new Generator(new Random(88));List<String> recent=new ArrayList<>();for(int i=0;i<150;i++){Question q=g.next(id,recent,true,limits);assertTrue(q.choices.isEmpty());assertFalse(recent.contains(q.signature()));recent.add(q.signature());assertNotNull(q.studyGuide);assertEquals(2,q.answers.length);}Map<String,Integer> exhausted=new HashMap<>();int index=0;String oldest=null;for(int d:DENOMINATORS)for(int n=0;n<=d;n++){String key=FractionPercentEquivalence.make(n,d).signature();if(oldest==null)oldest=key;exhausted.put(key,index++);}assertEquals(oldest,FractionPercentEquivalence.next(new Random(88),limits,exhausted).signature());}
}
