package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class FunctionValueRelationsTest {
 @Test public void invalidZeroDenominatorAndNegativeRadicandNeverGetValidCalculationFrames(){for(Question q:List.of(new Question("sec_rational_function","f(x)=3/(x-(2))+1일 때 f(2)의 값은?","","0"),new Question("sec_radical_function","f(x)=√(x-(2))+1일 때 f(1)의 값은?","","0"))){FunctionValueRelations.attach(q);assertNull(q.studyGuide);}}
 private List<Rational> values(Question q){boolean rational=q.skillId.equals("sec_rational_function");List<Long> n=new ArrayList<>();Matcher m=Pattern.compile("-?\\d+").matcher(q.prompt);while(m.find())n.add(Long.parseLong(m.group()));assertEquals(rational?4:3,n.size());long a=rational?n.get(0):0,h=n.get(rational?1:0),k=n.get(rational?2:1),x=n.get(rational?3:2),d=x-h;Rational u;if(rational){assertNotEquals(0,d);u=Rational.of(a,d);}else{assertTrue(d>=0);long root=-1;for(long z=0;z*z<=d;z++)if(z*z==d)root=z;assertTrue(root>=0);u=Rational.of(root);}List<Rational> result=new ArrayList<>();if(rational)result.add(Rational.of(a));result.addAll(List.of(Rational.of(h),Rational.of(k),Rational.of(x),Rational.of(d),u,u.add(Rational.of(k))));return result;}
 private void verify(Question q){List<Rational> v=values(q);assertTrue(new Checker().check(q,List.of(),List.of(v.get(v.size()-1).toString())).correct());String id=q.id,prompt=q.prompt,signature=q.signature();Arrays.fill(q.answers,"999");q.givenNumbers.replaceAll((k,x)->"999");q.choiceInputs=new Rational[]{Rational.of(999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(v.size(),p.size());assertFalse(p.canTransfer());assertEquals(id,q.id);assertEquals(prompt,q.prompt);assertEquals(signature,q.signature());for(int i=0;i<v.size();i++){assertTrue(p.step(i).accepts(v.get(i).toString()));assertFalse(p.step(i).accepts(v.get(i).add(Rational.ONE).toString()));assertEquals("",p.step(i).after);assertFalse(p.step(i).before.matches(".*[0-9].*"));}}
 @Test public void generatedPublicConditionsVaryAndIncludeZeroBoundary(){Generator g=new Generator(new Random(3001));for(String skill:List.of("sec_rational_function","sec_radical_function")){Set<String> prompts=new HashSet<>();Set<Integer> positions=new HashSet<>();Set<Rational> shifts=new HashSet<>(),constants=new HashSet<>(),insides=new HashSet<>();for(int i=0;i<12000;i++){Question q=g.next(skill,List.of(),i%2==0);prompts.add(q.prompt);if(!q.choices.isEmpty())positions.add(q.correctChoice);List<Rational> v=values(q);int offset=skill.equals("sec_rational_function")?1:0;shifts.add(v.get(offset));constants.add(v.get(offset+1));insides.add(v.get(offset+3));verify(q);}assertTrue(prompts.size()>100);assertEquals(Set.of(0,1,2,3),positions);assertTrue(shifts.contains(Rational.ZERO));assertTrue(constants.contains(Rational.ZERO));if(skill.equals("sec_radical_function"))assertTrue(insides.contains(Rational.ZERO));else{assertFalse(insides.contains(Rational.ZERO));assertTrue(insides.contains(Rational.of(-6)));assertTrue(insides.contains(Rational.of(6)));}}}
 @Test public void savedSignedFractionAndZeroRootHelpPreservesIdentityAndDrafts(){for(Question q:List.of(new Question("sec_rational_function","f(x)=-5/(x-(-2))+3일 때 f(1)의 값은?","","4/3"),new Question("sec_radical_function","f(x)=√(x-(-4))-2일 때 f(-4)의 값은?","","-2"),new Question("sec_radical_function","f(x)=√(x-(4))+0일 때 f(13)의 값은?","","3"))){q.studyGuide=new StudyGuide().step("옛 도움","1 - (-2) = ","","3");verify(q);HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft draft=new HelpPlan.Draft();draft.questionId=q.id;draft.stage=1;draft.entries=new ArrayList<>(List.of("3"));assertEquals(0,p.restore(draft,q.id).stage);draft.entries.set(0,values(q).get(0).toString());draft.stage=1;assertEquals(1,HelpPlan.forQuestion(q).restore(draft.copy(),q.id).stage);}}
}
