package com.gomgomapps.math.core;
import org.junit.Test;import static org.junit.Assert.*;import java.util.*;import java.util.regex.*;
public class FunctionConceptsTest {
 @Test public void mappingSupplyCoversTrueFalseRepeatedPairsAndSharedOutputs(){Generator g=new Generator(new Random(31));Set<String> seen=new HashSet<>();Set<Integer> positions=new HashSet<>();boolean repeatedValid=false,manyToOne=false;int trueCount=0;Set<Integer> counts=new HashSet<>();
  for(int i=0;i<100;i++){Question q=g.next("functionUniqueOutput",seen,false);assertTrue(seen.add(q.signature()));double[] d=q.diagram.values;assertEquals(8,d.length);Map<Integer,Set<Integer>> grouped=new HashMap<>();Set<String> pairs=new HashSet<>();Set<Integer> allY=new HashSet<>();for(int row=0;row<4;row++){int x=(int)d[2*row],y=(int)d[2*row+1];grouped.computeIfAbsent(x,k->new HashSet<>()).add(y);pairs.add(x+","+y);allY.add(y);}int max=grouped.values().stream().mapToInt(Set::size).max().orElseThrow();counts.add(max);String answer=max==1?"1":"0";assertEquals(answer,q.answers[0]);assertEquals(""+max,q.studyGuide.frames.get(0).expected);assertEquals(answer,q.studyGuide.frames.get(1).expected);assertEquals(q.choiceLabels,q.studyGuide.frames.get(1).options);assertFalse(q.studyGuide.transfer);assertEquals(Set.of("0","1"),new HashSet<>(q.choices));assertEquals(answer,q.choices.get(q.correctChoice));positions.add(q.correctChoice);assertTrue(new Checker().check(q,List.of(),List.of(answer)).correct());assertFalse(new Checker().check(q,List.of(),List.of(answer.equals("1")?"0":"1")).correct());if(max==1){trueCount++;repeatedValid|=pairs.size()<4;manyToOne|=allY.size()<grouped.size();}}
  assertTrue(trueCount>25&&trueCount<75);assertTrue(repeatedValid);assertTrue(manyToOne);assertEquals(Set.of(1,2,3),counts);assertEquals(Set.of(0,1),positions);
 }
 @Test public void squareSupplyHasOneHundredDistinctExactPublicCases(){Generator g=new Generator(new Random(32));Set<String> seen=new HashSet<>();Set<Integer> xSigns=new HashSet<>(),aSigns=new HashSet<>(),positions=new HashSet<>();Pattern pattern=Pattern.compile("제곱 함수식: y = (-?\\d+)x² ([+-]) (\\d+)\\nx = (-?\\d+)일 때 y를 구하세요[.]");
  for(int i=0;i<100;i++){Question q=g.next("functionSquareOutput",seen,i%2==0);assertTrue(seen.add(q.signature()));Matcher m=pattern.matcher(q.prompt);assertTrue(m.matches());int a=Integer.parseInt(m.group(1)),b=Integer.parseInt(m.group(3))*(m.group(2).equals("+")?1:-1),x=Integer.parseInt(m.group(4));long square=(long)x*x,total=a*square+b;assertEquals(""+total,q.answers[0]);assertEquals(""+square,q.studyGuide.frames.get(0).expected);assertEquals(""+(a*square),q.studyGuide.frames.get(1).expected);assertEquals(""+total,q.studyGuide.frames.get(2).expected);assertArrayEquals(new double[]{a,b,x},q.diagram.values,0);assertEquals("functionSquareGraph",q.diagram.type);assertFalse(HelpPlan.forQuestion(q).canTransfer());xSigns.add(Integer.signum(x));aSigns.add(Integer.signum(a));if(!q.choices.isEmpty()){assertEquals(4,new HashSet<>(q.choices).size());assertEquals(q.answers[0],q.choices.get(q.correctChoice));positions.add(q.correctChoice);}}
  assertEquals(Set.of(-1,0,1),xSigns);assertEquals(Set.of(-1,1),aSigns);assertEquals(Set.of(0,1,2,3),positions);
 }
 @Test public void repeatedPairDoesNotCreateASecondOutput(){assertEquals(1,FunctionConcepts.maximumOutputs(new double[]{2,5,2,5,3,5,4,7}));assertEquals(2,FunctionConcepts.maximumOutputs(new double[]{2,5,2,7,3,5,4,7}));}
 @Test public void negativeInputsAreSquaredBeforeMultiplying(){Generator g=new Generator(new Random(33));for(int i=0;i<200;i++){Question q=g.next("functionSquareOutput",List.of(),false);long x=q.choiceInputs[2].n.longValueExact();if(x<0){assertTrue(Long.parseLong(q.studyGuide.frames.get(0).expected)>0);assertEquals(x*x,Long.parseLong(q.studyGuide.frames.get(0).expected));return;}}fail("Expected negative x case");}
 @Test public void selectedNinthGradeConceptsAreNotPriorGradeDiagnosis(){Learning.Profile p=new Learning.Profile();GlobalCurriculum.chooseCountry(p,"BR");GlobalCurriculum.choosePack(p,"br-bncc-fundamental-2017-v1");p.grade=9;for(var s:FunctionConcepts.SKILLS){assertTrue(GlobalCurriculum.pack(p).inGrade(s.id,9));assertFalse(GlobalCurriculum.scope(p).stream().anyMatch(x->x.id.equals(s.id)));}}
}
