package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class HireInterestRelationsTest {
 @Test public void publicPaymentsAndInterestAreIndependentlySolvedBeforeKeyMutation(){Generator g=new Generator(new Random(1830));Set<String> modes=new HashSet<>();for(String id:List.of("hirePurchase","simpleInterest"))for(int i=0;i<600;i++){Question q=g.next(id,List.of(),i%2==0);List<Rational> v=new ArrayList<>();Matcher m=Pattern.compile("\\d+(?:\\.\\d+)?").matcher(q.prompt);while(m.find())v.add(Expression.number(m.group()));List<Rational> expected=new ArrayList<>();Rational answer;
  if(id.equals("hirePurchase")){boolean difference=q.prompt.contains("현금 가격");modes.add(difference?"difference":"total");Rational all=v.get(1).mul(v.get(2)),total=v.get(0).add(all);expected.addAll(v);expected.add(all);expected.add(total);answer=difference?total.sub(v.get(3)):total;if(difference)expected.add(answer);}
  else{modes.add("interest");Rational fraction=v.get(1).div(Rational.of(100)),annual=v.get(0).mul(fraction);answer=annual.mul(v.get(2));expected.addAll(v);expected.addAll(List.of(fraction,annual,answer));}
  assertTrue(new Checker().check(q,List.of(),List.of(answer.toString())).correct());verify(q,expected);
 }assertEquals(Set.of("total","difference","interest"),modes);}
 @Test public void savedDecimalValuesKeepExactSteps(){verify(new Question("hirePurchase","계약금: 3.5\n할부금: 1.25 × 3회 · 추가 비용 없음\n현금 가격: 6.5\n할부로 더 내는 금액은?","",".75"),List.of(Rational.of(7,2),Rational.of(5,4),Rational.of(3),Rational.of(13,2),Rational.of(15,4),Rational.of(29,4),Rational.of(3,4)));verify(new Question("simpleInterest","원금: 250.5\n연이율: 2.5% · 기간: 3년\n단리로 계산한 이자는?","","18.7875"),List.of(Rational.of(501,2),Rational.of(5,2),Rational.of(3),Rational.of(1,40),Rational.of(501,80),Rational.of(1503,80)));}
 @Test public void oldCalculatedDraftDoesNotBecomeNewGivenAndNewDraftRestores(){Question q=new Question("hirePurchase","계약금: 300\n할부금: 40 × 3회 · 추가 비용 없음\n할부 총금액은?","","420");HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of("120",""));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));d.entries.set(0,"300");d.stage=1;HelpPlan.Draft restored=HelpPlan.forQuestion(q).restore(d.copy(),q.id);assertEquals(1,restored.stage);assertEquals("300",restored.entries.get(0));}
 private void verify(Question q,List<Rational> expected){String signature=q.signature();Arrays.fill(q.answers,"999999");q.choiceInputs=new Rational[]{Rational.of(999999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(signature,q.signature());assertEquals(expected.size(),p.size());assertFalse(p.canTransfer());for(int k=0;k<p.size();k++){assertTrue(p.step(k).accepts(expected.get(k).toString()));assertFalse(p.step(k).accepts(expected.get(k).add(Rational.ONE).toString()));assertFalse(p.step(k).before.replace("100","").matches("(?s).*\\d.*"));}}
}
