package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class IntervalRelationsTest {
 private List<Rational> values(Question q){String n="[+-]?\\d+(?:\\.\\d+)?(?:/\\d+)?";Matcher m;
  if(q.skillId.equals("sec_quadratic_line_intersections")){m=Pattern.compile("이차함수 y=(?:x²|("+n+")\\(x-\\(("+n+")\\)\\)²\\+\\(("+n+")\\))과 직선 y=("+n+")의 교점은 몇 개인가요\\?").matcher(q.prompt);assertTrue(m.matches());Rational a=m.group(1)==null?Rational.ONE:Expression.number(m.group(1)),b=m.group(3)==null?Rational.ZERO:Expression.number(m.group(3)),k=Expression.number(m.group(4)),square=k.sub(b).div(a);int count=square.compareTo(Rational.ZERO)<0?0:square.equals(Rational.ZERO)?1:2;return List.of(a,b,k,k.sub(b),square,Rational.of(count));}
  if(q.skillId.equals("sec_linear_inequality_system")){m=Pattern.compile("x-\\(("+n+")\\)>("+n+")이고 x-\\(("+n+")\\)≤("+n+")를 모두 만족하는 정수 x는 몇 개인가요\\?").matcher(q.prompt);assertTrue(m.matches());Rational h=Expression.number(m.group(1)),a=Expression.number(m.group(2)),b=Expression.number(m.group(4));assertEquals(h,Expression.number(m.group(3)));List<Integer> allowed=new ArrayList<>();for(int x=-100;x<=100;x++){Rational shifted=Rational.of(x).sub(h);if(shifted.compareTo(a)>0&&shifted.compareTo(b)<=0)allowed.add(x);}assertFalse(allowed.isEmpty());return List.of(h,a,b,a.add(h),b.add(h),Rational.of(allowed.get(0)),Rational.of(allowed.get(allowed.size()-1)),Rational.of(allowed.size()));}
  m=Pattern.compile("\\|x-\\(("+n+")\\)\\|≤("+n+")를 만족하는 정수 x는 몇 개인가요\\?").matcher(q.prompt);assertTrue(m.matches());Rational h=Expression.number(m.group(1)),a=Expression.number(m.group(2));List<Integer> allowed=new ArrayList<>();for(int x=-100;x<=100;x++){Rational delta=Rational.of(x).sub(h);if(delta.compareTo(a)<=0&&delta.compareTo(a.mul(Rational.of(-1)))>=0)allowed.add(x);}assertFalse(allowed.isEmpty());return List.of(h,a,h.sub(a),h.add(a),Rational.of(allowed.get(0)),Rational.of(allowed.get(allowed.size()-1)),Rational.of(allowed.size()));
 }
 private void verify(Question q,List<Rational> v){String id=q.id,signature=q.signature(),prompt=q.prompt;StudyDiagram diagram=q.diagram;Arrays.fill(q.answers,"999999");q.choiceInputs=new Rational[]{Rational.of(999999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(v.size(),p.size());assertFalse(p.canTransfer());assertEquals(id,q.id);assertEquals(signature,q.signature());assertEquals(prompt,q.prompt);assertSame(diagram,q.diagram);for(int i=0;i<p.size();i++){assertTrue(p.step(i).accepts(v.get(i).toString()));assertFalse(p.step(i).accepts(v.get(i).add(Rational.ONE).toString()));assertEquals("",p.step(i).after);}}
 @Test public void publicEquationsAndDirectIntegerEnumerationDecideFrames(){Generator g=new Generator(new Random(2098));Set<Integer> counts=new HashSet<>();for(String skill:List.of("sec_quadratic_line_intersections","sec_linear_inequality_system","sec_absolute_linear_inequality")){Set<String> prompts=new HashSet<>();Set<Integer> positions=new HashSet<>();for(int i=0;i<1000;i++){Question q=g.next(skill,List.of(),i%2==0);List<Rational> v=values(q);Rational result=v.get(v.size()-1);if(skill.equals("sec_quadratic_line_intersections")){counts.add(Integer.parseInt(result.toString()));assertNotNull(q.diagram);assertEquals("coordinate",q.diagram.type);assertEquals("Original public vertex and line x coordinates",q.diagram.values[0],q.diagram.values[2],0);assertEquals(v.get(1).decimalText(),Expression.number(String.valueOf(q.diagram.values[1])).decimalText());assertEquals(v.get(2).decimalText(),Expression.number(String.valueOf(q.diagram.values[3])).decimalText());}prompts.add(q.prompt);positions.add(q.correctChoice);assertTrue(new Checker().check(q,List.of(),List.of(result.toString())).correct());assertFalse(new Checker().check(q,List.of(),List.of(result.add(Rational.ONE).toString())).correct());verify(q,v);}assertTrue(skill+prompts.size(),prompts.size()>100);assertTrue(positions.containsAll(Set.of(0,1,2,3)));}assertEquals(Set.of(0,1,2),counts);}
 @Test public void fractionsStrictBoundaryOldGraphAndDraftsRemainExact(){for(Question q:List.of(new Question("sec_quadratic_line_intersections","이차함수 y=x²과 직선 y=0의 교점은 몇 개인가요?","","1"),new Question("sec_linear_inequality_system","x-(-1/2)>1/2이고 x-(-1/2)≤5/2를 모두 만족하는 정수 x는 몇 개인가요?","","2"),new Question("sec_absolute_linear_inequality","|x-(1/2)|≤3/2를 만족하는 정수 x는 몇 개인가요?","","4"))){List<Rational> v=values(q);verify(q,v);HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of(v.get(0).toString()));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));assertTrue(d.teachingVersion.endsWith("relations-v1"));d.entries.set(0,v.get(0).toString());d.stage=1;assertEquals(1,HelpPlan.forQuestion(q).restore(d.copy(),q.id).stage);}}
}
