package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class IsoscelesAngleRelationsTest {
 private List<Rational> values(Question q){Matcher m=Pattern.compile("\\d+(?:\\.\\d+)?(?:/\\d+)?").matcher(q.prompt);assertTrue(m.find());Rational a=Expression.number(m.group()),sum=Rational.of(180).sub(a);return List.of(a,sum,sum.div(Rational.of(2)));}
 @Test public void schematicHasOnlyPublicApexAndKeepsOriginalStoredDiagram(){Generator g=new Generator(new Random(2032));for(int i=0;i<300;i++){Question q=g.next("sec_isosceles_angle",List.of(),false);StudyDiagram old=q.diagram;String signature=q.signature();q.answers[0]="99999";StudyDiagram d=IsoscelesAngleRelations.diagram(q);assertEquals("isoscelesAngles",d.type);assertEquals(1,d.values.length);assertEquals(values(q).get(0).intValue(),d.values[0],0);assertEquals("그림은 비례하지 않음",d.labels[1]);assertTrue(q.prompt.contains(d.labels[0]));assertSame(old,q.diagram);assertEquals(signature,q.signature());}}
 @Test public void publicApexAnglesDetermineAllRelationshipsAndMoreThan100Problems(){Generator g=new Generator(new Random(2030));Set<String> prompts=new HashSet<>(),answers=new HashSet<>();Set<Integer> positions=new HashSet<>();boolean fractional=false,acute=false,obtuse=false;for(int i=0;i<1000;i++){Question q=g.next("sec_isosceles_angle",List.of(),i%2==0);var v=values(q);assertTrue(v.get(0).compareTo(Rational.ZERO)>0&&v.get(0).compareTo(Rational.of(180))<0);assertEquals(Rational.of(180),v.get(2).mul(Rational.of(2)).add(v.get(0)));assertTrue(new Checker().check(q,List.of(),List.of(v.get(2).toString())).correct());fractional|=!v.get(2).isInteger();acute|=v.get(0).compareTo(Rational.of(90))<0;obtuse|=v.get(0).compareTo(Rational.of(90))>0;prompts.add(q.prompt);answers.add(v.get(2).toString());positions.add(q.correctChoice);verify(q,v);}assertTrue(prompts.size()>100);assertTrue(answers.size()>100);assertTrue(positions.containsAll(Set.of(0,1,2,3)));assertTrue(fractional&&acute&&obtuse);}
 @Test public void savedFractionalApexAndOldDraftKeepExactMeaningAndIdentity(){for(String n:List.of("1/2","179.5","125/2")){Question q=new Question("sec_isosceles_angle","꼭지각이 "+n+"°인 이등변삼각형의 한 밑각은?","","99999");verify(q,values(q));}Question q=new Question("sec_isosceles_angle","꼭지각이 35°인 이등변삼각형의 한 밑각은?","","72.5");HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of("145",""));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));d.entries.set(0,"35");d.stage=1;var restored=HelpPlan.forQuestion(q).restore(d.copy(),q.id);assertEquals(1,restored.stage);assertEquals("35",restored.entries.get(0));}
 private void verify(Question q,List<Rational> v){String signature=q.signature();StudyDiagram old=q.diagram;Arrays.fill(q.answers,"99999");q.choiceInputs=new Rational[]{Rational.of(99999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(signature,q.signature());assertSame(old,q.diagram);assertFalse(p.canTransfer());assertEquals(3,p.size());for(int k=0;k<3;k++){assertTrue(p.step(k).accepts(v.get(k).toString()));assertFalse(p.step(k).accepts(v.get(k).add(Rational.ONE).toString()));assertEquals("°",p.step(k).after);}assertEquals("180° − 꼭지각 = ",p.step(1).before);assertEquals("두 밑각의 합 ÷ 2 = ",p.step(2).before);}
}
