package com.gomgomapps.math.core;
import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class LargeWrittenProductsTest {
 private Question make(String id,int a,int b){return LargeWrittenProducts.indexed(id,(a-1)*(id.equals(LargeWrittenProducts.SINGLE)?10:90)+b-(id.equals(LargeWrittenProducts.SINGLE)?0:10));}
 @Test public void everyFirstOperandAndEveryMultiplierBoundaryUsePublicProducts(){Checker c=new Checker();for(String id:List.of(LargeWrittenProducts.SINGLE,LargeWrittenProducts.DOUBLE)){int[] multipliers=id.equals(LargeWrittenProducts.SINGLE)?new int[]{0,1,9}:new int[]{10,11,99};for(int a=1;a<=9999;a++)for(int b:multipliers){Question q=make(id,a,b);assertArrayEquals(new int[]{a,b,a*b},LargeWrittenProducts.read(q));q.answers=new String[]{"poison"};q.expression="poison";assertTrue(c.check(q,List.of(),List.of(""+((long)a*b))).correct());assertEquals(Checker.Status.WRONG_ANSWER,c.check(q,List.of(),List.of(""+(a*b+1))).status);}}for(int b=0;b<=99;b++)for(int a:new int[]{1,9,10,99,100,999,1000,1001,9009,9999}){String id=b<10?LargeWrittenProducts.SINGLE:LargeWrittenProducts.DOUBLE;assertTrue(c.check(make(id,a,b),List.of(),List.of(""+(a*b))).correct());}assertEquals(99990,LargeWrittenProducts.count(LargeWrittenProducts.SINGLE));assertEquals(899910,LargeWrittenProducts.count(LargeWrittenProducts.DOUBLE));}
 @Test public void fullLargeColumnLayoutChecksOnlyWrongLearnerCellAndUsesLearnerFinalRow(){Question q=make(LargeWrittenProducts.DOUBLE,9999,99);q.answers=new String[]{"poison"};VerticalWork.Layout l=VerticalWork.layout(q);assertNotNull(l);assertEquals(6,l.columns);assertEquals(2,l.rows.stream().filter(r->r.id.startsWith("part")).count());assertEquals(1,l.rows.stream().filter(r->r.id.equals("part1")).findFirst().get().shift);VerticalWork.Draft d=new VerticalWork.Draft();d.cells.put("part0:0","0");assertEquals(Set.of("part0:0"),VerticalWork.check(q,d).wrong);d.cells.put("part0:0","1");assertFalse(VerticalWork.check(q,d).error());d.cells.put("mulCarry0:1","8");assertFalse(VerticalWork.check(q,d).error());d.cells.put("mulCarry0:1","7");assertEquals(Set.of("mulCarry0:1"),VerticalWork.check(q,d).wrong);assertNull(VerticalWork.answer(q,d));d.cells.put("mulCarry0:1","8");String answer="989901";for(int i=0;i<answer.length();i++)d.cells.put("answer:"+i,answer.substring(answer.length()-1-i,answer.length()-i));assertEquals(answer,VerticalWork.answer(q,d));assertFalse(VerticalWork.check(q,d).error());}
 @Test public void helpRemainsBlankAndNoTransferAcrossFourDigitOneAndTwoDigitProducts(){for(Question q:List.of(make(LargeWrittenProducts.SINGLE,9009,9),make(LargeWrittenProducts.DOUBLE,9999,99),make(LargeWrittenProducts.SINGLE,1000,0))){q.answers=new String[]{"poison"};HelpPlan h=HelpPlan.forQuestion(q);assertFalse(h.canTransfer());assertTrue(h.restore(null,q.id).entries.stream().allMatch(String::isEmpty));int[] g=LargeWrittenProducts.read(q);assertTrue(h.step(0).accepts(""+g[0]));assertTrue(h.step(1).accepts(""+g[1]));assertTrue(h.step(h.size()-1).accepts(""+((long)g[0]*g[1])));assertTrue(h.size()>10);}}
 @Test public void normalFreshSupplyAndPlacementExcludeOtherGradesAndMalformedPrompts(){Learning.Profile p=new Learning.Profile();GlobalCurriculum.chooseCountry(p,"GB");GlobalCurriculum.choosePack(p,"england-primary-2021-v1");GlobalCurriculum.Pack pack=GlobalCurriculum.pack(p);Generator gen=new Generator(new Random(166));for(String id:List.of(LargeWrittenProducts.SINGLE,LargeWrittenProducts.DOUBLE)){assertTrue(pack.inGrade(id,5));assertFalse(pack.inGrade(id,4));assertFalse(pack.inGrade(id,6));assertFalse(Curriculum.inCurriculum(Catalog.get(id),2022));List<String> history=new ArrayList<>();CurriculumLimits limits=GlobalCurriculum.limits(pack.id,id,5);for(int i=0;i<100;i++){Question q=gen.next(id,history,false,limits);assertNotNull(LargeWrittenProducts.read(q));assertNotNull(VerticalWork.layout(q));assertFalse(history.contains(q.signature()));assertTrue(q.choices.isEmpty());history.add(q.signature());}}Question malformed=make(LargeWrittenProducts.SINGLE,9999,9);malformed.prompt="10000 × 9";assertNull(LargeWrittenProducts.read(malformed));assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(malformed,List.of(),List.of("90000")).status);}
}
