package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class LineCircleRelationsTest {
 private List<Rational> values(Question q){List<Rational> n=new ArrayList<>();Matcher m=Pattern.compile("[+-]?\\d+(?:\\.\\d+)?(?:/\\d+)?").matcher(q.prompt);while(m.find())n.add(Expression.number(m.group()));
  if(q.skillId.equals("sec_circle_equation")){assertEquals(3,n.size());Rational s=n.get(2);return List.of(s,s.sqrt());}
  if(q.skillId.equals("sec_point_line_distance")){assertEquals(4,n.size());Rational a=n.get(0),b=n.get(1),c=n.get(2),u=a.mul(a),v=b.mul(b),s=u.add(v),root=s.sqrt(),absolute=c.compareTo(Rational.ZERO)<0?c.neg():c;return List.of(a,b,c,u,v,s,root,absolute,absolute.div(root));}
  assertEquals(6,n.size());Rational a=n.get(0),b=n.get(1),constant=n.get(2),c=n.get(3),d=n.get(4),constant2=n.get(5),u=a.mul(d),v=c.mul(b),det=u.sub(v),p=a.mul(c),z=b.mul(d),dot=p.add(z);if(det.isZero())assertFalse("Generated parallel lines must be distinct",a.mul(constant2).equals(c.mul(constant))&&b.mul(constant2).equals(d.mul(constant)));Rational e1=a.mul(constant2),e2=c.mul(constant),e=e1.sub(e2),f1=b.mul(constant2),f2=d.mul(constant),ff=f1.sub(f2);return List.of(a,b,c,d,u,v,det,p,z,dot,constant,constant2,e1,e2,e,f1,f2,ff,Rational.of(det.isZero()?1:dot.isZero()?-1:0));
 }
 private void verify(Question q,List<Rational> expected){String id=q.id,sig=q.signature(),prompt=q.prompt;StudyDiagram diagram=q.diagram;Arrays.fill(q.answers,"999999");q.choiceInputs=new Rational[]{Rational.of(999999)};q.givenNumbers.replaceAll((k,x)->"999999");HelpPlan p=HelpPlan.forQuestion(q);assertEquals(expected.size(),p.size());assertFalse(p.canTransfer());assertEquals(id,q.id);assertEquals(sig,q.signature());assertEquals(prompt,q.prompt);assertSame(diagram,q.diagram);for(int i=0;i<p.size();i++){assertTrue(p.step(i).accepts(expected.get(i).toString()));assertFalse(p.step(i).accepts(expected.get(i).add(Rational.ONE).toString()));assertEquals("",p.step(i).after);assertFalse(Pattern.compile("\\d").matcher(p.step(i).before).find());}}
 @Test public void publicEquationsAndSignsDetermineGeneratedSteps(){Generator g=new Generator(new Random(2301));for(String skill:List.of("sec_line_relation","sec_point_line_distance","sec_circle_equation")){Set<String> prompts=new HashSet<>();Set<Integer> positions=new HashSet<>();Set<String> relationships=new HashSet<>();Set<String> coefficientSigns=new HashSet<>();for(int i=0;i<1200;i++){Question q=g.next(skill,List.of(),i%2==0);List<Rational> v=values(q);String result=v.get(v.size()-1).toString();assertTrue(new Checker().check(q,List.of(),List.of(result)).correct());assertFalse(new Checker().check(q,List.of(),List.of(v.get(v.size()-1).add(Rational.ONE).toString())).correct());prompts.add(q.prompt);if(q.correctChoice>=0)positions.add(q.correctChoice);if(skill.equals("sec_line_relation"))relationships.add(result);if(skill.equals("sec_point_line_distance"))coefficientSigns.add(v.get(0).n.signum()+","+v.get(1).n.signum()+","+v.get(2).n.signum());verify(q,v);}assertTrue(skill+prompts.size(),prompts.size()>100);assertEquals(Set.of(0,1,2,3),positions);if(skill.equals("sec_line_relation"))assertEquals(Set.of("1","-1","0"),relationships);if(skill.equals("sec_point_line_distance"))assertEquals(8,coefficientSigns.size());}}
 @Test public void savedFractionsAndZeroDistanceMigrateHelperDraft(){for(Question q:List.of(new Question("sec_line_relation","두 직선 1/2x+(1)y=2, 1x+(2)y=3의 관계를 고르세요.","","1"),new Question("sec_point_line_distance","원점 O와 직선 -3/2x+2y+(0)=0 사이의 거리는?","","0"),new Question("sec_circle_equation","(x-(-1/2))²+(y-(2))²=9/4인 원의 반지름은?","","3/2"))){List<Rational> v=values(q);verify(q,v);HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of(v.get(0).toString()));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));assertTrue(d.teachingVersion.endsWith(q.skillId.equals("sec_line_relation")?"relations-v2":"relations-v1"));d.entries.set(0,v.get(0).toString());d.stage=1;assertEquals(1,HelpPlan.forQuestion(q).restore(d.copy(),q.id).stage);}}
}
