package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class MatrixCalculationRelationsTest {
 private List<Rational> values(Question q){
  List<Rational[]> matrices=new ArrayList<>();Matcher arrays=Pattern.compile("\\[\\[([^]]+)\\], \\[([^]]+)\\]\\]").matcher(q.prompt);
  while(arrays.find()){List<Rational> entries=new ArrayList<>();for(int row=1;row<=2;row++)for(String item:arrays.group(row).split(","))entries.add(Expression.number(item.trim()));assertEquals(4,entries.size());matrices.add(entries.toArray(Rational[]::new));}
  Matcher pos=Pattern.compile("\\(([12]), ?([12])\\) 성분은\\?").matcher(q.prompt);assertTrue(pos.find());int row=Integer.parseInt(pos.group(1)),col=Integer.parseInt(pos.group(2)),index=(row-1)*2+col-1;Rational[] a=matrices.get(0);
  if(q.skillId.equals("sec_matrix_element"))return List.of(Rational.of(row),Rational.of(col),a[index]);
  if(q.skillId.equals("sec_matrix_scalar")){Matcher scalar=Pattern.compile("일 때 ([+-]?\\d+(?:/\\d+)?)A의").matcher(q.prompt);assertTrue(scalar.find());Rational k=Expression.number(scalar.group(1));return List.of(k,a[index],a[index].mul(k));}
  Rational[] b=matrices.get(1);
  if(q.skillId.equals("sec_matrix_add"))return List.of(Rational.of(row),Rational.of(col),a[index],b[index],a[index].add(b[index]));
  if(q.skillId.equals("sec_matrix_sub"))return List.of(Rational.of(row),Rational.of(col),a[index],b[index],b[index].mul(Rational.of(-1)),a[index].sub(b[index]));
  assertEquals(1,row);assertEquals(1,col);List<Rational> products=new ArrayList<>();Rational sum=Rational.ZERO;for(int k=0;k<2;k++){Rational product=a[(row-1)*2+k].mul(b[k*2+col-1]);products.add(product);sum=sum.add(product);}return List.of(a[0],b[0],a[1],b[2],products.get(0),products.get(1),sum);
 }
 private void verify(Question q,List<Rational> v){String id=q.id,sig=q.signature(),prompt=q.prompt;StudyDiagram diagram=q.diagram;Arrays.fill(q.answers,"999999");q.choiceInputs=new Rational[]{Rational.of(999999)};q.givenNumbers.replaceAll((k,x)->"999999");HelpPlan p=HelpPlan.forQuestion(q);assertEquals(v.size(),p.size());assertFalse(p.canTransfer());assertEquals(id,q.id);assertEquals(sig,q.signature());assertEquals(prompt,q.prompt);assertSame(diagram,q.diagram);for(int i=0;i<p.size();i++){assertTrue(p.step(i).accepts(v.get(i).toString()));assertFalse(p.step(i).accepts(v.get(i).add(Rational.ONE).toString()));assertEquals("",p.step(i).after);}}
 @Test public void publicRowsColumnsAndDotProductsDecideEveryGeneratedFrame(){Generator g=new Generator(new Random(2102));Set<String> positionsRead=new HashSet<>();for(String skill:List.of("sec_matrix_element","sec_matrix_add","sec_matrix_sub","sec_matrix_scalar","sec_matrix_product")){Set<String> prompts=new HashSet<>();Set<Integer> choices=new HashSet<>();boolean negative=false,positive=false,zero=false;for(int i=0;i<1000;i++){Question q=g.next(skill,List.of(),i%2==0);List<Rational> v=values(q);if(skill.equals("sec_matrix_element")||skill.equals("sec_matrix_add")||skill.equals("sec_matrix_sub"))positionsRead.add(v.get(0)+","+v.get(1));Rational result=v.get(v.size()-1);negative|=result.compareTo(Rational.ZERO)<0;positive|=result.compareTo(Rational.ZERO)>0;zero|=result.equals(Rational.ZERO);prompts.add(q.prompt);if(q.correctChoice>=0)choices.add(q.correctChoice);assertTrue(new Checker().check(q,List.of(),List.of(result.toString())).correct());assertFalse(new Checker().check(q,List.of(),List.of(result.add(Rational.ONE).toString())).correct());verify(q,v);}assertTrue(skill+prompts.size(),prompts.size()>100);assertEquals(Set.of(0,1,2,3),choices);assertTrue(negative&&positive);if(!skill.equals("sec_matrix_element")&&!skill.equals("sec_matrix_scalar"))assertTrue(skill,zero);}assertEquals(Set.of("1,1","1,2","2,1","2,2"),positionsRead);}
 @Test public void savedFractionEntriesSignsAndDraftVersions(){for(Question q:List.of(new Question("sec_matrix_element","행렬 [[1/2, -3/2], [2, -4]]의 (1, 2) 성분은?","","-3/2"),new Question("sec_matrix_add","A=[[1/2, -2], [3, 4]], B=[[3/2, 5], [6, 7]]일 때 A+B의 (1,1) 성분은?","","2"),new Question("sec_matrix_sub","A=[[1, 2], [3, -1/2]], B=[[4, 5], [6, -3/2]]일 때 A-B의 (2,2) 성분은?","","1"),new Question("sec_matrix_scalar","A=[[1, 2], [0, -3/2]]일 때 -2A의 (2,2) 성분은?","","3"),new Question("sec_matrix_product","A=[[1/2, -2], [3, 4]], B=[[2, 1], [-3/2, 0]]일 때 AB의 (1,1) 성분은?","","4"))){List<Rational> v=values(q);verify(q,v);HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of(v.get(0).toString()));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));assertTrue(d.teachingVersion.endsWith("relations-v1"));d.entries.set(0,v.get(0).toString());d.stage=1;assertEquals(1,HelpPlan.forQuestion(q).restore(d.copy(),q.id).stage);}}
}
