package com.gomgomapps.math.core;
import org.junit.Test;import static org.junit.Assert.*;import java.util.*;import java.util.regex.*;import java.io.*;
public class MeasureUnitRelationsTest {
 private final Map<String,Long> size=Map.of("mm",1L,"cm",10L,"m",1000L,"km",1000000L,"mL",1L,"L",1000L,"g",1L,"kg",1000L,"t",1000000L);
 private List<Long> nums(String s){List<Long> out=new ArrayList<>();Matcher m=Pattern.compile("[0-9]+").matcher(s);while(m.find())out.add(Long.parseLong(m.group()));return out;}
 private List<String> units(String s){List<String> out=new ArrayList<>();Matcher m=Pattern.compile("[0-9]+(mm|cm|km|mL|L|kg|g|t|m)").matcher(s);while(m.find())out.add(m.group(1));if(s.contains("□")){Matcher target=Pattern.compile("□(mm|cm|km|mL|L|kg|g|t|m)").matcher(s);assertTrue(target.find());out.add(target.group(1));}else if(s.contains("몇 ")){Matcher target=Pattern.compile("몇 (mm|cm|km|mL|L|kg|g|t|m)").matcher(s);assertTrue(target.find());out.add(target.group(1));}return out;}
 private void verify(Question q){String signature=q.signature(),expression=q.expression;String[] answers=q.answers.clone();List<Long> n=nums(q.prompt);List<String> u=units(q.prompt);String target=u.get(u.size()-1);boolean arithmetic=q.prompt.contains(" + ")||q.prompt.contains(" − ")||q.prompt.contains(" - ");boolean mixed=n.size()==2&&!arithmetic;long source=size.get(u.get(0)),dest=size.get(target),factor=source>=dest?source/dest:dest/source;long value=n.get(0)*source;if(n.size()==2)value+=(q.prompt.contains("−")||q.prompt.contains(" - ")?-1:1)*n.get(1)*size.get(u.get(1));long expected=value/dest;assertEquals(0,value%dest);assertEquals(q.prompt,""+expected,q.answers[0]);HelpPlan p=HelpPlan.forQuestion(q);assertNotNull(q.prompt,p);var frames=MeasureUnitRelations.frames(q);assertEquals(frames.size(),p.size());assertFalse(p.canTransfer());Map<String,Long> quantities=new HashMap<>();quantities.put("첫 수량("+u.get(0)+")",n.get(0));if(n.size()==2)quantities.put("둘째 수량("+u.get(1)+")",n.get(1));quantities.put("단위 관계("+u.get(0)+"→"+target+")",factor);quantities.put("바꾼 수량("+target+")",n.get(0)*source/dest);quantities.put("전체 수량("+target+")",expected);quantities.put("합한 수량("+u.get(0)+")",n.stream().mapToLong(Long::longValue).sum());if(n.size()==2)quantities.put("남은 수량("+u.get(0)+")",n.get(0)-n.get(1));
  for(int i=0;i<frames.size();i++){var f=frames.get(i);assertEquals(f.result(),""+quantities.get(f.result()),f.expected());assertTrue(p.step(i).accepts(f.expected()));assertFalse(p.step(i).accepts(""));assertFalse(p.step(i).accepts(""+(Long.parseLong(f.expected())+1)));assertFalse(f.label(),Pattern.compile("[0-9]").matcher(f.label()).find());for(int prior:f.prior())assertTrue(prior>=0&&prior<i);}
  assertTrue(new Checker().check(q,List.of(),List.of(""+expected)).correct());assertEquals(signature,q.signature());assertArrayEquals(answers,q.answers);q.expression="99999999";q.answers=new String[]{"99999999"};q.studyGuide=new StudyGuide().step("old","999 = ","999","999");HelpPlan.forQuestion(q);assertEquals("measure-unit-relations-v1",q.studyGuide.teachingVersion);assertEquals(frames.size(),q.studyGuide.frames.size());q.answers=answers;q.expression=expression;
 }
 @Test public void allTwelveUnitsVaryWithoutChangingUnitScaleOrOriginalAnswers(){Generator g=new Generator(new Random(99081));for(String id:MeasureUnitRelations.IDS){Set<String> seen=new HashSet<>();for(int i=0;i<1200;i++){Question q=g.next(id,List.of(),i%2==0);seen.add(q.prompt);verify(q);}assertTrue(id+" has only "+seen.size()+" public forms",seen.size()>=100);}}
 @Test public void sourceBoundsZeroAndInverseConversionsStayIntegral(){Generator g=new Generator(new Random(99082));boolean zero=false,addition=false,subtraction=false,inverse=false;for(String id:List.of("el_length_m_cm","el_length_km_m","el_capacity_l_ml","el_mass_t_kg"))for(int i=0;i<500;i++){Question q=g.next(id,List.of(),false);verify(q);List<Long> n=nums(q.prompt);List<String> u=units(q.prompt);long maximum=id.equals("el_mass_t_kg")?8:20;long scale=id.equals("el_length_m_cm")?100:1000;for(int j=0;j<n.size();j++){boolean small=List.of("cm","mL","kg").contains(u.get(j))||id.equals("el_length_km_m")&&u.get(j).equals("m");assertTrue(n.get(j)<=(small?maximum*scale:maximum));}zero|=q.answers[0].equals("0");addition|=q.prompt.contains(" + ");subtraction|=q.prompt.contains(" − ");inverse|=q.prompt.contains("□")&&q.prompt.endsWith(id.equals("el_mass_t_kg")?"t":id.equals("el_capacity_l_ml")?"L":id.equals("el_length_m_cm")?"m":"km");}assertTrue(zero&&addition&&subtraction&&inverse);}
 @Test public void obsoleteGuidesAndDraftsResetWhileNewPartialValuesRestore()throws Exception{Question q=new Generator(new Random(99083)).next("el_mass_mixed",List.of(),false);HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft old=new HelpPlan.Draft();old.questionId=q.id;old.stage=1;old.entries.add("999");assertEquals(0,p.restore(old,q.id).stage);HelpPlan.Draft d=p.restore(null,q.id);for(int i=0;i<2;i++){d.entries.set(i,q.studyGuide.frames.get(i).expected);d.stage++;d.entries.add("");}ByteArrayOutputStream b=new ByteArrayOutputStream();new ObjectOutputStream(b).writeObject(d);HelpPlan.Draft restored=(HelpPlan.Draft)new ObjectInputStream(new ByteArrayInputStream(b.toByteArray())).readObject();assertEquals(2,p.restore(restored,q.id).stage);assertNull(MeasureUnitRelations.read(new Question("el_capacity_l_ml","3kg는 몇 g인가요?","","0")));}
}
