package com.gomgomapps.math.core;
import org.junit.Test;import static org.junit.Assert.*;import java.util.*;
public class MentalPlaceCalculationsTest {
 @Test public void gradeRangesFreshPublicArithmeticAndEveryPlace(){for(int grade:new int[]{2,3})for(String id:List.of(MentalPlaceCalculations.ADD,MentalPlaceCalculations.SUB)){Generator g=new Generator(new Random(118));var limits=GlobalCurriculum.limits("england-primary-2021-v1",id,grade);List<String> recent=new ArrayList<>();Set<Integer> units=new HashSet<>();for(int i=0;i<100;i++){Question q=g.next(id,recent,true,limits);assertFalse(recent.contains(q.signature()));recent.add(q.signature());String[] p=q.prompt.split(" ");int a=Integer.parseInt(p[0]),b=Integer.parseInt(p[2]),u=1,t=b;while(t%10==0){t/=10;u*=10;}units.add(u);assertTrue(t>=1&&t<=9);assertTrue(a>=(grade==2?10:100)&&a<=(grade==2?99:999));assertTrue(b<=(grade==2?90:900));int result=id.equals(MentalPlaceCalculations.ADD)?a+b:a-b;assertTrue(result>=0);q.answers=new String[]{"poison"};q.expression="wrong";Checker c=new Checker();assertTrue(c.check(q,List.of(),List.of(""+result)).correct());assertEquals(0,c.check(q,List.of(),List.of(""+(result+1))).index);assertTrue(q.choices.isEmpty());HelpPlan h=HelpPlan.forQuestion(q);assertFalse(h.canTransfer());for(int j=0;j<h.size();j++)assertFalse(h.step(j).before.matches(".*\\d.*"));}assertEquals(grade==2?Set.of(1,10):Set.of(1,10,100),units);}}
 private void frames(String id,int a,int b,int...values){Question q=MentalPlaceCalculations.make(id,a,b);q.answers=new String[]{"poison"};q.expression="wrong";HelpPlan h=HelpPlan.forQuestion(q);assertEquals(values.length,h.size());assertFalse(h.canTransfer());assertEquals(MentalPlaceCalculations.VERSION,q.studyGuide.teachingVersion);for(int i=0;i<values.length;i++){assertTrue(h.step(i).instruction,h.step(i).accepts(""+values[i]));assertFalse(h.step(i).accepts(""+(values[i]+1)));assertTrue(values[i]>=0);}}
 @Test public void regroupBridgeAndUnchangedLowerPlacesAreTaughtWithoutNegatives(){frames(MentalPlaceCalculations.ADD,47,8,10,4,40,7,3,50,5,55);frames(MentalPlaceCalculations.SUB,302,5,10,30,300,2,3,300,297);frames(MentalPlaceCalculations.ADD,367,50,10,36,360,7,5,41,410,417);frames(MentalPlaceCalculations.SUB,302,50,10,30,300,2,5,25,250,252);frames(MentalPlaceCalculations.ADD,967,500,100,9,900,67,5,14,1400,1467);frames(MentalPlaceCalculations.SUB,302,200,100,3,300,2,2,1,100,102);frames(MentalPlaceCalculations.ADD,47,2,10,4,40,7,9,49);frames(MentalPlaceCalculations.SUB,47,3,10,4,40,7,4,44);frames(MentalPlaceCalculations.SUB,300,1,10,30,300,0,1,300,299);frames(MentalPlaceCalculations.SUB,100,100,100,1,100,0,1,0,0,0);
  Checker c=new Checker();for(String id:List.of(MentalPlaceCalculations.ADD,MentalPlaceCalculations.SUB)){Question q=MentalPlaceCalculations.make(id,999,900);assertTrue(c.check(q,List.of(),List.of(id.equals(MentalPlaceCalculations.ADD)?"1899":"99")).correct());assertEquals(Checker.Status.INPUT_NEEDED,c.check(q,List.of(),List.of("9+9")).status);q.prompt="999 + 91";assertEquals(Checker.Status.INPUT_NEEDED,c.check(q,List.of(),List.of("1090")).status);}assertNull(MentalPlaceCalculations.read(new Question(MentalPlaceCalculations.SUB,"10 - 20","","-10")));assertNull(MentalPlaceCalculations.read(new Question(MentalPlaceCalculations.ADD,"10 + 0","","10")));
 }
}
