package com.gomgomapps.math.core;
import java.math.*;import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class PercentageNotationTest {
 @Test public void everyWholePercentageKeepsTheRequestedRepresentation(){Checker check=new Checker();for(int p=0;p<=100;p++){
  Question f=PercentageNotation.make(PercentageNotation.FRACTION,p),d=PercentageNotation.make(PercentageNotation.DECIMAL,p);assertTrue(check.check(f,List.of(),List.of(p+"/100")).correct());assertTrue(FractionInput.defaultFraction(f));assertFalse(check.check(f,List.of(),List.of((p*2)+"/200")).correct());assertEquals(2,FractionInput.errorPart(f,(p*2)+"/200"));assertFalse(check.check(f,List.of(),List.of((p+1)+"/100")).correct());assertEquals(1,FractionInput.errorPart(f,(p+1)+"/100"));String value=new BigDecimal(p).divide(new BigDecimal("100")).toPlainString();assertTrue(check.check(d,List.of(),List.of(value)).correct());assertFalse(check.check(d,List.of(),List.of(p+"/100")).correct());assertFalse(check.check(d,List.of(),List.of(new BigDecimal(value).add(new BigDecimal("0.01")).toPlainString())).correct());assertEquals("",f.expression);assertFalse(f.stepSupport);
 }}
 @Test public void hiddenAnswerCannotSupplyTheMeaningOrStudentFields(){for(String id:List.of(PercentageNotation.FRACTION,PercentageNotation.DECIMAL)){Question original=PercentageNotation.make(id,37),q=new Question(id,original.prompt,"poison","999");HelpPlan h=HelpPlan.forQuestion(q);assertFalse(h.canTransfer());assertEquals(id.equals(PercentageNotation.FRACTION)?3:4,h.size());assertTrue(h.step(0).accepts("100"));assertFalse(h.step(0).accepts("10"));assertTrue(h.step(1).accepts("100"));assertTrue(h.step(2).accepts("37"));if(h.size()==4){assertTrue(h.step(3).accepts("0.37"));assertFalse(h.step(3).accepts("37/100"));}}}
 @Test public void all101ConditionsBeforeRepetitionAndOnlyReviewedPlacement(){var pack=GlobalCurriculum.packs("GB").stream().filter(p->p.id.equals("england-primary-2021-v1")).findFirst().orElseThrow();for(String id:List.of(PercentageNotation.FRACTION,PercentageNotation.DECIMAL)){assertTrue(pack.inGrade(id,5));assertFalse(pack.inGrade(id,4));assertFalse(Curriculum.inCurriculum(Catalog.get(id),2022));List<String> recent=new ArrayList<>();Set<Integer> seen=new HashSet<>();Generator generator=new Generator(new Random(87));var limits=GlobalCurriculum.limits(pack.id,id,5);for(int i=0;i<101;i++){Question q=generator.next(id,recent,true,limits);assertTrue(q.choices.isEmpty());assertFalse(recent.contains(q.signature()));recent.add(q.signature());seen.add(PercentageNotation.read(q));}assertEquals(101,seen.size());assertTrue(seen.contains(0));assertTrue(seen.contains(100));assertTrue(recent.contains(generator.next(id,recent,true,limits).signature()));}}
}
