package com.gomgomapps.math.core;
import org.junit.Test;import static org.junit.Assert.*;import java.util.*;import java.util.regex.*;import java.io.*;
public class PerimeterBoundaryRelationsTest {
 private static List<Integer> sides(String prompt){List<Integer> a=new ArrayList<>();Matcher m=Pattern.compile("(\\([0-9]+ [+−-] [0-9]+\\)|[0-9]+)cm").matcher(prompt);while(m.find()){Matcher digits=Pattern.compile("[0-9]+").matcher(m.group(1));assertTrue(digits.find());int first=Integer.parseInt(digits.group());if(digits.find()){int second=Integer.parseInt(digits.group());assertTrue(first>=1&&first<=20&&second>=1&&second<=20);a.add(m.group(1).contains(" + ")?first+second:first-second);}else a.add(first);}return a;}
 @Test public void publicPerimetersHaveVarietyWithoutLeakingKeys(){Generator g=new Generator(new Random(100101));for(String id:PerimeterBoundaryRelations.IDS){Set<String> prompts=new HashSet<>();for(int i=0;i<1600;i++){Question q=g.next(id,List.of(),i%2==0);var lengths=sides(q.prompt);int answer=id.equals("el_rhombus_perimeter")?lengths.get(0)*4:lengths.stream().mapToInt(Integer::intValue).sum();assertEquals(""+answer,q.answers[0]);prompts.add(q.prompt);String sig=q.signature();String[] answers=q.answers.clone();var choices=new ArrayList<>(q.choices);HelpPlan p=HelpPlan.forQuestion(q);var frames=PerimeterBoundaryRelations.frames(q);assertFalse(frames.isEmpty());assertFalse(p.canTransfer());HelpPlan.Draft d=p.restore(null,q.id);for(int k=0;k<p.size();k++){var f=frames.get(k);assertTrue(p.step(k).accepts(f.expected()));assertFalse(p.step(k).accepts(""));assertFalse(p.step(k).accepts(""+(Integer.parseInt(f.expected())+1)));assertTrue(f.label(),!f.label().matches(".*[0-9].*")||f.label().equals("마름모의 한 변 × 4 = "));d.entries.set(k,f.expected());d.stage++;d.entries.add("");}assertEquals(""+answer,p.enteredAnswer(d));assertEquals(sig,q.signature());assertArrayEquals(answers,q.answers);assertEquals(choices,q.choices);q.answers=new String[]{"999"};q.expression="999+1";q.studyGuide=new StudyGuide().step("old","999 = ","","999");p=HelpPlan.forQuestion(q);assertFalse(p.canTransfer());assertEquals(""+answer,p.enteredAnswer(d));}assertTrue(id+" "+prompts.size(),prompts.size()>=100);}}
 @Test public void originalValidShapesAndAllSideBoundsAreRetained(){Generator g=new Generator(new Random(100102));for(String id:PerimeterBoundaryRelations.IDS){boolean pure=false,add=false,sub=false;Set<Integer> firstSides=new HashSet<>(),scales=new HashSet<>();for(int i=0;i<1600;i++){Question q=g.next(id,List.of(),false);var a=sides(q.prompt);assertTrue(a.get(0)>=2&&a.get(0)<=20);firstSides.add(a.get(0));pure|=!q.prompt.contains("(");add|=q.prompt.contains(" + ");sub|=q.prompt.contains(" − ");if(a.size()==4){int scale=a.get(1)/3;scales.add(scale);assertTrue(scale>=1&&scale<=4);assertEquals(3*scale,(int)a.get(1));assertEquals(a.get(0)+4*scale,(int)a.get(2));assertEquals(5*scale,(int)a.get(3));assertEquals((long)a.get(1)*a.get(1)+(long)(a.get(2)-a.get(0))*(a.get(2)-a.get(0)),(long)a.get(3)*a.get(3));}}assertTrue(pure&&add&&sub);assertEquals(19,firstSides.size());if(id.equals("el_trapezoid_perimeter"))assertEquals(Set.of(1,2,3,4),scales);}
 for(String prompt:List.of("한 변의 길이가 (1 − 2)cm인 마름모의 둘레는?","한 변의 길이가 21cm인 마름모의 둘레는?"))assertTrue(PerimeterBoundaryRelations.frames(new Question("el_rhombus_perimeter",prompt,"","0")).isEmpty());assertTrue(PerimeterBoundaryRelations.frames(new Question("el_trapezoid_perimeter","네 변의 길이가 5cm, 3cm, 9cm, 6cm인 사다리꼴의 둘레는?","","0")).isEmpty());}
 @Test public void oldDraftResetsAndCheckedPartialRestores()throws Exception{for(String id:PerimeterBoundaryRelations.IDS){Question q=new Generator(new Random(100103)).next(id,List.of(),false);q.studyGuide=new StudyGuide().step("old","29 = ","","29");HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft old=new HelpPlan.Draft();old.questionId=q.id;old.stage=1;old.entries.add("29");assertEquals(0,p.restore(old,q.id).stage);HelpPlan.Draft d=p.restore(null,q.id);d.entries.set(0,q.studyGuide.frames.get(0).expected);d.stage=1;d.entries.add("");ByteArrayOutputStream b=new ByteArrayOutputStream();new ObjectOutputStream(b).writeObject(d);HelpPlan.Draft loaded=(HelpPlan.Draft)new ObjectInputStream(new ByteArrayInputStream(b.toByteArray())).readObject();assertEquals(1,p.restore(loaded,q.id).stage);assertEquals(d.entries.get(0),p.restore(loaded,q.id).entries.get(0));}}
}
