package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class PolynomialRootRelationsTest {
 private List<Rational> values(Question q){
  String n="[+-]?\\d+(?:\\.\\d+)?(?:/\\d+)?";Matcher m;
  if(q.skillId.equals("sec_factor_theorem")){
   m=Pattern.compile("P\\(x\\)=x²\\+\\(("+n+")\\)x\\+\\(("+n+")\\)일 때 x-\\(("+n+")\\)가 P\\(x\\)의 인수인지 고르세요\\.").matcher(q.prompt);assertTrue(m.matches());Rational l=Expression.number(m.group(1)),c=Expression.number(m.group(2)),t=Expression.number(m.group(3)),sq=t.mul(t),product=l.mul(t),value=sq.add(product).add(c);return List.of(t,l,c,sq,product,value,value.equals(Rational.ZERO)?Rational.ONE:Rational.ZERO);
  }
  if(q.skillId.equals("sec_cubic_equation")){m=Pattern.compile("(?:("+n+")×)?\\(x-\\(("+n+")\\)\\)³=0을 만족하는 x는\\?").matcher(q.prompt);assertTrue(m.matches());Rational k=m.group(1)==null?Rational.ONE:Expression.number(m.group(1)),a=Expression.number(m.group(2));assertNotEquals(Rational.ZERO,k);assertEquals(Rational.ZERO,k.mul(a.sub(a)).mul(a.sub(a)).mul(a.sub(a)));return List.of(k,a,a);}
  m=Pattern.compile("x⁴(?:\\+\\(("+n+")\\))?=("+n+")의 양의 해는\\?").matcher(q.prompt);assertTrue(m.matches());Rational b=m.group(1)==null?Rational.ZERO:Expression.number(m.group(1)),y=Expression.number(m.group(2)),power=y.sub(b);long numerator=integerRoot(power.n.longValueExact()),denominator=integerRoot(power.d.longValueExact());Rational x=Rational.of(numerator,denominator),sq=x.mul(x);assertEquals(y,sq.mul(sq).add(b));assertTrue(x.compareTo(Rational.ZERO)>0);return List.of(b,y,power,sq,x);
 }
 private long integerRoot(long v){for(long x=0;x<=100;x++)if(x*x*x*x==v)return x;throw new AssertionError("No exact fourth root: "+v);}
 private void verify(Question q,List<Rational> values){String id=q.id,signature=q.signature(),prompt=q.prompt;StudyDiagram diagram=q.diagram;Arrays.fill(q.answers,"999999");q.choiceInputs=new Rational[]{Rational.of(999999)};HelpPlan p=HelpPlan.forQuestion(q);assertFalse(p.canTransfer());assertEquals(values.size(),p.size());assertEquals(id,q.id);assertEquals(signature,q.signature());assertEquals(prompt,q.prompt);assertSame(diagram,q.diagram);for(int i=0;i<p.size();i++){assertTrue(p.step(i).accepts(values.get(i).toString()));assertFalse(p.step(i).accepts(values.get(i).add(Rational.ONE).toString()));assertEquals("",p.step(i).after);assertFalse(p.step(i).before.matches(".*[0-9].*"));}if(q.skillId.equals("sec_factor_theorem"))assertEquals(Set.of("0","1"),p.step(6).options.keySet());}
 @Test public void publicEquationsDecideAllFramesAndSupplyOver100Prompts(){Generator g=new Generator(new Random(2094));for(String skill:List.of("sec_factor_theorem","sec_cubic_equation","sec_quartic_equation")){Set<String> prompts=new HashSet<>();Set<Integer> positions=new HashSet<>();boolean negative=false,positive=false,zero=false;for(int i=0;i<1000;i++){Question q=g.next(skill,List.of(),i%2==0);List<Rational> v=values(q);Rational result=v.get(v.size()-1);prompts.add(q.prompt);positions.add(q.correctChoice);negative|=v.stream().anyMatch(x->x.compareTo(Rational.ZERO)<0);positive|=v.stream().anyMatch(x->x.compareTo(Rational.ZERO)>0);zero|=v.stream().anyMatch(Rational.ZERO::equals);assertTrue(new Checker().check(q,List.of(),List.of(result.toString())).correct());assertFalse(new Checker().check(q,List.of(),List.of(result.add(Rational.ONE).toString())).correct());verify(q,v);}assertTrue(skill+prompts.size(),prompts.size()>100);assertTrue(negative&&positive);if(skill.equals("sec_factor_theorem"))assertTrue(zero);else assertTrue(positions.containsAll(Set.of(0,1,2,3)));}}
 @Test public void oldPublicEquationsFractionsAndVersionedDraftsRemainExact(){for(Question q:List.of(new Question("sec_cubic_equation","(x-(-1/2))³=0을 만족하는 x는?","","-1/2"),new Question("sec_quartic_equation","x⁴=1/16의 양의 해는?","","1/2"),new Question("sec_factor_theorem","P(x)=x²+(1/2)x+(-1/2)일 때 x-(1/2)가 P(x)의 인수인지 고르세요.","","1"))){List<Rational> v=values(q);verify(q,v);HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of(v.get(0).toString()));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));assertTrue(d.teachingVersion.endsWith("relations-v1"));d.entries.set(0,v.get(0).toString());d.stage=1;HelpPlan.Draft restored=HelpPlan.forQuestion(q).restore(d.copy(),q.id);assertEquals(1,restored.stage);assertEquals(v.get(0).toString(),restored.entries.get(0));}}
}
