package com.gomgomapps.math.core;
import org.junit.Test;import static org.junit.Assert.*;import java.util.*;import java.util.regex.*;
public class PopulationDensityTest {
 private Rational quantity(String raw,String key,String unit){Matcher m=Pattern.compile(Pattern.quote(key)+"([0-9.]+)"+Pattern.quote(unit)).matcher(raw);assertTrue(raw,m.find());return Rational.decimal(m.group(1));}
 @Test public void threeHundredDistinctPublicProblemsHaveWholePopulationsAndExactHelp(){for(var skill:PopulationDensity.SKILLS){Generator g=new Generator(new Random(71));Set<String> seen=new HashSet<>();Set<Integer> positions=new HashSet<>();boolean fractional=false,whole=false;
  for(int i=0;i<100;i++){Question q=g.next(skill.id,seen,i%2==0);assertTrue(seen.add(q.signature()));String row=q.prompt.split("\n")[1];Rational answer,operand,p,a,d;
   if(skill.id.equals("populationDensity")){p=quantity(row,"인구: ","명");a=quantity(row,"면적: "," km²");d=p.div(a);answer=d;operand=a;}
   else if(skill.id.equals("populationFromDensity")){a=quantity(row,"면적: "," km²");d=quantity(row,"인구밀도: ","명/km²");p=a.mul(d);answer=p;operand=a;}
   else{p=quantity(row,"인구: ","명");d=quantity(row,"인구밀도: ","명/km²");a=p.div(d);answer=a;operand=d;}
   assertTrue(p.isInteger());assertTrue(p.compareTo(Rational.ZERO)>0&&a.compareTo(Rational.ZERO)>0&&d.compareTo(Rational.ZERO)>0);assertEquals(answer,Expression.number(q.answers[0]));assertEquals(operand,Expression.number(q.studyGuide.frames.get(0).expected));assertEquals(answer,Expression.number(q.studyGuide.frames.get(1).expected));assertFalse(HelpPlan.forQuestion(q).canTransfer());fractional|=!a.isInteger()||!d.isInteger();whole|=a.isInteger()&&d.isInteger();assertTrue(new Checker().check(q,List.of(),List.of(answer.toString())).correct());assertFalse(new Checker().check(q,List.of(),List.of(answer.add(Rational.ONE).toString())).correct());
   if(!q.choices.isEmpty()){assertEquals(4,new HashSet<>(q.choices).size());assertEquals(answer,Expression.number(q.choices.get(q.correctChoice)));positions.add(q.correctChoice);for(String option:q.choices){Rational v=Expression.number(option);assertTrue(v.compareTo(Rational.ZERO)>0);assertEquals(answer.isInteger(),v.isInteger());}}
  }assertTrue(fractional&&whole);assertEquals(Set.of(0,1,2,3),positions);
 }}
 @Test public void reusedSpeedUnitContextsAreIndependentlySolved(){Generator g=new Generator(new Random(72));Set<String> seen=new HashSet<>(),units=new HashSet<>();for(int i=0;i<100;i++){Question q=g.next("speedValue",seen,false);assertTrue(seen.add(q.signature()));Matcher m=Pattern.compile("거리 ([0-9.]+)(km|m) · 시간 ([0-9.]+)(분|시간|초)").matcher(q.prompt);assertTrue(m.find());Rational distance=Rational.decimal(m.group(1)),given=Rational.decimal(m.group(3)),time=m.group(4).equals("분")?given.div(Rational.of(60)):given;assertEquals(distance.div(time),Expression.number(q.answers[0]));assertEquals(time,Expression.number(q.studyGuide.frames.get(0).expected));units.add(m.group(4));}assertEquals(Set.of("분","시간","초"),units);}
 @Test public void averageSpeedUsesTotalsRatherThanTheMeanOfSegmentSpeeds(){Generator g=new Generator(new Random(74));Set<String> seen=new HashSet<>();for(int i=0;i<100;i++){Question q=g.next("averageSpeed",seen,false);assertTrue(seen.add(q.signature()));Matcher m=Pattern.compile("구간[12]: ([0-9.]+)km · ([0-9.]+)시간").matcher(q.prompt);assertTrue(m.find());Rational d1=Rational.decimal(m.group(1)),t1=Rational.decimal(m.group(2));assertTrue(m.find());Rational d2=Rational.decimal(m.group(1)),t2=Rational.decimal(m.group(2));assertEquals(d1.add(d2).div(t1.add(t2)),Expression.number(q.answers[0]));assertEquals(d1.add(d2),Expression.number(q.studyGuide.frames.get(0).expected));assertEquals(t1.add(t2),Expression.number(q.studyGuide.frames.get(1).expected));}}
 @Test public void brazilNinthGradeRatiosUseMappedSkillsButPriorGradeDiagnosisExcludesNewTopics(){Learning.Profile p=new Learning.Profile();GlobalCurriculum.chooseCountry(p,"BR");GlobalCurriculum.choosePack(p,"br-bncc-fundamental-2017-v1");p.grade=9;for(String id:List.of("populationDensity","populationFromDensity","areaFromPopulation","speedValue","averageSpeed")){assertTrue(GlobalCurriculum.pack(p).inGrade(id,9));assertFalse(GlobalCurriculum.scope(p).stream().anyMatch(x->x.id.equals(id)));}}
}
