package com.gomgomapps.math.core;
import org.junit.Test;import static org.junit.Assert.*;import java.util.*;
public class PrimaryFormulaContextTest {
 @Test public void allStoriesRequireGeneralFormulaAndCorrectSpecifiedValue(){Checker c=new Checker();int count=0;assertFalse(PrimaryFormulaContext.TEMPLATE.matches(".*[0-9].*"));
  for(int story=0;story<2;story++)for(int a=1;a<=12;a++)for(int b=0;b<=12;b++)for(int x=0;x<=20;x++){count++;Question q=PrimaryFormulaContext.create(story,a,b,x);String expr=b+"+x*"+a,value=""+(a*x+b);assertTrue(c.check(q,List.of(),List.of(expr,value)).correct());assertEquals(0,c.check(q,List.of(),List.of((a+1)+"x+"+b,value)).index);assertEquals(1,c.check(q,List.of(),List.of(expr,""+(a*x+b+1))).index);assertFalse(c.check(q,List.of(),List.of(value,value)).correct());q.answers=new String[]{"999","999"};assertTrue(c.check(q,List.of(),List.of(expr,value)).correct());PrimaryFormulaContext.attach(q);assertEquals(List.of(""+a,""+b,""+x,""+(a*x),value),q.studyGuide.frames.stream().map(f->f.expected).toList());for(var f:q.studyGuide.frames){assertFalse(f.before.matches(".*[0-9].*"));assertEquals("",f.after);}assertFalse(HelpPlan.forQuestion(q).canTransfer());
  }assertEquals(6552,count);
 }
 @Test public void malformedFinalInputsDoNotReferToWorkRows(){Question q=PrimaryFormulaContext.create(0,3,2,4);Checker c=new Checker();for(var answers:List.of(List.of("","14"),List.of("x+","14"),List.of("3x+2",""),List.of("3x+2","x"),List.of("3x+2","12+2"))){var result=c.check(q,List.of(),answers);assertEquals(Checker.Status.INPUT_NEEDED,result.status);assertEquals(-1,result.index);}assertTrue(c.check(q,List.of(""),List.of("3x+2","14")).correct());}
 @Test public void hundredFreshMappedConditionsAndTeachingDraftRestore(){Generator gen=new Generator(new Random(109));Set<String> seen=new LinkedHashSet<>();for(int i=0;i<100;i++){Question q=gen.next(PrimaryFormulaContext.ID,seen,false);assertTrue(seen.add(q.signature()));assertTrue(q.choices.isEmpty());assertFalse(q.stepSupport);}Learning.Profile p=new Learning.Profile();GlobalCurriculum.chooseCountry(p,"GB");GlobalCurriculum.choosePack(p,"england-primary-2021-v1");var pack=GlobalCurriculum.pack(p);assertTrue(pack.inGrade(PrimaryFormulaContext.ID,6));assertFalse(pack.inGrade(PrimaryFormulaContext.ID,5));Question q=PrimaryFormulaContext.create(1,3,2,4);HelpPlan plan=HelpPlan.forQuestion(q);HelpPlan.Draft draft=new HelpPlan.Draft();draft.questionId=q.signature();draft.teachingVersion="primary-formula-context-v1";draft.stage=3;draft.entries=new ArrayList<>(List.of("3","2","4","13",""));assertEquals(draft.entries,plan.restore(draft,q.signature()).entries);assertTrue(plan.step(3).accepts("12"));}
}
