package com.gomgomapps.math.core;
import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class PrimeRecallTest {
 private List<String> expected(int max){List<String> r=new ArrayList<>();for(int n=2;n<=max;n++){int divisors=0;for(int d=1;d<=n;d++)if(n%d==0)divisors++;if(divisors==2)r.add(""+n);}return r;}
 @Test public void all18BoundsCheckPublicListsWithoutReadingKeys(){Checker c=new Checker();Set<String> seen=new HashSet<>();for(int max=2;max<=19;max++){Question q=PrimeRecall.make(max);assertTrue(seen.add(q.signature()));q.answers=new String[]{"poison"};List<String> answer=expected(max);assertTrue(c.check(q,List.of(),answer).correct());List<String> wrong=new ArrayList<>(answer);wrong.set(0,"1");assertEquals(0,c.check(q,List.of(),wrong).index);if(answer.size()>1){Checker.Result missing=c.check(q,List.of(),answer.subList(0,answer.size()-1));assertEquals(Checker.Status.WRONG_ANSWER,missing.status);assertEquals(-1,missing.index);}}assertEquals(List.of("2","3","5","7","11","13","17","19"),expected(19));}
 @Test public void duplicateOrderBlankCompositeAndOutOfRangeAreDistinct(){Checker c=new Checker();Question q=PrimeRecall.make(19);assertEquals(1,c.check(q,List.of(),List.of("2","2")).index);assertEquals(1,c.check(q,List.of(),List.of("3","2")).index);assertEquals(Checker.Status.INPUT_NEEDED,c.check(q,List.of(),List.of("2","")).status);assertEquals(1,c.check(q,List.of(),List.of("2","4")).index);assertEquals(0,c.check(q,List.of(),List.of("23")).index);assertNull(PrimeVocabulary.read(q));assertEquals(-1,PrimeRecall.read(new Question(PrimeRecall.ID,"2 이상 20 이하의 소수를 모두 쓰세요.\n작은 수부터 쓰세요.","","2")));}
 @Test public void helpNeverRevealsListCardinalityOrMembers(){for(int max=2;max<=19;max++){Question q=PrimeRecall.make(max);q.answers=new String[]{"poison"};HelpPlan h=HelpPlan.forQuestion(q);assertEquals(1,h.size());assertFalse(h.canTransfer());assertEquals(List.of(""),h.restore(null,q.id).entries);assertTrue(h.step(0).accepts("2"));assertFalse(h.step(0).accepts("8"));assertFalse(h.step(0).before.matches(".*[0-9].*"));}}
 @Test public void normalSupplyExhausts18RealConditionsAndKeepsYear5Scope(){Learning.Profile p=new Learning.Profile();GlobalCurriculum.chooseCountry(p,"GB");GlobalCurriculum.choosePack(p,"england-primary-2021-v1");GlobalCurriculum.Pack pack=GlobalCurriculum.pack(p);assertTrue(pack.inGrade(PrimeRecall.ID,5));assertFalse(pack.inGrade(PrimeRecall.ID,4));assertFalse(Curriculum.inCurriculum(Catalog.get(PrimeRecall.ID),2022));CurriculumLimits l=GlobalCurriculum.limits(pack.id,PrimeRecall.ID,5);List<String> history=new ArrayList<>();Generator gen=new Generator(new Random(165));for(int i=0;i<18;i++){Question q=gen.next(PrimeRecall.ID,history,false,l);assertFalse(history.contains(q.signature()));assertTrue(q.choices.isEmpty());history.add(q.signature());}assertEquals(history.get(0),gen.next(PrimeRecall.ID,history,false,l).signature());}
}
