package com.gomgomapps.math.core;
import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class PrimaryPowersTest {
 static final List<String> IDS=List.of("squareWhole","cubeWhole",PrimaryPowers.SQUARE,PrimaryPowers.CUBE);
 @Test public void finiteDomainsAndPublicChecking(){for(String id:IDS){assertTrue(PrimaryPowers.count(id)>=100);for(int i=0;i<PrimaryPowers.count(id);i++){Question q=PrimaryPowers.at(id,i);int[] g=PrimaryPowers.read(q);long value=g[1]==2?(long)g[0]*g[0]:(long)g[0]*g[0]*g[0];String expected;if(PrimaryPowers.added(id)){int b=0;while((g[1]==2?(long)b*b:(long)b*b*b)<g[0])b++;expected=(g[1]==2?(long)b*b:(long)b*b*b)==g[0]?"1":"0";}else expected=""+value;q.answers=new String[]{"poison"};q.expression="poison";assertTrue(new Checker().check(q,List.of(),List.of(expected)).correct());assertFalse(new Checker().check(q,List.of(),List.of(PrimaryPowers.added(id)?expected.equals("1")?"0":"1":""+(value+1))).correct());assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(q,List.of(),List.of("abc")).status);}}}
 @Test public void notationAndBlankRelationships(){for(String id:IDS){Question q=PrimaryPowers.at(id,10);int[] g=PrimaryPowers.read(q);HelpPlan plan=HelpPlan.forQuestion(q);assertFalse(plan.canTransfer());List<String> values=new ArrayList<>();if(PrimaryPowers.added(id)){int b=PrimaryPowers.lower(g[0],g[1]);values.add(""+g[0]);values.add(""+b);values.add(""+PrimaryPowers.power(b,g[1]));values.add(""+PrimaryPowers.power(b+1,g[1]));values.add(PrimaryPowers.answer(id,g[0],g[1]));assertEquals(5,plan.size());}else{assertTrue(q.prompt.endsWith(g[1]==2?"²":"³"));values.add(""+g[0]);values.add(""+g[1]);values.add(""+PrimaryPowers.power(g[0],2));if(g[1]==3)values.add(""+PrimaryPowers.power(g[0],3));}for(int i=0;i<plan.size();i++){assertTrue(plan.step(i).accepts(values.get(i)));assertFalse(plan.step(i).accepts(""));}if(!PrimaryPowers.added(id))assertEquals("두 수의 곱 B = a × a = ",plan.step(2).before);}}
 @Test public void normalPlacementFreshConditionsAndChoicePositions(){var pack=GlobalCurriculum.packs("GB").stream().filter(p->p.id.equals("england-primary-2021-v1")).findFirst().orElseThrow();for(String id:IDS){assertTrue(pack.inGrade(id,5));Generator gen=new Generator(new Random(171));List<String> recent=new ArrayList<>();Set<Integer> positions=new HashSet<>();Set<String> classifications=new HashSet<>();int positive=0;for(int i=0;i<100;i++){Question q=gen.next(id,recent,true,GlobalCurriculum.limits(pack.id,id,5));assertTrue(PrimaryPowers.selected(q));assertFalse(recent.contains(q.signature()));recent.add(q.signature());positions.add(q.correctChoice);classifications.add(q.answers[0]);if(q.answers[0].equals("1"))positive++;assertFalse(HelpPlan.forQuestion(q).canTransfer());}if(PrimaryPowers.added(id)){assertEquals(Set.of(0,1),positions);assertEquals(Set.of("0","1"),classifications);assertTrue(positive>=25&&positive<=75);}}assertFalse(Curriculum.inCurriculum(Catalog.get(PrimaryPowers.SQUARE),2022));}
 @Test public void legacyAndMalformedAreSeparate(){assertFalse(PrimaryPowers.selected(new Question("cubeWhole","(5)^3","5^3","125")));for(String prompt:List.of("101²","4³","2^2")){Question q=new Question("squareWhole",prompt,"","16");assertEquals(Checker.Status.INPUT_NEEDED,PrimaryPowers.check(q,List.of("16")).status);}Question zero=PrimaryPowers.at("cubeWhole",0);assertTrue(new Checker().check(zero,List.of(),List.of("0")).correct());}
}
