package com.gomgomapps.math.core;
import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class PrimeVocabularyTest {
 private boolean prime(int n){if(n<2)return false;for(int d=2;d*d<=n;d++)if(n%d==0)return false;return true;}
 @Test public void everyConditionUsesPublicGivensAndRejectsEachOtherChoice(){Checker c=new Checker();for(String id:List.of(PrimeVocabulary.CLASSIFY,PrimeVocabulary.FACTOR)){Set<String> seen=new HashSet<>();assertTrue(PrimeVocabulary.count(id)>=100);for(int i=0;i<PrimeVocabulary.count(id);i++){Question q=PrimeVocabulary.indexed(id,i);assertTrue(seen.add(q.signature()));int[] g=PrimeVocabulary.read(q);String expected=id.equals(PrimeVocabulary.CLASSIFY)?(g[0]==1?"0":prime(g[0])?"1":"2"):(prime(g[1])&&g[0]%g[1]==0?"1":"0");q.answers=new String[]{"poison"};q.correctChoice=999;for(String option:q.choiceLabels.keySet())assertEquals(option.equals(expected),c.check(q,List.of(),List.of(option)).correct());assertEquals(Checker.Status.INPUT_NEEDED,c.check(q,List.of(),List.of("" )).status);}}}
 @Test public void edgeCasesAndMalformedQuestions(){Checker c=new Checker();assertTrue(c.check(PrimeVocabulary.make(PrimeVocabulary.CLASSIFY,1,0),List.of(),List.of("0")).correct());assertTrue(c.check(PrimeVocabulary.make(PrimeVocabulary.CLASSIFY,2,0),List.of(),List.of("1")).correct());assertTrue(c.check(PrimeVocabulary.make(PrimeVocabulary.CLASSIFY,121,0),List.of(),List.of("2")).correct());assertTrue(c.check(PrimeVocabulary.make(PrimeVocabulary.FACTOR,12,4),List.of(),List.of("0")).correct());assertTrue(c.check(PrimeVocabulary.make(PrimeVocabulary.FACTOR,12,5),List.of(),List.of("0")).correct());assertTrue(c.check(PrimeVocabulary.make(PrimeVocabulary.FACTOR,12,3),List.of(),List.of("1")).correct());assertNull(PrimeVocabulary.read(new Question(PrimeVocabulary.CLASSIFY,"0은 소수, 합성수, 둘 다 아님 중 무엇인가요?","","1")));assertNull(PrimeVocabulary.read(new Question(PrimeVocabulary.FACTOR,"1은 12의 소인수인가요?","","1")));}
 @Test public void blankHelpFramesNoAnswerTransferAndIndependentRelations(){for(Question q:List.of(PrimeVocabulary.make(PrimeVocabulary.CLASSIFY,1,0),PrimeVocabulary.make(PrimeVocabulary.CLASSIFY,121,0),PrimeVocabulary.make(PrimeVocabulary.FACTOR,12,4),PrimeVocabulary.make(PrimeVocabulary.FACTOR,12,5))){q.answers=new String[]{"poison"};HelpPlan h=HelpPlan.forQuestion(q);assertFalse(h.canTransfer());assertTrue(h.restore(null,q.id).entries.stream().allMatch(String::isEmpty));int[] g=PrimeVocabulary.read(q);int target=g.length==1?g[0]:g[1],count=0;for(int d=1;d<=target;d++)if(target%d==0)count++;assertTrue(h.step(0).accepts(""+count));assertFalse(h.step(0).accepts("999"));if(g.length==2)assertTrue(h.step(1).accepts(""+(g[0]%g[1])));assertEquals(g.length==1?2:3,h.size());}}
 @Test public void ordinaryGeneratorFreshThenOldestOnlyReviewedPlacementAndShuffledChoices(){Learning.Profile p=new Learning.Profile();GlobalCurriculum.chooseCountry(p,"GB");GlobalCurriculum.choosePack(p,"england-primary-2021-v1");GlobalCurriculum.Pack pack=GlobalCurriculum.pack(p);Generator gen=new Generator(new Random(164));for(String id:List.of(PrimeVocabulary.CLASSIFY,PrimeVocabulary.FACTOR)){assertTrue(pack.inGrade(id,5));assertFalse(pack.inGrade(id,4));assertFalse(pack.inGrade(id,6));assertFalse(Curriculum.inCurriculum(Catalog.get(id),2022));CurriculumLimits limits=GlobalCurriculum.limits(pack.id,id,5);List<String> history=new ArrayList<>();Set<List<String>> orders=new HashSet<>();for(int i=0;i<100;i++){Question q=gen.next(id,history,false,limits);assertNotNull(PrimeVocabulary.read(q));assertFalse(history.contains(q.signature()));history.add(q.signature());orders.add(List.copyOf(q.choices));}assertTrue(orders.size()>1);Map<String,Integer> all=new LinkedHashMap<>();for(int i=0;i<PrimeVocabulary.count(id);i++)all.put(PrimeVocabulary.indexed(id,i).signature(),i);assertEquals(PrimeVocabulary.indexed(id,0).signature(),PrimeVocabulary.next(id,new Random(1),limits,all).signature());}}
}
