package com.gomgomapps.math.core;
import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class PrimaryScaleRatesTest {
 @Test public void wholeQuantityInputStaysSingleEvenAfterOldFractionMode(){for(String id:IDS){Question q=PrimaryScaleRates.at(id,0);assertFalse(FractionInput.available(q));assertFalse(FractionInput.defaultFraction(q));Learning.Session s=new Learning.Session();s.question=q;s.answers=new ArrayList<>(List.of("397/"));FractionInput.forms(s).put(0,new FractionInput.Form(true));assertFalse(FractionInput.form(s,0).fraction);assertEquals("397/",s.answers.get(0));}}
 static final List<String> IDS=List.of(PrimaryScaleRates.SCALE,PrimaryScaleRates.AMOUNT,PrimaryScaleRates.TIME);
 @Test public void allConditionsHaveUniqueVisibleQuestionsAndPublicAnswers(){for(String id:IDS){Set<String> unique=new HashSet<>();boolean lower=false,higher=false;for(int i=0;i<PrimaryScaleRates.count(id);i++){Question q=PrimaryScaleRates.at(id,i);assertTrue(unique.add(q.signature()));int[] v=PrimaryScaleRates.read(q);assertNotNull(v);int result;if(id.equals(PrimaryScaleRates.SCALE)){assertEquals(0,v[0]*v[1]%v[2]);result=v[0]*v[1]/v[2];lower|=v[1]<v[2];higher|=v[1]>v[2];}else{assertEquals(0,v[0]%v[1]);int rate=v[0]/v[1];result=id.equals(PrimaryScaleRates.AMOUNT)?v[2]*rate:v[2]/rate;if(id.equals(PrimaryScaleRates.TIME))assertEquals(0,v[2]%rate);}assertEquals(""+result,q.answers[0]);q.answers=new String[]{"poison"};q.expression="poison";assertTrue(new Checker().check(q,List.of(),List.of(""+result)).correct());assertEquals(Checker.Status.WRONG_ANSWER,new Checker().check(q,List.of(),List.of(""+(result+1))).status);}if(id.equals(PrimaryScaleRates.SCALE))assertTrue(lower&&higher);}assertEquals(9000,PrimaryScaleRates.count(PrimaryScaleRates.SCALE));assertEquals(9570,PrimaryScaleRates.count(PrimaryScaleRates.AMOUNT));assertEquals(9570,PrimaryScaleRates.count(PrimaryScaleRates.TIME));}
 @Test public void helpHasBlankStudentRelationshipsWithoutTransfer(){for(String id:IDS)for(int i=0;i<PrimaryScaleRates.count(id);i+=53){Question q=PrimaryScaleRates.at(id,i);int[] v=PrimaryScaleRates.read(q);int[] values=id.equals(PrimaryScaleRates.SCALE)?new int[]{v[0],v[1],v[2],v[0]/v[2],Integer.parseInt(q.answers[0])}:new int[]{v[0],v[1],v[0]/v[1],v[2],Integer.parseInt(q.answers[0])};HelpPlan plan=HelpPlan.forQuestion(q);assertEquals(5,plan.size());assertFalse(plan.canTransfer());for(int j=0;j<5;j++){assertTrue(plan.step(j).accepts(""+values[j]));assertFalse(plan.step(j).accepts(""));assertFalse(plan.step(j).before.matches(".*\\d.*"));assertEquals("",plan.step(j).after);for(int r:PrimaryScaleRates.referenceIndices(id,j))assertTrue(r<j);}}}
 @Test public void freshHundredWithShuffledChoicesAndExplicitPlacement(){var pack=GlobalCurriculum.packs("GB").stream().filter(p->p.id.equals("england-primary-2021-v1")).findFirst().orElseThrow();for(String id:IDS){assertTrue(pack.inGrade(id,5));assertFalse(pack.inGrade(id,4));assertFalse(Curriculum.inCurriculum(Catalog.get(id),2022));Generator gen=new Generator(new Random(174));List<String> recent=new ArrayList<>();Set<Integer> positions=new HashSet<>();for(int i=0;i<100;i++){Question q=gen.next(id,recent,i%2==0,GlobalCurriculum.limits(pack.id,id,5));assertFalse(recent.contains(q.signature()));recent.add(q.signature());assertNotNull(PrimaryScaleRates.read(q));if(!q.choices.isEmpty()){assertEquals(4,new HashSet<>(q.choices).size());assertEquals(q.answers[0],q.choices.get(q.correctChoice));positions.add(q.correctChoice);}}assertEquals(Set.of(0,1,2,3),positions);}}
 @Test public void invalidPublicGivensAreRejectedAndNegativeCountsAreWrong(){Question q=PrimaryScaleRates.at(PrimaryScaleRates.SCALE,0);for(String raw:List.of("","1/2","1.5","1234567"))assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(q,List.of(),List.of(raw)).status);assertEquals(Checker.Status.WRONG_ANSWER,new Checker().check(q,List.of(),List.of("−1")).status);for(String prompt:List.of(q.prompt.replace("1/2","1/0"),q.prompt.replace("2g","3g"),q.prompt.replace("1/2","2/4"))){q.prompt=prompt;assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(q,List.of(),List.of("1")).status);}q=new Question(PrimaryScaleRates.TIME,"물이 일정한 속도로 흐릅니다.\n2분 동안 물 6L가 흐릅니다.\n물 1L가 흐르는 데 몇 분이 걸리나요?","","1");assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(q,List.of(),List.of("1")).status);}
}
