package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class ProbabilityRelationsTest {
 private List<Rational> values(Question q){Matcher m=Pattern.compile("\\d+(?:\\.\\d+)?(?:/\\d+)?").matcher(q.prompt);List<Rational> nums=new ArrayList<>();while(m.find())nums.add(Expression.number(m.group()));if(q.skillId.endsWith("add")){assertEquals(3,nums.size());Rational total=nums.get(0),a=nums.get(1),b=nums.get(2),sum=a.add(b);return List.of(a,b,total,sum,sum.div(total));}assertEquals(2,nums.size());return List.of(nums.get(0),nums.get(1),nums.get(0).mul(nums.get(1)));}
 @Test public void generatedPublicConditionsGiveEveryStepAndVariedProblems(){Generator g=new Generator(new Random(2050));for(String id:List.of("sec_probability_add","sec_probability_multiply")){Set<String> prompts=new HashSet<>(),answers=new HashSet<>();Set<Integer> positions=new HashSet<>();boolean noninteger=false;for(int i=0;i<1000;i++){Question q=g.next(id,List.of(),i%2==0);var v=values(q);Rational result=v.get(v.size()-1);assertTrue(result.compareTo(Rational.ZERO)>=0&&result.compareTo(Rational.ONE)<=0);assertTrue(new Checker().check(q,List.of(),List.of(result.toString())).correct());prompts.add(q.prompt);answers.add(result.toString());positions.add(q.correctChoice);noninteger|=!result.isInteger();verify(q,v);}assertTrue(prompts.size()>100);assertTrue(answers.size()>100);assertTrue(noninteger);assertTrue(positions.containsAll(Set.of(0,1,2,3)));}}
 private void verify(Question q,List<Rational> v){String signature=q.signature();StudyDiagram old=q.diagram;Arrays.fill(q.answers,"999999");q.choiceInputs=new Rational[]{Rational.of(999999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(signature,q.signature());assertSame(old,q.diagram);assertFalse(p.canTransfer());assertEquals(v.size(),p.size());for(int i=0;i<v.size();i++){assertTrue(p.step(i).accepts(v.get(i).toString()));assertFalse(p.step(i).accepts(v.get(i).add(Rational.ONE).toString()));assertEquals("",p.step(i).after);assertFalse(p.step(i).before.matches(".*[0-9].*"));}assertEquals(q.skillId.endsWith("add")?"A의 경우의 수 = ":"A의 확률 = ",p.step(0).before);}
 @Test public void savedEndpointsAndFractionalProbabilitiesRemainExact(){for(String[] pair:new String[][]{{"0","1"},{"1","1"},{"3/7","0.25"},{"2/4","5/10"}}){Question q=new Question("sec_probability_multiply","서로 독립인 두 시행에서 A가 일어날 확률은 "+pair[0]+", B가 일어날 확률은 "+pair[1]+"입니다. 둘 다 일어날 확률은?","","999999");verify(q,values(q));}for(String[] pair:new String[][]{{"0","0"},{"0","10"},{"3","7"}}){Question q=new Question("sec_probability_add","같은 가능성의 결과가 10개이고 서로 겹치지 않는 A가 "+pair[0]+"개, B가 "+pair[1]+"개입니다. A 또는 B일 확률은?","","999999");verify(q,values(q));}}
 @Test public void oldCalculatedSumDraftResetsAndNewPublicCountRestores(){Question q=new Question("sec_probability_add","같은 가능성의 결과가 20개이고 서로 겹치지 않는 A가 3개, B가 5개입니다. A 또는 B일 확률은?","","2/5");HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of("8",""));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));d.entries.set(0,"3");d.stage=1;var restored=HelpPlan.forQuestion(q).restore(d.copy(),q.id);assertEquals(1,restored.stage);assertEquals("3",restored.entries.get(0));}
}
