package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class QuadraticValueRelationsTest {
 private List<Rational> values(Question q){String num="[+-]?\\d+(?:\\.\\d+)?(?:/\\d+)?";Matcher m=Pattern.compile("f\\(x\\)=("+num+")\\(x-\\(("+num+")\\)\\)²([+-]\\d+(?:\\.\\d+)?(?:/\\d+)?)일 때 f\\(("+num+")\\)의 값은\\?").matcher(q.prompt);assertTrue(m.matches());Rational a=Expression.number(m.group(1)),h=Expression.number(m.group(2)),k=Expression.number(m.group(3)),x=Expression.number(m.group(4)),d=x.sub(h),s=d.mul(d),product=a.mul(s);return List.of(x,a,h,k,d,s,product,product.add(k));}
 @Test public void publicQuadraticsDetermineEachStepIncludingNegativeAndZeroValues(){Generator g=new Generator(new Random(2060));Set<String> prompts=new HashSet<>(),answers=new HashSet<>();Set<Integer> positions=new HashSet<>();boolean negativeShift=false,zeroShift=false,negativeProduct=false,positiveProduct=false,negativeFinal=false;for(int i=0;i<1000;i++){Question q=g.next("sec_quadratic_value",List.of(),i%2==0);var v=values(q);assertTrue(new Checker().check(q,List.of(),List.of(v.get(7).toString())).correct());prompts.add(q.prompt);answers.add(v.get(7).toString());positions.add(q.correctChoice);negativeShift|=v.get(4).compareTo(Rational.ZERO)<0;zeroShift|=v.get(4).equals(Rational.ZERO);negativeProduct|=v.get(6).compareTo(Rational.ZERO)<0;positiveProduct|=v.get(6).compareTo(Rational.ZERO)>0;negativeFinal|=v.get(7).compareTo(Rational.ZERO)<0;verify(q,v);}assertTrue(prompts.size()>100);assertTrue(answers.size()>100);assertTrue(positions.containsAll(Set.of(0,1,2,3)));assertTrue(negativeShift&&zeroShift&&negativeProduct&&positiveProduct&&negativeFinal);}
 private void verify(Question q,List<Rational> v){String signature=q.signature();StudyDiagram old=q.diagram;Arrays.fill(q.answers,"999999");q.choiceInputs=new Rational[]{Rational.of(999999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(signature,q.signature());assertSame(old,q.diagram);assertFalse(p.canTransfer());assertEquals(8,p.size());for(int i=0;i<8;i++){assertTrue(p.step(i).accepts(v.get(i).toString()));assertFalse(p.step(i).accepts(v.get(i).add(Rational.ONE).toString()));assertEquals("",p.step(i).after);}assertEquals("x − h = ",p.step(4).before);assertEquals("(x−h) × (x−h) = ",p.step(5).before);assertEquals("a × (x−h)² + k = ",p.step(7).before);for(int i=4;i<8;i++)assertFalse(p.step(i).before.matches(".*[0-9].*"));}
 @Test public void savedFractionalCoefficientsAndInputsKeepExactMeaning(){for(String text:List.of("f(x)=3/2(x-(-5/4))²+1/8일 때 f(0)의 값은?","f(x)=-0.5(x-(1/2))²-3/4일 때 f(-1.5)의 값은?","f(x)=-3(x-(-2))²+0일 때 f(-2)의 값은?")){Question q=new Question("sec_quadratic_value",text,"","999999");verify(q,values(q));}}
 @Test public void oldShiftedValueDraftResetsAndPublicXDraftRestores(){Question q=new Question("sec_quadratic_value","f(x)=-3(x-(-2))²+5일 때 f(-4)의 값은?","","-7");HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of("-2",""));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));d.entries.set(0,"-4");d.stage=1;var restored=HelpPlan.forQuestion(q).restore(d.copy(),q.id);assertEquals(1,restored.stage);assertEquals("-4",restored.entries.get(0));}
}
