package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class QuadraticRangeRelationsTest {
 private List<Rational> values(Question q){String n="[+-]?\\d+(?:\\.\\d+)?(?:/\\d+)?";Matcher m;
  if(q.skillId.equals("sec_simultaneous_quadratic")){m=Pattern.compile("y=x²(?:\\+\\(("+n+")\\))?, y=("+n+")를 동시에 만족하고 x>0일 때 x는\\?").matcher(q.prompt);assertTrue(m.matches());Rational b=m.group(1)==null?Rational.ZERO:Expression.number(m.group(1)),y=Expression.number(m.group(2)),sq=y.sub(b),x=sqrt(sq);assertEquals(y,x.mul(x).add(b));assertTrue(x.compareTo(Rational.ZERO)>0);return List.of(b,y,sq,x);}
  if(q.skillId.equals("sec_quadratic_inequality")){m=Pattern.compile("\\(x-\\(("+n+")\\)\\)²(?:\\+\\(("+n+")\\))?≤("+n+")를 만족하는 정수 x는 모두 몇 개인가요\\?").matcher(q.prompt);assertTrue(m.matches());Rational h=Expression.number(m.group(1)),b=m.group(2)==null?Rational.ZERO:Expression.number(m.group(2)),y=Expression.number(m.group(3)),sq=y.sub(b),a=sqrt(sq);List<Integer> allowed=new ArrayList<>();for(int x=-100;x<=100;x++){Rational dx=Rational.of(x).sub(h);if(dx.mul(dx).add(b).compareTo(y)<=0)allowed.add(x);}assertFalse(allowed.isEmpty());return List.of(h,b,y,sq,a,Rational.of(allowed.get(0)),Rational.of(allowed.get(allowed.size()-1)),Rational.of(allowed.size()));}
  m=Pattern.compile("("+n+")≤x≤("+n+")에서 f\\(x\\)=("+n+")\\(x-\\(("+n+")\\)\\)²\\+\\(("+n+")\\)의 최솟값은\\?").matcher(q.prompt);assertTrue(m.matches());Rational low=Expression.number(m.group(1)),high=Expression.number(m.group(2)),a=Expression.number(m.group(3)),h=Expression.number(m.group(4)),k=Expression.number(m.group(5));List<Rational> candidates=new ArrayList<>(List.of(low,high));if(h.compareTo(low)>=0&&h.compareTo(high)<=0)candidates.add(h);Rational best=null,minimum=null;for(Rational x:candidates){Rational dx=x.sub(h),value=a.mul(dx.mul(dx)).add(k);if(minimum==null||value.compareTo(minimum)<0){minimum=value;best=x;}}Rational difference=best.sub(h);return List.of(h,a,k,best,difference,difference.mul(difference),minimum);
 }
 private Rational sqrt(Rational v){long n=Math.round(Math.sqrt(v.n.longValueExact())),d=Math.round(Math.sqrt(v.d.longValueExact()));Rational result=Rational.of(n,d);assertEquals(v,result.mul(result));return result;}
 private void verify(Question q,List<Rational> v){String id=q.id,prompt=q.prompt,signature=q.signature();StudyDiagram diagram=q.diagram;Arrays.fill(q.answers,"999999");q.choiceInputs=new Rational[]{Rational.of(999999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(v.size(),p.size());assertFalse(p.canTransfer());assertEquals(id,q.id);assertEquals(prompt,q.prompt);assertEquals(signature,q.signature());assertSame(diagram,q.diagram);for(int i=0;i<p.size();i++){assertTrue(p.step(i).accepts(v.get(i).toString()));assertFalse(p.step(i).accepts(v.get(i).add(Rational.ONE).toString()));assertEquals("",p.step(i).after);} }
 @Test public void publicEquationsAndIndependentIntervalsControlAllSteps(){Generator g=new Generator(new Random(2096));boolean vertex=false,left=false,right=false;for(String skill:List.of("sec_simultaneous_quadratic","sec_quadratic_inequality","sec_quadratic_extremum")){Set<String> prompts=new HashSet<>();Set<Integer> positions=new HashSet<>();for(int i=0;i<1000;i++){Question q=g.next(skill,List.of(),i%2==0);List<Rational> v=values(q);Rational result=v.get(v.size()-1);assertTrue(new Checker().check(q,List.of(),List.of(result.toString())).correct());assertFalse(new Checker().check(q,List.of(),List.of(result.add(Rational.ONE).toString())).correct());prompts.add(q.prompt);positions.add(q.correctChoice);if(skill.equals("sec_quadratic_extremum")){int comparison=v.get(3).compareTo(v.get(0));vertex|=comparison==0;left|=comparison<0;right|=comparison>0;}verify(q,v);}assertTrue(skill+prompts.size(),prompts.size()>100);assertTrue(positions.containsAll(Set.of(0,1,2,3)));}assertTrue(vertex&&left&&right);}
 @Test public void savedFractionsInclusiveEndpointsAndVersionedDrafts(){for(Question q:List.of(new Question("sec_simultaneous_quadratic","y=x², y=9/4를 동시에 만족하고 x>0일 때 x는?","","3/2"),new Question("sec_quadratic_inequality","(x-(1/2))²≤9/4를 만족하는 정수 x는 모두 몇 개인가요?","","4"),new Question("sec_quadratic_extremum","-3/2≤x≤-1/2에서 f(x)=2(x-(1/2))²+(-1)의 최솟값은?","","1"))){List<Rational> v=values(q);verify(q,v);HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of(v.get(0).toString()));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));assertTrue(d.teachingVersion.endsWith("relations-v1"));d.entries.set(0,v.get(0).toString());d.stage=1;assertEquals(1,HelpPlan.forQuestion(q).restore(d.copy(),q.id).stage);}}
}
