package com.gomgomapps.math.core;
import org.junit.Test;import static org.junit.Assert.*;import java.util.*;import java.io.*;
public class RadicalAnswerFrameTest {
 @Test public void asyncSnapshotDetachesIncompleteFrameInsteadOfRejectingIt(){Learning.State state=new Learning.State();state.session=session("rootSimplify","√(56)","2√(14)");RadicalAnswerFrame.update(state.session,0,"−2/");Learning.State frozen=LearningSnapshot.capture(state);assertNotSame(state.session.radicalAnswerDraft,frozen.session.radicalAnswerDraft);assertNotSame(state.session.radicalAnswerDraft.values,frozen.session.radicalAnswerDraft.values);assertEquals(List.of("−2/",""),frozen.session.radicalAnswerDraft.values);RadicalAnswerFrame.update(state.session,0,"3");assertEquals("−2/",frozen.session.radicalAnswerDraft.values.get(0));}
 private Learning.Session session(String skill,String expression,String answer){Learning.Session s=new Learning.Session();s.question=new Question(skill,expression,expression,answer);s.question.kind="radical";s.answers.add("");return s;}
 @Test public void fieldsStartBlankRegardlessOfAnswerMetadata(){for(String id:RadicalWork.SKILLS){Learning.Session s=session(id,id.equals("rootRationalize")?"12/(3+√(14))":"√(56)","do not read");assertTrue(RadicalAnswerFrame.available(s));assertTrue(RadicalAnswerFrame.draft(s).values.stream().allMatch(String::isEmpty));assertEquals("",s.answers.get(0));}}
 @Test public void typedSignedFractionAndRootComposeWithoutSolving(){Learning.Session s=session("rootQuotient","(-6√(13))/(-4√(2))","3√(26)/4");RadicalAnswerFrame.update(s,0,"3/4");assertEquals("",s.answers.get(0));RadicalAnswerFrame.update(s,1,"26");assertTrue(RadicalWork.answer(s.question,s.answers).correct());assertEquals(List.of("3/4","26"),s.radicalAnswerDraft.values);RadicalAnswerFrame.update(s,0,"6/8");assertEquals(Checker.Status.INPUT_NEEDED,RadicalWork.answer(s.question,s.answers).status);assertEquals("6/8",s.radicalAnswerDraft.values.get(0));}
 @Test public void binomialFieldsKeepNegativeTermsAndDoNotRationalizeForStudent(){Learning.Session s=session("rootRationalize","12/(3+√(14))","-36/5+12√(14)/5");assertEquals(3,RadicalAnswerFrame.draft(s).values.size());RadicalAnswerFrame.update(s,0,"−36/5");RadicalAnswerFrame.update(s,1,"12/5");assertEquals("",s.answers.get(0));RadicalAnswerFrame.update(s,2,"14");assertTrue(RadicalWork.answer(s.question,s.answers).correct());RadicalAnswerFrame.update(s,1,"−12/5");assertEquals(Checker.Status.WRONG_ANSWER,RadicalWork.answer(s.question,s.answers).status);}
 @Test public void rationalAndZeroResultsNeedNoUnsimplifiedRootOne(){assertEquals(Radical.parse("3/4"),Radical.parse(RadicalAnswerFrame.compose(List.of("3/4","1"))));assertTrue(Radical.simplified(RadicalAnswerFrame.compose(List.of("3/4","1"))));assertEquals("0",RadicalAnswerFrame.compose(List.of("0","3")));}
 @Test public void partialDraftSurvivesSerializationAndOldRawAnswersRemainUntouched()throws Exception{Learning.Session s=session("rootSimplify","√(56)","2√(14)");RadicalAnswerFrame.update(s,0,"−2/");ByteArrayOutputStream bytes=new ByteArrayOutputStream();new ObjectOutputStream(bytes).writeObject(s);Learning.Session restored=(Learning.Session)new ObjectInputStream(new ByteArrayInputStream(bytes.toByteArray())).readObject();assertEquals(List.of("−2/",""),RadicalAnswerFrame.draft(restored).values);assertEquals("",restored.answers.get(0));Learning.Session old=session("rootSimplify","√(56)","2√(14)");old.answers.set(0,"2√(14)");assertFalse(RadicalAnswerFrame.available(old));assertEquals("2√(14)",old.answers.get(0));}
 @Test public void choicesAndNewQuestionIdentityDoNotReuseFrame(){Learning.Session s=session("rootSimplify","√(56)","2√(14)");RadicalAnswerFrame.update(s,0,"2");s.question=new Question("rootSimplify","√(72)","√(72)","6√(2)");assertTrue(RadicalAnswerFrame.draft(s).values.stream().allMatch(String::isEmpty));s.question.choices.add("6√(2)");assertFalse(RadicalAnswerFrame.available(s));}
}
