package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class RatioValueRelationsTest {
 private Matcher match(String pattern,String prompt){Matcher m=Pattern.compile(pattern).matcher(prompt);assertTrue(prompt,m.find());return m;}
 @Test public void eachBlankFollowsPublicGivensWithoutAnswerKeys(){Generator g=new Generator(new Random(777));for(String id:List.of("percent","proportion","substitute","function","linearValue"))for(int i=0;i<500;i++){
  Question q=g.create(Catalog.get(id));List<Rational> values;
  if(id.equals("percent")){Matcher m=match("(\\d+)의 (\\d+)%",q.prompt);Rational whole=Expression.number(m.group(1)),percent=Expression.number(m.group(2)),rate=percent.div(Rational.of(100));values=List.of(whole,percent,rate,whole.mul(rate));}
  else if(id.equals("proportion")){Matcher m=match("(\\d+) : (\\d+) = (\\d+) : x",q.prompt);Rational a=Expression.number(m.group(1)),b=Expression.number(m.group(2)),c=Expression.number(m.group(3)),factor=c.div(a);values=List.of(a,b,c,factor,b.mul(factor));}
  else{Rational x,coefficient,constant;if(id.equals("linearValue")){Matcher m=match("y = (.*?)x(?: ([+-]) (\\d+))?\\nx = (-?\\d+)일 때",q.prompt);String raw=m.group(1);coefficient=raw.isEmpty()?Rational.ONE:raw.equals("-")?Rational.ONE.neg():Expression.number(raw);constant=m.group(3)==null?Rational.ZERO:Expression.number((m.group(2).equals("-")?"-":"")+m.group(3));x=Expression.number(m.group(4));}
   else if(id.equals("substitute")){Matcher m=match("x = (-?\\d+)일 때\\n(-?\\d+)x \\+ \\((-?\\d+)\\)",q.prompt);x=Expression.number(m.group(1));coefficient=Expression.number(m.group(2));constant=Expression.number(m.group(3));}
   else{Matcher m=match("f\\(x\\) = (-?\\d+)x \\+ \\((-?\\d+)\\)\\nf\\((-?\\d+)\\)",q.prompt);coefficient=Expression.number(m.group(1));constant=Expression.number(m.group(2));x=Expression.number(m.group(3));}Rational product=x.mul(coefficient);values=List.of(x,coefficient,product,constant,product.add(constant));}
  Rational result=values.get(values.size()-1);assertTrue(new Checker().check(q,List.of(),List.of(result.toString())).correct());Arrays.fill(q.answers,"999999");HelpPlan p=HelpPlan.forQuestion(q);assertFalse(p.canTransfer());assertEquals(values.size(),p.size());HelpPlan.Draft d=p.restore(null,q.id);for(int k=0;k<values.size();k++){assertTrue(p.step(k).accepts(values.get(k).toString()));assertFalse(p.step(k).accepts(values.get(k).add(Rational.ONE).toString()));assertFalse(p.step(k).before.replace("100","").matches("(?s).*\\d.*"));d.entries.set(k,values.get(k).toString());d.stage++;d.entries.add("");}assertEquals(result,Expression.number(p.enteredAnswer(d)));
 }}
 @Test public void legacyRateDraftIsClearedAndCheckedWholeSurvives(){Question q=new Question("percent","30의 5%는?","30*5/100","1.5");q.studyGuide=new StudyGuide().step("old","5 ÷ 100 = ","","0.05");HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of("0.05",""));HelpPlan p=HelpPlan.forQuestion(q);p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));d.entries.set(0,"30");d.stage=1;d.entries.add("");HelpPlan.Draft restored=HelpPlan.forQuestion(q).restore(d.copy(),q.id);assertEquals(1,restored.stage);assertEquals("30",restored.entries.get(0));assertEquals("ratio-value-relations-v1",restored.teachingVersion);}
}
