package com.gomgomapps.math.core;
import org.junit.Test;import static org.junit.Assert.*;import java.util.*;import java.util.regex.*;import java.io.*;
public class RatioCorrespondenceRelationsTest {
 private static List<Integer> numbers(String prompt){List<Integer> out=new ArrayList<>();Matcher m=Pattern.compile("[0-9]+").matcher(prompt);while(m.find())out.add(Integer.parseInt(m.group()));return out;}
 private static Rational answer(Question q){var n=numbers(q.prompt);return switch(q.skillId){case "el_ratio_terms"->Rational.of(n.get(0)+n.get(1));case "el_ratio_fraction"->Rational.of(n.get(0),n.get(1));case "el_correspondence_add"->Rational.of(n.get(0)+n.get(1));default->Rational.of(n.get(0)*(n.size()==2?n.get(1):q.prompt.contains(" + ")?n.get(1)+n.get(2):n.get(1)-n.get(2)));};}
 @Test public void publicRelationsHaveVarietyAndRemainIndependentOfKeys(){Generator g=new Generator(new Random(99901));for(String id:RatioCorrespondenceRelations.IDS){Set<String> prompts=new HashSet<>();for(int i=0;i<1600;i++){Question q=g.next(id,List.of(),i%2==0);Rational expected=answer(q);assertEquals(expected,Expression.number(q.answers[0]));prompts.add(q.prompt);String sig=q.signature();String[] answers=q.answers.clone();var choices=new ArrayList<>(q.choices);HelpPlan p=HelpPlan.forQuestion(q);var frames=RatioCorrespondenceRelations.frames(q);assertFalse(frames.isEmpty());assertFalse(p.canTransfer());HelpPlan.Draft d=p.restore(null,q.id);for(int k=0;k<p.size();k++){var f=frames.get(k);assertTrue(p.step(k).accepts(f.expected()));assertFalse(p.step(k).accepts(""));assertFalse(p.step(k).accepts(""+(Integer.parseInt(f.expected())+1)));assertFalse(f.label().matches(".*[0-9].*"));d.entries.set(k,f.expected());d.stage++;d.entries.add("");}assertEquals(expected,Expression.number(p.enteredAnswer(d)));assertEquals(sig,q.signature());assertArrayEquals(answers,q.answers);assertEquals(choices,q.choices);q.answers=new String[]{"999"};q.expression="999+1";q.studyGuide=new StudyGuide().step("old","999 = ","","999");p=HelpPlan.forQuestion(q);assertFalse(p.canTransfer());assertEquals(expected,Expression.number(p.enteredAnswer(d)));}assertTrue(id+" "+prompts.size(),prompts.size()>=100);}}
 @Test public void inputAndFactorBoundsAndFractionMeaningArePreserved(){Generator g=new Generator(new Random(99902));boolean pure=false,plus=false,minus=false;for(int i=0;i<1600;i++){Question q=g.next("el_correspondence_mul",List.of(),false);var n=numbers(q.prompt);int input=n.size()==2?n.get(1):q.prompt.contains(" + ")?n.get(1)+n.get(2):n.get(1)-n.get(2);assertTrue(n.get(0)>=2&&n.get(0)<=9);for(int k=1;k<n.size();k++)assertTrue(n.get(k)>=1&&n.get(k)<=12);assertTrue(input>=1&&input<=12);pure|=n.size()==2;plus|=q.prompt.contains(" + ");minus|=q.prompt.contains(" − ");q=g.next("el_ratio_fraction",List.of(),false);n=numbers(q.prompt);assertTrue(n.get(0)>=1&&n.get(0)<n.get(1)&&n.get(1)<=30);assertTrue(FractionInput.defaultFraction(q));assertEquals(0,(int)q.studyGuide.resultNumeratorFrame);assertEquals(1,(int)q.studyGuide.resultDenominatorFrame);}assertTrue(pure&&plus&&minus);for(String prompt:List.of("x와 y의 대응 관계가 y=10x입니다.\nx=2일 때 y의 값은?","x와 y의 대응 관계가 y=3x입니다.\nx=(1 − 2)일 때 y의 값은?","x와 y의 대응 관계가 y=x+3입니다.\nx=2일 때 y의 값은?"))assertTrue(RatioCorrespondenceRelations.frames(new Question("el_correspondence_mul",prompt,"","0")).isEmpty());assertTrue(RatioCorrespondenceRelations.frames(new Question("el_ratio_fraction","비교하는 양이 5, 기준량이 5일 때 비율을 분수로 나타내세요.","","1")).isEmpty());}
 @Test public void oldDraftResetsAndCheckedPartialRestores()throws Exception{for(String id:RatioCorrespondenceRelations.IDS){Question q=new Generator(new Random(99903)).next(id,List.of(),false);q.studyGuide=new StudyGuide().step("old","29 = ","","29");HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft old=new HelpPlan.Draft();old.questionId=q.id;old.stage=1;old.entries.add("29");assertEquals(0,p.restore(old,q.id).stage);HelpPlan.Draft d=p.restore(null,q.id);d.entries.set(0,q.studyGuide.frames.get(0).expected);d.stage=1;d.entries.add("");ByteArrayOutputStream b=new ByteArrayOutputStream();new ObjectOutputStream(b).writeObject(d);HelpPlan.Draft loaded=(HelpPlan.Draft)new ObjectInputStream(new ByteArrayInputStream(b.toByteArray())).readObject();assertEquals(1,p.restore(loaded,q.id).stage);assertEquals(d.entries.get(0),p.restore(loaded,q.id).entries.get(0));}}
}
