package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class RelativeFrequencyRelationsTest {
 private List<Rational> values(Question q){Matcher m=Pattern.compile("\\d+").matcher(q.prompt);assertTrue(m.find());Rational total=Expression.number(m.group());assertTrue(m.find());Rational frequency=Expression.number(m.group());return List.of(frequency,total,frequency.div(total));}
 @Test public void diagramNamesReferToDataClassesAndDoNotMutateStoredIdentity(){Generator g=new Generator(new Random(2022));for(int i=0;i<300;i++){Question q=g.next("sec_relative_frequency",List.of(),false);var v=values(q);String signature=q.signature();StudyDiagram old=q.diagram;Arrays.fill(q.answers,"99999");q.choiceInputs=new Rational[]{Rational.of(99999)};StudyDiagram d=RelativeFrequencyRelations.diagram(q);assertSame(old,q.diagram);assertEquals(signature,q.signature());assertArrayEquals(new String[]{"이 계급의 자료","다른 계급의 자료"},d.labels);assertEquals(v.get(0).intValue(),d.values[0],0);assertEquals(v.get(1).sub(v.get(0)).intValue(),d.values[1],0);}}
 @Test public void publicCountsDetermineOriginalAnswerAndEveryRelationship(){Generator g=new Generator(new Random(2020));Set<String> prompts=new HashSet<>();Set<Integer> positions=new HashSet<>();Set<String> answers=new HashSet<>();for(int i=0;i<600;i++){Question q=g.next("sec_relative_frequency",List.of(),i%2==0);var v=values(q);assertTrue(new Checker().check(q,List.of(),List.of(v.get(2).toString())).correct());assertTrue(v.get(2).compareTo(Rational.ZERO)>=0&&v.get(2).compareTo(Rational.ONE)<=0);prompts.add(q.prompt);positions.add(q.correctChoice);answers.add(v.get(2).toString());verify(q,v);}assertTrue(prompts.size()>100);assertTrue(answers.size()>15);assertTrue(positions.containsAll(Set.of(0,1,2,3)));}
 @Test public void savedZeroOneAndUnreducedCountsKeepIdentityAndExactAnswers(){for(String s:List.of("전체 도수가 17이고 한 계급의 도수가 0일 때 그 계급의 상대도수는?","전체 도수가 17이고 한 계급의 도수가 17일 때 그 계급의 상대도수는?","전체 도수가 48이고 한 계급의 도수가 30일 때 그 계급의 상대도수는?")){Question q=new Question("sec_relative_frequency",s,"","99999");verify(q,values(q));}}
 @Test public void oldReducedDraftCannotPopulatePublicCountsAndVersionedCountsRestore(){Question q=new Question("sec_relative_frequency","전체 도수가 48이고 한 계급의 도수가 30일 때 그 계급의 상대도수는?","","5/8");HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of("5",""));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));d.entries.set(0,"30");d.stage=1;var restored=HelpPlan.forQuestion(q).restore(d.copy(),q.id);assertEquals(1,restored.stage);assertEquals("30",restored.entries.get(0));}
 private void verify(Question q,List<Rational> values){String signature=q.signature();Arrays.fill(q.answers,"99999");q.choiceInputs=new Rational[]{Rational.of(99999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(signature,q.signature());assertFalse(p.canTransfer());assertEquals(3,p.size());for(int k=0;k<3;k++){assertTrue(p.step(k).accepts(values.get(k).toString()));assertFalse(p.step(k).accepts(values.get(k).add(Rational.ONE).toString()));assertFalse(p.step(k).before.matches("(?s).*\\d.*"));}assertEquals("계급 도수 ÷ 전체 도수 = ",p.step(2).before);}
}
