package com.gomgomapps.math.core;
import org.junit.Test;import static org.junit.Assert.*;import java.math.*;import java.util.*;import java.util.regex.*;import java.io.*;
public class RoundingRelationsTest {
 private final List<String> ids=List.of("el_estimate_ops","el_round","el_round_up","el_round_down","el_decimal_round");
 private String text(BigDecimal n){return n.stripTrailingZeros().toPlainString();}
 private List<String> numbers(String prompt){List<String> n=new ArrayList<>();Matcher m=Pattern.compile("[0-9]+(?:\\.[0-9]+)?").matcher(prompt);while(m.find())n.add(m.group());return n;}
 private List<String> oracle(Question q){List<String> v=numbers(q.prompt),out=new ArrayList<>();if(q.skillId.equals("el_estimate_ops")){BigDecimal unit=new BigDecimal(v.get(2));out.add(text(unit));BigDecimal a=one(out,v.get(0),unit,"nearest",true,false),b=one(out,v.get(1),unit,"nearest",true,false);out.add(text(a.add(b)));}
  else{boolean decimal=q.skillId.equals("el_decimal_round");int places=decimal?(q.prompt.contains("첫째")?1:q.prompt.contains("둘째")?2:3):0;BigDecimal unit=decimal?BigDecimal.ONE.movePointLeft(places):new BigDecimal(v.get(1));out.add(v.get(0));if(decimal)out.add(""+places);out.add(text(unit));one(out,v.get(0),unit,q.skillId.equals("el_round_up")?"up":q.skillId.equals("el_round_down")?"down":"nearest",false,decimal);}return out;}
 private BigDecimal one(List<String> out,String original,BigDecimal unit,String mode,boolean include,boolean decimal){
  BigDecimal n=new BigDecimal(original),base=n.divide(unit,0,RoundingMode.DOWN).multiply(unit),rounded=n.divide(unit,0,mode.equals("up")?RoundingMode.CEILING:mode.equals("down")?RoundingMode.DOWN:RoundingMode.HALF_UP).multiply(unit);if(include)out.add(original);if(mode.equals("down")){out.add(text(base));return base;}
  if(mode.equals("up"))out.add(text(n.remainder(unit)));
  else{String[] parts=original.split("\\.");String digits=decimal?(parts.length==1?"":parts[1])+"000000":parts[0];int index=decimal?unit.scale():digits.length()-unit.toPlainString().length()+1;out.add(""+(index<0?0:digits.charAt(index)-'0'));}
  boolean raise=rounded.compareTo(base)>0;out.add(raise?"raise":"keep");out.add(text(base));out.add(raise?text(unit):"0");out.add(text(rounded));return rounded;
 }
 private void verify(Question q,boolean checker){String signature=q.signature();String[] answers=q.answers.clone();List<String> expected=oracle(q);HelpPlan p=HelpPlan.forQuestion(q);assertNotNull(q.prompt,p);assertFalse(p.canTransfer());assertEquals(q.prompt,expected.size(),p.size());assertEquals("rounding-relations-v1",q.studyGuide.teachingVersion);for(int i=0;i<p.size();i++){assertTrue(q.prompt+" step "+i+" expected "+expected.get(i),p.step(i).accepts(expected.get(i)));assertFalse(p.step(i).accepts(""));String wrong=p.step(i).options.isEmpty()?text(new BigDecimal(expected.get(i)).add(BigDecimal.ONE)):expected.get(i).equals("raise")?"keep":"raise";assertFalse(p.step(i).accepts(wrong));assertEquals("",p.step(i).after);assertFalse(p.step(i).before.matches(".*[0-9].*"));if(!p.step(i).options.isEmpty())assertEquals(Set.of("raise","keep"),p.step(i).options.keySet());}assertEquals(signature,q.signature());assertArrayEquals(answers,q.answers);if(checker)assertTrue(q.prompt,new Checker().check(q,List.of(),List.of(expected.get(expected.size()-1))).correct());}
 @Test public void allFiveUnitsKeepTheirPublicQuestionsAndRequireStudentDecisions(){Generator g=new Generator(new Random(710901));for(String id:ids){Set<String> seen=new HashSet<>();for(int i=0;i<600;i++){Question q=g.next(id,List.of(),i%2==0);verify(q,true);seen.add(q.prompt);Question old=new Question(id,q.prompt,"poison remainder","999999999");old.studyGuide=new StudyGuide().step("old","999 = ","999","999");verify(old,false);}assertTrue(id,seen.size()>=100);}}
 @Test public void carriesTiesExactValuesAndLowHiddenDigitsUseCorrectRounding(){for(String[] item:new String[][]{{"el_round","1499을 1000의 자리까지 반올림하면?"},{"el_round","1500을 1000의 자리까지 반올림하면?"},{"el_round","99999을 10의 자리까지 반올림하면?"},{"el_round_up","1001을 1000의 자리까지 올림하면?"},{"el_round_up","5000을 1000의 자리까지 올림하면?"},{"el_round_down","99999을 1000의 자리까지 버림하면?"},{"el_decimal_round","9.995을 소수 둘째 자리까지 반올림하면?"},{"el_decimal_round","0.0001을 소수 셋째 자리까지 반올림하면?"},{"el_decimal_round","2.4500을 소수 첫째 자리까지 반올림하면?"}})verify(new Question(item[0],item[1],"poison","poison"),false);assertNull(RoundingRelations.read(new Question("el_round","123을 11의 자리까지 반올림하면?","0","0")));assertNull(RoundingRelations.read(new Question("el_round_up","123을 10의 자리까지 버림하면?","0","0")));}
 @Test public void actualKenyaRoundingPrecisionAndCountryPlaceLimitsArePreserved(){Generator g=new Generator(new Random(710902));Set<Integer> targets=new HashSet<>();for(String id:ids)for(int i=0;i<300;i++){CurriculumLimits limits=GlobalCurriculum.limits("ke-kicd-cbc-2024-v1",id,6);Question q=g.next(id,List.of(),false,limits);verify(q,true);if(id.equals("el_decimal_round")){assertTrue(new BigDecimal(numbers(q.prompt).get(0)).scale()<=4);targets.add(q.prompt.contains("첫째")?1:q.prompt.contains("둘째")?2:3);}else if(!id.equals("el_estimate_ops"))assertTrue(numbers(q.prompt).get(0).length()<=6);}assertEquals(Set.of(1,2,3),targets);}
 @Test public void legacyGuidesResetWhileNumericAndChoicePartialEntriesRestore()throws Exception{for(String id:ids){Question q=new Generator(new Random(901)).next(id,List.of(),false);HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft legacy=new HelpPlan.Draft();legacy.questionId=q.id;legacy.stage=1;legacy.entries.add("999");assertEquals(0,p.restore(legacy,q.id).stage);HelpPlan.Draft d=p.restore(null,q.id);List<String> values=oracle(q);int stop=Math.min(p.size()-1,5);for(int i=0;i<stop;i++){d.entries.set(i,values.get(i));d.stage++;d.entries.add("");}ByteArrayOutputStream bytes=new ByteArrayOutputStream();new ObjectOutputStream(bytes).writeObject(d);HelpPlan.Draft saved=(HelpPlan.Draft)new ObjectInputStream(new ByteArrayInputStream(bytes.toByteArray())).readObject();assertEquals(stop,p.restore(saved,q.id).stage);}}
}
