package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class RoundSolidVolumeRelationsTest {
 private final List<String> ids=List.of("sec_cone_volume","sec_sphere_volume");
 @Test public void publicLengthsDefineExactCoefficientsWithoutSupplyingIntermediateAnswers(){Generator g=new Generator(new Random(1900));for(String id:ids)for(int i=0;i<600;i++){Question q=g.next(id,List.of(),i%2==0);List<Rational> givens=new ArrayList<>();Matcher m=Pattern.compile("[0-9]+(?:\\.[0-9]+)?(?:/\\d+)?").matcher(q.prompt);while(m.find())givens.add(Expression.number(m.group()));assertTrue(q.prompt.contains("(□)π"));List<Rational> values=expected(id,givens);assertTrue(new Checker().check(q,List.of(),List.of(values.get(values.size()-1).toString())).correct());verify(q,values,givens);}}
 @Test public void savedFractionalLengthsKeepExactFinalDivision(){for(String id:ids){Question q=saved(id);List<Rational> givens=id.equals(ids.get(0))?List.of(Rational.of(1,2),Rational.of(3,2)):List.of(Rational.of(1,2));verify(q,expected(id,givens),givens);}}
 @Test public void oldCalculatedDraftCannotPopulateNewRadiusAndCheckedNewInputsRestore(){for(String id:ids){Question q=saved(id);HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of("16",""));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));d.entries.set(0,"1/2");d.stage=1;HelpPlan.Draft restored=HelpPlan.forQuestion(q).restore(d.copy(),q.id);assertEquals(1,restored.stage);assertEquals("1/2",restored.entries.get(0));}}
 private Question saved(String id){return new Question(id,id.equals(ids.get(0))?"반지름이 1/2, 높이가 3/2인 원뿔의 부피는 (□)π입니다. □는?":"반지름이 1/2인 구의 부피는 (□)π입니다. □는?","","99999");}
 private List<Rational> expected(String id,List<Rational> g){Rational r=g.get(0);return id.equals(ids.get(0))?List.of(r,g.get(1),r.pow(2),r.pow(2).mul(g.get(1)),r.pow(2).mul(g.get(1)).div(Rational.of(3))):List.of(r,r.pow(3),r.pow(3).mul(Rational.of(4)).div(Rational.of(3)));}
 private void verify(Question q,List<Rational> values,List<Rational> givens){String signature=q.signature();Arrays.fill(q.answers,"99999");q.choiceInputs=new Rational[]{Rational.of(99999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(signature,q.signature());assertEquals(values.size(),p.size());assertFalse(p.canTransfer());for(int k=0;k<p.size();k++){assertTrue(p.step(k).accepts(values.get(k).toString()));assertFalse(p.step(k).accepts(values.get(k).add(Rational.ONE).toString()));assertFalse(p.step(k).before.replace("3","").replace("4","").replace("²","").replace("³","").matches("(?s).*\\d.*"));assertEquals("",p.step(k).after);}StudyDiagram picture=BasicSolidDiagram.forQuestion(q);assertEquals(q.skillId.equals(ids.get(0))?"basicSolidConeHeight":"basicSolidSphere",picture.type);for(int i=0;i<givens.size();i++)assertEquals(givens.get(i).n.doubleValue()/givens.get(i).d.doubleValue(),picture.values[i],1e-9);}
}
