package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class SectorCoefficientRelationsTest {
 @Test public void publicRadiusAndAngleDetermineExactPiCoefficient(){Generator g=new Generator(new Random(1880));for(String id:List.of("sec_sector_arc","sec_sector_area"))for(int i=0;i<600;i++){Question q=g.next(id,List.of(),i%2==0);Matcher m=Pattern.compile("반지름이 (.*?), 중심각이 (.*?)°").matcher(q.prompt);assertTrue(m.find());Rational radius=Expression.number(m.group(1)),angle=Expression.number(m.group(2)),circle=id.endsWith("arc")?radius.mul(Rational.of(2)):radius.pow(2),coefficient=circle.mul(angle).div(Rational.of(360));assertTrue(q.prompt.contains("(□)π"));assertTrue(new Checker().check(q,List.of(),List.of(coefficient.toString())).correct());assertEquals("sector",q.diagram.type);assertEquals(angle.intValue(),(int)q.diagram.values[1]);verify(q,List.of(radius,angle,circle,coefficient));}}
 @Test public void savedFractionalRadiusAndAngleRemainExact(){for(String id:List.of("sec_sector_arc","sec_sector_area")){Question q=question(id,"1/2","45/2");verify(q,List.of(Rational.of(1,2),Rational.of(45,2),id.endsWith("arc")?Rational.ONE:Rational.of(1,4),id.endsWith("arc")?Rational.of(1,16):Rational.of(1,64)));}}
 @Test public void oldComputedCoefficientCannotBecomeRadius(){for(String id:List.of("sec_sector_arc","sec_sector_area")){Question q=question(id,"8","90");HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of("16",""));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));d.entries.set(0,"8");d.stage=1;HelpPlan.Draft restored=HelpPlan.forQuestion(q).restore(d.copy(),q.id);assertEquals(1,restored.stage);assertEquals("8",restored.entries.get(0));}}
 private Question question(String id,String radius,String angle){return new Question(id,"반지름이 "+radius+", 중심각이 "+angle+"°인 부채꼴의 "+(id.endsWith("arc")?"호의 길이":"넓이")+"는 (□)π입니다. □는?","","999999");}
 private void verify(Question q,List<Rational> values){String signature=q.signature();Arrays.fill(q.answers,"999999");q.choiceInputs=new Rational[]{Rational.of(999999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(signature,q.signature());assertEquals(4,p.size());assertFalse(p.canTransfer());for(int k=0;k<4;k++){assertTrue(p.step(k).accepts(values.get(k).toString()));assertFalse(p.step(k).accepts(values.get(k).add(Rational.ONE).toString()));assertFalse(p.step(k).before.replace("360","").replace("2","").replace("²","").matches("(?s).*\\d.*"));}}
}
