package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class SolidSurfaceRelationsTest {
 private static final List<String> IDS=List.of("sec_prism_surface","sec_cylinder_surface","sec_cone_surface","sec_sphere_surface");
 @Test public void publicLengthsIndependentlyDetermineEverySurfaceFrame(){Generator g=new Generator(new Random(1890));for(String id:IDS)for(int i=0;i<600;i++){Question q=g.next(id,List.of(),i%2==0);List<Rational> lengths=new ArrayList<>();Matcher m=Pattern.compile("[0-9]+(?:\\.[0-9]+)?(?:/[0-9]+)?").matcher(q.prompt);while(m.find())lengths.add(Expression.number(m.group()));assertEquals(id,id.equals(IDS.get(0))?3:id.equals(IDS.get(3))?1:2,lengths.size());List<Rational> values=expected(id,lengths);assertTrue(new Checker().check(q,List.of(),List.of(values.get(values.size()-1).toString())).correct());if(!id.equals(IDS.get(0)))assertTrue(q.prompt.contains("(□)π"));if(id.equals(IDS.get(2))){assertTrue(q.prompt.contains("모선"));assertTrue(lengths.get(1).compareTo(lengths.get(0))>0);}verify(q,values);}}
 @Test public void savedFractionalLengthsKeepExactAreasAndCoefficients(){for(String id:IDS){Question q=question(id);List<Rational> v=id.equals(IDS.get(0))?List.of(Rational.of(1,2),Rational.ONE,Rational.of(3,2)):id.equals(IDS.get(3))?List.of(Rational.of(1,2)):List.of(Rational.of(1,2),Rational.of(3,2));verify(q,expected(id,v));}}
 @Test public void oldAreaDraftCannotBecomeNewLength(){for(String id:IDS){Question q=question(id);HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of("16",""));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));d.entries.set(0,"1/2");d.stage=1;HelpPlan.Draft restored=HelpPlan.forQuestion(q).restore(d.copy(),q.id);assertEquals(1,restored.stage);assertEquals("1/2",restored.entries.get(0));}}
 private Question question(String id){String prompt=switch(id){case "sec_prism_surface"->"가로 1/2, 세로 1, 높이 3/2인 직육면체의 겉넓이는?";case "sec_cylinder_surface"->"반지름이 1/2, 높이가 3/2인 원기둥의 겉넓이는 (□)π입니다. □는?";case "sec_cone_surface"->"밑면 반지름이 1/2, 모선이 3/2인 원뿔의 겉넓이는 (□)π입니다. □는?";default->"반지름이 1/2인 구의 겉넓이는 (□)π입니다. □는?";};return new Question(id,prompt,"","999999");}
 private List<Rational> expected(String id,List<Rational> v){List<Rational> out=new ArrayList<>(v);Rational a=v.get(0);switch(id){case "sec_prism_surface":{Rational b=v.get(1),c=v.get(2),ab=a.mul(b),ac=a.mul(c),bc=b.mul(c);out.addAll(List.of(ab,ac,bc,ab.add(ac).add(bc).mul(Rational.of(2))));break;}case "sec_cylinder_surface":{Rational bases=a.pow(2).mul(Rational.of(2)),side=a.mul(v.get(1)).mul(Rational.of(2));out.addAll(List.of(bases,side,bases.add(side)));break;}case "sec_cone_surface":{Rational base=a.pow(2),side=a.mul(v.get(1));out.addAll(List.of(base,side,base.add(side)));break;}default:out.addAll(List.of(a.pow(2),a.pow(2).mul(Rational.of(4))));}return out;}
 private void verify(Question q,List<Rational> values){String signature=q.signature();Arrays.fill(q.answers,"999999");q.choiceInputs=new Rational[]{Rational.of(999999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(signature,q.signature());assertEquals(values.size(),p.size());assertFalse(p.canTransfer());for(int k=0;k<p.size();k++){assertTrue(p.step(k).accepts(values.get(k).toString()));assertFalse(p.step(k).accepts(values.get(k).add(Rational.ONE).toString()));assertFalse(p.step(k).before.replace("2","").replace("4","").replace("²","").matches("(?s).*\\d.*"));assertEquals("",p.step(k).after);}}
}
