package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class SolidFoundationRelationsTest {
 private List<Rational> values(Question q){List<Rational> g=new ArrayList<>();Matcher m=Pattern.compile("[0-9]+(?:\\.[0-9]+)?(?:/\\d+)?").matcher(q.prompt);while(m.find())g.add(Expression.number(m.group()));if(q.skillId.equals("regularPolygonArea")){assertEquals(2,g.size());Rational count=Rational.of(q.prompt.startsWith("정오각형")?5:6),triangle=g.get(0).mul(g.get(1)).div(Rational.of(2));return List.of(g.get(0),g.get(1),count,triangle,triangle.mul(count));}boolean triangle=q.prompt.contains("삼각형"),square=q.prompt.contains("정사각형");assertEquals(square?2:3,g.size());Rational base=square?g.get(0).pow(2):g.get(0).mul(g.get(1)).div(Rational.of(triangle?2:1)),prism=base.mul(g.get(g.size()-1));List<Rational> out=new ArrayList<>(g);out.addAll(List.of(base,prism,prism.div(Rational.of(3))));return out;}
 @Test public void publicMeasurementsDetermineEveryRelationshipAndOriginalAnswer(){Generator gen=new Generator(new Random(2000));Set<String> shapes=new HashSet<>();for(String id:List.of("regularPolygonArea","pyramidVolume"))for(int i=0;i<600;i++){Question q=gen.next(id,List.of(),i%2==0);List<Rational> v=values(q);assertTrue(new Checker().check(q,List.of(),List.of(v.get(v.size()-1).toString())).correct());if(id.equals("regularPolygonArea")){assertTrue(q.prompt.contains("소수 첫째 자리 근삿값"));shapes.add(q.prompt.startsWith("정오각형")?"pentagon":"hexagon");}else{assertTrue(q.prompt.contains("수직 높이"));shapes.add(q.prompt.contains("정사각형")?"square":q.prompt.contains("삼각형")?"triangle":"rectangle");}verify(q,v);}assertEquals(Set.of("pentagon","hexagon","square","triangle","rectangle"),shapes);}
 @Test public void savedFractionalMeasurementsKeepExactArithmeticAndUnits(){for(Question q:saved())verify(q,values(q));}
 @Test public void oldCalculatedDraftCannotPopulateLengthAndNewEntriesRestore(){for(Question q:saved()){HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of("16",""));p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));d.entries.set(0,"1/2");d.stage=1;HelpPlan.Draft restored=HelpPlan.forQuestion(q).restore(d.copy(),q.id);assertEquals(1,restored.stage);assertEquals("1/2",restored.entries.get(0));}}
 private List<Question> saved(){return List.of(new Question("regularPolygonArea","정오각형 · 한 변 1/2cm\n중심에서 변까지 수직거리 0.3cm\n수직거리는 소수 첫째 자리 근삿값입니다.\n주어진 길이로 넓이는 몇 cm²인가요?","","99999"),new Question("pyramidVolume","각뿔 · 밑면 삼각형 · 밑변 1/2cm · 높이 3/2cm\n수직 높이 2cm\n부피는 몇 cm³인가요?","","99999"),new Question("pyramidVolume","각뿔 · 밑면 직사각형 · 가로 1/2cm · 세로 3/2cm\n수직 높이 2cm\n부피는 몇 cm³인가요?","","99999"),new Question("pyramidVolume","각뿔 · 밑면 정사각형 · 한 변 1/2cm\n수직 높이 2cm\n부피는 몇 cm³인가요?","","99999"));}
 private void verify(Question q,List<Rational> values){String signature=q.signature();Arrays.fill(q.answers,"99999");q.choiceInputs=new Rational[]{Rational.of(99999)};HelpPlan p=HelpPlan.forQuestion(q);assertEquals(signature,q.signature());assertEquals(values.size(),p.size());assertFalse(p.canTransfer());for(int k=0;k<p.size();k++){assertTrue(p.step(k).accepts(values.get(k).toString()));assertFalse(p.step(k).accepts(values.get(k).add(Rational.ONE).toString()));assertFalse(p.step(k).before.replace("2","").replace("3","").replace("²","").matches("(?s).*\\d.*"));}assertEquals(q.skillId.equals("regularPolygonArea")?" cm²":" cm³",p.step(p.size()-1).after);}
}
