package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class SolidVolumeLearningTest {
 @Test public void storedFilledFormulaGuideIsReplacedWithoutReadingAnswerKey(){
  Question q=new Generator(new Random(1190)).create(Catalog.get("sec_prism_volume"));
  int width=(int)q.diagram.values[0],depth=(int)q.diagram.values[1],height=(int)q.diagram.values[2];
  q.studyGuide=new StudyGuide().step("old",width+" × "+depth+" = ","",String.valueOf(width*depth)).step("old",width*depth+" × "+height+" = ","",String.valueOf(width*depth*height));
  HelpPlan.Draft old=new HelpPlan.Draft();old.questionId=q.id;old.stage=1;old.entries.add(String.valueOf(width*depth));old.entries.add("");
  Arrays.fill(q.answers,"999999");HelpPlan plan=HelpPlan.forQuestion(q);
  assertEquals("가로 = ",plan.step(0).before);assertEquals("가로 × 세로 = ",plan.step(2).before);
  assertTrue(plan.step(0).accepts(String.valueOf(width)));assertFalse(plan.step(0).accepts(String.valueOf(width*depth)));
  assertEquals(0,plan.restore(old,q.id).stage);assertEquals("",old.entries.get(0));assertFalse(plan.canTransfer());
 }
 private List<Integer> cm(Question q){List<Integer> dims=new ArrayList<>();Matcher m=Pattern.compile("([0-9]+)cm").matcher(q.prompt);while(m.find())dims.add(Integer.parseInt(m.group(1)));return dims;}
 @Test public void hundredUniquePublicDimensionProblemsForEachShape(){for(String id:List.of("sec_prism_volume","sec_cylinder_volume","triangularPrismVolume")){Generator g=new Generator(new Random(1151+id.hashCode()));Set<String> seen=new HashSet<>();Set<Integer> positions=new HashSet<>();for(int i=0;i<100;i++){Question q=g.next(id,seen,true);assertTrue(id+" repeated at "+i,seen.add(q.signature()));List<Integer> v=cm(q);boolean cylinder=id.equals("sec_cylinder_volume"),triangular=id.equals("triangularPrismVolume");assertEquals(cylinder?2:3,v.size());Rational base=cylinder?Rational.of(v.get(0)*v.get(0)):Rational.of(v.get(0)*v.get(1)).div(Rational.of(triangular?2:1)),volume=base.mul(Rational.of(v.get(cylinder?1:2)));assertTrue(new Checker().check(q,List.of(),List.of(volume.toString())).correct());assertFalse(new Checker().check(q,List.of(),List.of(volume.add(Rational.ONE).toString())).correct());assertEquals(cylinder?"solidCylinder":triangular?"solidTriangularPrism":"solidRectPrism",q.diagram.type);assertEquals(v.size(),q.diagram.values.length);for(int k=0;k<v.size();k++)assertEquals(v.get(k),q.diagram.values[k],0);assertEquals(4,new HashSet<>(q.choices).size());assertEquals(volume,Expression.number(q.choices.get(q.correctChoice)));positions.add(q.correctChoice);HelpPlan plan=HelpPlan.forQuestion(q);assertEquals(cylinder?4:5,plan.size());assertFalse(plan.canTransfer());HelpPlan.Draft d=plan.restore(null,q.id);String[] entries=cylinder?new String[]{v.get(0).toString(),base.toString(),v.get(1).toString(),volume.toString()}:new String[]{v.get(0).toString(),v.get(1).toString(),base.toString(),v.get(2).toString(),volume.toString()};for(int k=0;k<entries.length;k++){assertFalse("Filled measurement or intermediate result",plan.step(k).before.matches("(?s).*\\d{2,}.*"));assertTrue(plan.step(k).accepts(entries[k]));assertFalse(plan.step(k).accepts(Expression.number(entries[k]).add(Rational.ONE).toString()));d.entries.set(k,entries[k]);d.stage++;d.entries.add("");}Arrays.fill(q.answers,"999999");assertEquals(volume,Expression.number(plan.enteredAnswer(d)));}assertEquals(id,Set.of(0,1,2,3),positions);}}
 @Test public void cylinderSuppliesBeyondOldEightyEightPairs(){Random r=new Random(1152);Set<String> seen=new HashSet<>();boolean newRadius=false,newHeight=false;for(int i=0;i<6000;i++){Question q=SecondaryBasics.create(Catalog.get("sec_cylinder_volume"),r);List<Integer> v=cm(q);assertTrue(v.get(0)>=2&&v.get(0)<=20);assertTrue(v.get(1)>=2&&v.get(1)<=30);newRadius|=v.get(0)>9;newHeight|=v.get(1)>12;seen.add(q.signature());assertEquals(Rational.of(v.get(0)*v.get(0)*v.get(1)),Expression.number(q.answers[0]));double[] values=q.diagram.values.clone();Arrays.fill(q.answers,"999999");assertArrayEquals(values,q.diagram.values,0);}assertTrue(newRadius&&newHeight);assertTrue(seen.size()>500);}
}
