package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import org.junit.Test;import static org.junit.Assert.*;
public class StatisticsRelationsTest {
 @Test public void publicGivensDriveEveryBlankWithoutRevealingIntermediateValues(){Generator g=new Generator(new Random(193));for(String id:List.of("mean","angles"))for(int i=0;i<500;i++){
  Question q=g.create(Catalog.get(id));List<Rational> values=new ArrayList<>();Matcher m=Pattern.compile(id.equals("mean")?"\\d+":"(\\d+)°").matcher(q.prompt);while(m.find())values.add(Expression.number(id.equals("mean")?m.group():m.group(1)));List<Rational> expected;if(id.equals("mean")){Rational sum=values.stream().reduce(Rational.ZERO,Rational::add),count=Rational.of(values.size());expected=List.of(sum,count,sum.div(count));}else{assertEquals(2,values.size());Rational a=values.get(0),b=values.get(1),sum=a.add(b);expected=List.of(a,b,sum,Rational.of(180).sub(sum));}Rational result=expected.get(expected.size()-1);assertTrue(new Checker().check(q,List.of(),List.of(result.toString())).correct());Arrays.fill(q.answers,"999999");HelpPlan p=HelpPlan.forQuestion(q);assertFalse(p.canTransfer());assertEquals(expected.size(),p.size());HelpPlan.Draft d=p.restore(null,q.id);for(int k=0;k<expected.size();k++){assertTrue(p.step(k).accepts(expected.get(k).toString()));assertFalse(p.step(k).accepts(expected.get(k).add(Rational.ONE).toString()));assertFalse(p.step(k).before.replace("180°","").matches("(?s).*\\d.*"));d.entries.set(k,expected.get(k).toString());d.stage++;d.entries.add("");}assertEquals(result,Expression.number(p.enteredAnswer(d)));
 }}
 @Test public void oldMeanInputsKeepTheirMeaningAndSurviveTemplateCorrection(){Question q=new Question("mean","1, 2, 3, 5의 평균은?","11/4","11/4");q.studyGuide=new StudyGuide().transfer(false).step("old","1,2,3,5 → 합계 = ","","11").step("old","자료의 개수 = ","","4").step("old","11 ÷ 4 = ","","11/4");HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=2;d.entries=new ArrayList<>(List.of("11","4",""));HelpPlan p=HelpPlan.forQuestion(q);p.restore(d,q.id);assertEquals(2,d.stage);assertEquals(List.of("11","4",""),d.entries);assertEquals("계산한 합계 ÷ 자료의 개수 = ",p.step(2).before);}
 @Test public void oldAngleSumCannotBeReusedAsAnAngleMeasurement(){Question q=new Question("angles","삼각형의 두 내각이 40°, 75°","180-40-75","65");q.studyGuide=new StudyGuide().step("old","40 + 75 = ","","115");HelpPlan.Draft d=new HelpPlan.Draft();d.questionId=q.id;d.stage=1;d.entries=new ArrayList<>(List.of("115",""));HelpPlan p=HelpPlan.forQuestion(q);p.restore(d,q.id);assertEquals(0,d.stage);assertEquals("",d.entries.get(0));d.entries.set(0,"40");d.stage=1;d.entries.add("");HelpPlan.Draft restored=HelpPlan.forQuestion(q).restore(d.copy(),q.id);assertEquals(1,restored.stage);assertEquals("40",restored.entries.get(0));assertEquals("statistics-angle-relations-v1",restored.teachingVersion);}
}
