package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;import java.io.*;import org.junit.Test;import static org.junit.Assert.*;
public class TimeUnitRelationsTest {
 private List<Integer> nums(String text){List<Integer> n=new ArrayList<>();Matcher m=Pattern.compile("[0-9]+").matcher(text);while(m.find())n.add(Integer.parseInt(m.group()));return n;}
 private void put(Map<String,Integer> m,String key,int value){m.put(key,value);}
 private void clock(Map<String,Integer> m,String prefix,int hour,int minute,int second){put(m,prefix+"의 시간 수",hour);put(m,prefix+"의 분 수",minute);put(m,prefix+"의 초 수",second);put(m,prefix+"의 시간을 바꾼 분",hour*60);put(m,prefix+"의 전체 분",hour*60+minute);put(m,prefix+"의 분을 바꾼 초",(hour*60+minute)*60);put(m,prefix+"의 전체 초",hour*3600+minute*60+second);}
 private Map<String,Integer> oracle(Question q){List<Integer> n=nums(q.prompt);Map<String,Integer> m=new HashMap<>();m.put("1시간의 분 수",60);m.put("1분의 초 수",60);m.put("1주일의 일 수",7);String id=q.skillId;
  if(id.equals("el_hours_to_minutes")||id.equals("el_time_to_seconds")){boolean sec=id.equals("el_time_to_seconds");m.put(sec?"분 수":"시간 수",n.get(0));m.put(sec?"남은 초":"남은 분",n.get(1));m.put(sec?"분을 바꾼 초":"시간을 바꾼 분",n.get(0)*60);m.put(sec?"전체 초":"전체 분",n.get(0)*60+n.get(1));}
  else if(id.equals("el_minutes_to_hours")||id.equals("el_days_to_weeks")){boolean days=id.equals("el_days_to_weeks");String quantity=days?"일 수":"분 수";int total=n.stream().mapToInt(Integer::intValue).sum(),scale=days?7:60;m.put("첫 "+quantity,n.get(0));if(n.size()>1)m.put("둘째 "+quantity,n.get(1));m.put(days?"전체 일 수":"전체 분",total);m.put(days?"주일 수":"시간 수",total/scale);m.put(days?"남은 일":"남은 분",total%scale);}
  else if(id.equals("el_days_week")){if(n.size()==1){m.put("주일 수",n.get(0));m.put("전체 일 수",n.get(0)*7);}else{int total=0;for(int i=0;i<n.size();i+=2){String prefix=i==0?"첫 기간":"둘째 기간";m.put(prefix+"의 주일 수",n.get(i));m.put(prefix+"의 남은 일",n.get(i+1));m.put(prefix+"의 주일을 바꾼 일",n.get(i)*7);int t=n.get(i)*7+n.get(i+1);m.put(prefix+"의 전체 일",t);total+=t;}m.put("전체 일 수",total);}}
  else{boolean sec=id.contains("second"),diff=id.contains("difference");int width=sec?3:2;clock(m,"처음 시각",n.get(0),n.get(1),sec?n.get(2):0);int start=n.get(0)*(sec?3600:60)+n.get(1)*(sec?60:1)+(sec?n.get(2):0),end;
   if(diff){clock(m,"끝 시각",n.get(width),n.get(width+1),sec?n.get(width+2):0);end=n.get(width)*(sec?3600:60)+n.get(width+1)*(sec?60:1)+(sec?n.get(width+2):0);m.put(sec?"걸린 초 수":"걸린 분 수",end-start);}
   else{end=start+n.get(width);m.put(sec?"더할 초 수":"더할 분 수",n.get(width));if(sec)clock(m,"끝 시각",end/3600,(end/60)%60,end%60);else clock(m,"끝 시각",end/60,end%60,0);}
  }return m;
 }
 private void verify(Question q){String sig=q.signature();String[] answers=q.answers.clone();Map<String,Integer> expected=oracle(q);List<TimeUnitRelations.Frame> frames=TimeUnitRelations.frames(q);assertFalse(q.prompt,frames.isEmpty());HelpPlan p=HelpPlan.forQuestion(q);assertEquals(frames.size(),p.size());assertEquals("time-unit-relations-v1",q.studyGuide.teachingVersion);assertFalse(p.canTransfer());
  for(int i=0;i<frames.size();i++){var f=frames.get(i);assertNotNull(f.result(),expected.get(f.result()));String answer=""+expected.get(f.result());assertEquals(q.prompt+" / "+f.result(),answer,f.expected());assertFalse(f.label(),Pattern.compile("[0-9]").matcher(f.label().replace("1시간","시간").replace("1분","분").replace("1주일","주일")).find());assertTrue(p.step(i).accepts(answer));assertFalse(p.step(i).accepts(""+(expected.get(f.result())+1)));assertFalse(p.step(i).accepts(""));for(int prior:f.prior())assertTrue(prior>=0&&prior<i);}
  assertEquals(sig,q.signature());assertArrayEquals(answers,q.answers);assertTrue(new Checker().check(q,List.of(),List.of(answers)).correct());q.expression="9999999";q.answers=new String[]{"9999999"};q.studyGuide=null;TimeUnitRelations.attach(q);List<TimeUnitRelations.Frame> poisoned=TimeUnitRelations.frames(q);assertEquals(frames.size(),poisoned.size());for(int i=0;i<frames.size();i++){assertEquals(frames.get(i).expected(),poisoned.get(i).expected());assertEquals(frames.get(i).label(),poisoned.get(i).label());assertEquals(frames.get(i).result(),poisoned.get(i).result());assertArrayEquals(frames.get(i).prior(),poisoned.get(i).prior());}
 }
 @Test public void allNinePublicFormsAndOriginalAnswers(){for(String id:TimeUnitRelations.IDS){Generator g=new Generator(new Random(819));Set<String> prompts=new HashSet<>();for(int i=0;i<600;i++){Question q=g.next(id,List.of(),i%2==0);prompts.add(q.prompt);verify(q);}assertTrue(id+" unique forms "+prompts.size(),prompts.size()>=100);}}
 @Test public void crossingUnitsZeroAndMalformed(){for(String[] row:new String[][]{{"el_time_add","23시 30분에서 25분 뒤의 시각은?"},{"el_time_difference","9시 55분부터 10시 5분까지 몇 분인가요?"},{"el_time_second_add","9시 59분 59초에서 1초 뒤의 시각은?"},{"el_time_second_difference","9시 59분 59초부터 10시 0분 0초까지 몇 초인가요?"},{"el_minutes_to_hours","1분은 몇 시간 몇 분인가요?"},{"el_days_to_weeks","7일과 7일을 합하면 몇 주일 며칠인가요?"},{"el_days_week","2주일 0일과 3주일 0일을 합하면 모두 며칠인가요?"}}){Question q=new Question(row[0],row[1],"","0");Map<String,Integer> expected=oracle(q);List<TimeUnitRelations.Frame> frames=TimeUnitRelations.frames(q);assertFalse(frames.isEmpty());for(var f:frames)assertEquals(f.result(),""+expected.get(f.result()),f.expected());}
  assertTrue(TimeUnitRelations.frames(new Question("el_time_difference","10시 0분부터 9시 0분까지 몇 분인가요?","","0")).isEmpty());assertTrue(TimeUnitRelations.frames(new Question("el_hours_to_minutes","2시간 60분은 모두 몇 분인가요?","","0")).isEmpty());assertTrue(TimeUnitRelations.frames(new Question("el_time_second_add","23시 59분 59초에서 1초 뒤의 시각은?","","0")).isEmpty());}
 @Test public void legacyDraftRefreshAndPartialRoundTrip()throws Exception{Question q=new Generator(new Random(95)).next("el_time_second_add",List.of(),false);q.studyGuide=new StudyGuide().step("old","999 = ","","999");HelpPlan p=HelpPlan.forQuestion(q);HelpPlan.Draft old=new HelpPlan.Draft();old.stage=1;old.entries.add("999");old=p.restore(old,q.id);assertEquals(0,old.stage);assertTrue(old.entries.stream().allMatch(String::isBlank));for(int i=0;i<4;i++){old.entries.set(i,TimeUnitRelations.frames(q).get(i).expected());old.stage++;old.entries.add("");}ByteArrayOutputStream buf=new ByteArrayOutputStream();new ObjectOutputStream(buf).writeObject(old);HelpPlan.Draft copy=(HelpPlan.Draft)new ObjectInputStream(new ByteArrayInputStream(buf.toByteArray())).readObject();copy=p.restore(copy,q.id);assertEquals(old.stage,copy.stage);assertEquals(old.entries,copy.entries);}
 @Test public void existingCountryGenerationRetainsItsPublicQuantities(){for(String pack:List.of("ke-kicd-cbc-2024-v1","us-ccss-2010-v1")){Generator g=new Generator(new Random(8893));for(String id:TimeUnitRelations.IDS)for(int i=0;i<100;i++)verify(g.next(id,List.of(),false,GlobalCurriculum.limits(pack,id,6)));}}
}
