package com.gomgomapps.math.core;
import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class YearFiveNumberStoriesTest {
 private static void verify(Question q){int[] v=YearFiveNumberStories.read(q);assertNotNull(v);String id=q.skillId;List<String> answers=id.equals(YearFiveNumberStories.COMPARE)?List.of(v[0]==v[1]?"=":v[0]>v[1]?">":"<"):id.equals(YearFiveNumberStories.ROUND)?List.of(""+((v[0]+v[1]/2)/v[1]*v[1])):List.of(""+(v[0]+v[1]),""+(v[0]+2*v[1]));q.answers=new String[]{"999","999"};q.expression="999";Checker c=new Checker();assertTrue(c.check(q,List.of(),answers).correct());List<String> wrong=new ArrayList<>(answers);wrong.set(0,id.equals(YearFiveNumberStories.COMPARE)?answers.get(0).equals("=")?"<":"=":""+(Integer.parseInt(answers.get(0))+1));assertEquals(Checker.Status.WRONG_ANSWER,c.check(q,List.of(),wrong).status);HelpPlan h=HelpPlan.forQuestion(q);assertNotNull(h);assertFalse(h.canTransfer());assertTrue(h.restore(null,q.id).entries.stream().allMatch(String::isEmpty));
  if(id.equals(YearFiveNumberStories.ROUND)){int base=v[0]/v[1]*v[1],digit=v[0]%(v[1])/Math.max(1,v[1]/10),extra=digit>=5?v[1]:0;List<String> entries=List.of(""+v[0],""+v[1],""+digit,digit>=5?"raise":"keep",""+base,""+extra,""+(base+extra));assertEquals(7,h.size());for(int i=0;i<7;i++)assertTrue(h.step(i).accepts(entries.get(i)));}
  else if(id.equals(YearFiveNumberStories.COMPARE)){assertEquals(3,h.size());assertTrue(h.step(0).accepts(""+v[0]));assertTrue(h.step(1).accepts(""+v[1]));assertTrue(h.step(2).accepts(answers.get(0)));}
  else{assertEquals(4,h.size());int[] entries={v[0],Math.abs(v[1]),v[2],v[3]};for(int i=0;i<4;i++)assertTrue(h.step(i).accepts(""+entries[i]));}
 }
 @Test public void indexedSamplesAndEveryTemperatureUseVisibleRelations(){for(String id:List.of(YearFiveNumberStories.STOCK,YearFiveNumberStories.ROUND,YearFiveNumberStories.COMPARE)){int size=YearFiveNumberStories.count(id);for(int index=0;index<size;index+=Math.max(1,size/250))verify(YearFiveNumberStories.at(id,index));verify(YearFiveNumberStories.at(id,size-1));}for(int index=0;index<1220;index++)verify(YearFiveNumberStories.at(YearFiveNumberStories.TEMPERATURE,index));}
 @Test public void actualFiveGradeSuppliesKeepFreshAndEarlierInventoriesStaySmall(){Generator g=new Generator(new Random(155));for(String id:List.of(PracticalPlaceStories.ID,YearFiveNumberStories.STOCK,YearFiveNumberStories.TEMPERATURE,YearFiveNumberStories.ROUND,YearFiveNumberStories.COMPARE)){List<String> recent=new ArrayList<>();for(int i=0;i<200;i++){Question q=g.next(id,recent,false,GlobalCurriculum.limits("england-primary-2021-v1",id,5));assertFalse(recent.contains(q.signature()));recent.add(q.signature());if(id.equals(PracticalPlaceStories.ID)){int[] v=PracticalPlaceStories.readMillion(q);assertNotNull(v);assertTrue(v[6]<=1000000);}else assertNotNull(YearFiveNumberStories.read(q));}}
  for(int grade:new int[]{3,4})for(int i=0;i<50;i++){Question q=g.next(PracticalPlaceStories.ID,List.of(),false,GlobalCurriculum.limits("england-primary-2021-v1",PracticalPlaceStories.ID,grade));assertNull(PracticalPlaceStories.readMillion(q));assertNotNull(grade==3?PracticalPlaceStories.read(q):PracticalPlaceStories.readUpper(q));}
 }
 @Test public void millionInventoryAndStoryBoundaries(){for(int context=0;context<2;context++)for(int number:new int[]{0,1,9999,10000,10001,99999,100000,999999,1000000}){Question q=PracticalPlaceStories.makeMillion(context,number);int[] v=PracticalPlaceStories.readMillion(q);assertNotNull(v);assertEquals(number,v[6]);q.answers=new String[]{"999"};q.expression="999";assertTrue(new Checker().check(q,List.of(),List.of(""+number)).correct());assertEquals(Checker.Status.WRONG_ANSWER,new Checker().check(q,List.of(),List.of(""+(number+1))).status);HelpPlan h=HelpPlan.forQuestion(q);assertEquals(7,h.size());assertFalse(h.canTransfer());int unit=100000;for(int i=0;i<6;i++,unit/=10)assertTrue(h.step(i).accepts(""+(v[i]*unit)));assertTrue(h.step(6).accepts(""+number));}
  for(int unit:new int[]{10,100,1000,10000,100000})for(int number:new int[]{0,unit/2-1,unit/2,unit-1,999999,1000000})verify(YearFiveNumberStories.rounding(number,unit));verify(YearFiveNumberStories.stock(1000000,1000000));verify(YearFiveNumberStories.stock(200000,-100000));verify(YearFiveNumberStories.temperature(1,-1));verify(YearFiveNumberStories.temperature(-1,1));
  Question q=YearFiveNumberStories.temperature(1,-1);q.prompt=q.prompt.replace("1 °C씩","0 °C씩");assertNull(YearFiveNumberStories.read(q));assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(q,List.of(),List.of("1","1")).status);
 }
}
