package com.gomgomapps.math.core;
import java.math.*;import java.util.*;import java.util.concurrent.atomic.AtomicInteger;import org.junit.Test;import static org.junit.Assert.*;
public class YearFiveDecimalRelationsTest {
 private CurriculumLimits limits(String id){return GlobalCurriculum.limits("england-primary-2021-v1",id,5);}
 @Test public void twoRoundingTargetsCoverEveryHundredthIncludingTiesAndCarries(){
  var pool=DecimalRoundingSupply.candidates(limits("el_decimal_round"));assertEquals(20000,pool.size());Set<Integer> targets=new HashSet<>();for(Question q:pool.values()){String raw=q.prompt.split("을")[0];int target=q.prompt.contains("정수")?0:1;targets.add(target);BigDecimal x=new BigDecimal(raw);assertEquals(2,x.scale());assertTrue(new Checker().check(q,List.of(),List.of(x.setScale(target,RoundingMode.HALF_UP).toPlainString())).correct());}
  assertEquals(Set.of(0,1),targets);Question carry=pool.values().stream().filter(q->q.prompt.startsWith("9.95을 소수")).findFirst().orElseThrow();assertEquals(Checker.Status.INPUT_NEEDED,new Checker().check(carry,List.of(),List.of("10")).status);assertTrue(new Checker().check(carry,List.of(),List.of("10.0")).correct());for(String raw:List.of("0.00","0.05","0.50","9.95","99.99"))for(int target:List.of(0,1)){String prompt=raw+(target==0?"을 가장 가까운 정수로 반올림하면?":"을 소수 첫째 자리까지 반올림하면?");Question q=new Question("el_decimal_round",prompt,"poison","999");HelpPlan h=HelpPlan.forQuestion(q);assertFalse(h.canTransfer());BigDecimal x=new BigDecimal(raw),unit=BigDecimal.ONE.movePointLeft(target),base=x.divideToIntegralValue(unit).multiply(unit);int digit=x.subtract(base).movePointRight(target+1).intValue();List<String> inputs=new ArrayList<>(List.of(raw));if(target>0)inputs.add(""+target);inputs.addAll(List.of(unit.toPlainString(),""+digit,digit>=5?"raise":"keep",base.toPlainString(),digit>=5?unit.toPlainString():"0",x.setScale(target,RoundingMode.HALF_UP).toPlainString()));assertEquals(inputs.size(),h.size());for(int i=0;i<inputs.size();i++){assertTrue(prompt+" step"+i,h.step(i).accepts(inputs.get(i)));assertEquals("",h.step(i).after);}}
 }
 @Test public void allThousandthDigitValuesAndPublicRestorationAreExact(){
  var pool=DecimalPlaceRelations.candidates(limits(DecimalPlaceRelations.ID));assertEquals(40000,pool.size());Set<Integer> positions=new HashSet<>();for(Question q:pool.values()){String raw=q.prompt.substring(0,5);int position=q.prompt.contains("일의 자리")?0:q.prompt.contains("첫째")?1:q.prompt.contains("둘째")?2:3;positions.add(position);int digit=raw.charAt(position==0?0:position+1)-'0';BigDecimal expected=BigDecimal.valueOf(digit).movePointLeft(position);assertTrue(new Checker().check(q,List.of(),List.of(""+digit,expected.toPlainString())).correct());}
  assertEquals(Set.of(0,1,2,3),positions);Question q=new Question(DecimalPlaceRelations.ID,"0.007의 소수 셋째 자리 숫자와 그 숫자가 나타내는 값을 쓰세요.","poison","999","999");HelpPlan h=HelpPlan.forQuestion(q);assertFalse(h.canTransfer());for(int i=0;i<4;i++)assertTrue(h.step(i).accepts(List.of("0.007","7","0.001","0.007").get(i)));
 }
 @Test public void threePlaceComparisonAndDecimalOrderingUseVisibleValuesAndFreshHundred(){
  Generator g=new Generator(new Random(82));Set<String> signs=new HashSet<>();boolean third=false,ascending=false,descending=false;
  for(String id:List.of("el_decimal_compare","decimalOrder")){List<String> recent=new ArrayList<>();for(int i=0;i<150;i++){Question q=g.next(id,recent,false,limits(id));assertFalse(recent.contains(q.signature()));recent.add(q.signature());if(id.equals("el_decimal_compare")){String[] raw=q.prompt.split("\\s+□\\s+");BigDecimal a=new BigDecimal(raw[0]),b=new BigDecimal(raw[1]);third|=a.scale()==3||b.scale()==3;String sign=a.compareTo(b)<0?"<":a.compareTo(b)>0?">":"=";signs.add(sign);assertTrue(new Checker().check(q,List.of(),List.of(sign)).correct());}else{List<String> shown=FractionOrdering.givens(q);assertEquals(3,shown.size());boolean reverse=q.prompt.startsWith("큰");descending|=reverse;ascending|=!reverse;List<String> sorted=new ArrayList<>(shown);sorted.sort((a,b)->new BigDecimal(a).compareTo(new BigDecimal(b))*(reverse?-1:1));assertTrue(new Checker().check(q,List.of(),sorted).correct());Collections.swap(sorted,0,1);assertFalse(new Checker().check(q,List.of(),sorted).correct());Question saved=new Question(id,q.prompt,"poison","999","999","999");HelpPlan h=HelpPlan.forQuestion(saved);assertEquals(3,h.size());assertFalse(h.canTransfer());for(int s=0;s<3;s++){assertEquals(3-s,h.step(s).options.size());assertTrue(shown.contains(saved.studyGuide.frames.get(s).expected));}}}}
  assertTrue(third&&ascending&&descending);assertEquals(Set.of("<","=",">"),signs);
 }
 @Test public void indexedSupplyGeneratesOnlyNeededQuestionsAndStillExhaustsBeforeReuse(){
  AtomicInteger calls=new AtomicInteger();Map<String,Integer> recent=new HashMap<>();Random random=new Random(820);for(int i=0;i<100;i++){Question q=IndexedQuestionSupply.choose(20000,index->{calls.incrementAndGet();return new Question("el_decimal_round","public "+index,"","0");},random,CurriculumLimits.NONE,recent);assertFalse(recent.containsKey(q.signature()));recent.put(q.signature(),i);}assertTrue("100 draws must not allocate two million full questions",calls.get()<10000);
  Map<String,Integer> tiny=new HashMap<>();for(int i=0;i<5;i++)tiny.put("el_decimal_round|public "+i,i);Question oldest=IndexedQuestionSupply.choose(5,index->new Question("el_decimal_round","public "+index,"","0"),random,CurriculumLimits.NONE,tiny);assertEquals("public 0",oldest.prompt);
 }
}
