package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;
/** Compare an operation with its reversed order without requiring untaught negative numbers. */
public final class CalculationOrder {
 private CalculationOrder(){}
 public static final String ADD="additionOrder",SUB="subtractionOrder",VERSION="calculation-order-v1";
 static final String ADD_PROMPT="위 식과 아래 식을 각각 계산하세요.",SUB_PROMPT="아래 식에서 뺄 수가 처음 수보다 크나요?";
 public static final List<Catalog.Skill> SKILLS=List.of(new Catalog.Skill(ADD,"덧셈의 순서 바꾸기",2,1,1,"","calculationOrder",20,"add20","두 수의 순서를 바꿔 더한 결과를 비교한다."),new Catalog.Skill(SUB,"뺄셈의 순서 바꾸기",2,1,1,"","calculationOrder",20,"sub20","순서를 바꾼 식에서 처음 수보다 큰 수를 빼야 하는지 확인한다."));
 public static boolean supports(String id){return ADD.equals(id)||SUB.equals(id);}
 static Map<String,String> options(){Map<String,String> map=new LinkedHashMap<>();map.put("fits","같거나 작아요");map.put("larger","더 커요");return map;}
 static Question make(String id,int a,int b){boolean add=ADD.equals(id);if(!supports(id)||a<0||b<0||a>20||b>20||(add?a+b>20:a<b))throw new IllegalArgumentException("order domain");String op=add?" + ":" − ";Question q=new Question(id,(add?ADD_PROMPT:SUB_PROMPT)+"\n"+a+op+b+"\n"+b+op+a,"",add?new String[]{""+(a+b),""+(a+b)}:new String[]{a>b?"larger":"fits"});q.kind="calculationOrder";q.labels=add?new String[]{"위 식의 값","아래 식의 값"}:new String[]{"비교"};q.stepSupport=false;if(!add)q.choiceLabels.putAll(options());return q;}
 static Question next(String id,Random random,CurriculumLimits limits,Map<String,Integer> recent){Map<String,Question> pool=new LinkedHashMap<>();for(int a=0;a<=20;a++)for(int b=0;b<=20;b++){if(ADD.equals(id)?a+b>20:a<b)continue;Question q=make(id,a,b);if(limits.allows(q))pool.put(q.signature(),q);}Map<String,Question> selected=pool;
  // Equal operands are a small finite subset. While both fresh outcomes exist, sample the
  // outcome first so early practice cannot be solved by always choosing "larger".
  if(SUB.equals(id)){Map<String,Question> equal=new LinkedHashMap<>(),larger=new LinkedHashMap<>();for(var entry:pool.entrySet())if(!recent.containsKey(entry.getKey()))(entry.getValue().answers[0].equals("fits")?equal:larger).put(entry.getKey(),entry.getValue());if(!equal.isEmpty()&&!larger.isEmpty())selected=random.nextBoolean()?equal:larger;else if(!equal.isEmpty())selected=equal;else if(!larger.isEmpty())selected=larger;}
  Question q=FactFoundations.choose(selected,random,recent);attach(q);return q;}
 static int[] read(Question q){if(q==null||!supports(q.skillId)||q.prompt==null)return null;boolean add=ADD.equals(q.skillId);String prefix=(add?ADD_PROMPT:SUB_PROMPT)+"\n",op=add?"\\+":"−";if(!q.prompt.startsWith(prefix))return null;Matcher m=Pattern.compile("(\\d{1,2}) "+op+" (\\d{1,2})\\n(\\d{1,2}) "+op+" (\\d{1,2})").matcher(q.prompt.substring(prefix.length()));if(!m.matches())return null;int a=Integer.parseInt(m.group(1)),b=Integer.parseInt(m.group(2));if(a>20||b>20||Integer.parseInt(m.group(3))!=b||Integer.parseInt(m.group(4))!=a||(add?a+b>20:a<b))return null;return new int[]{a,b};}
 static Checker.Result check(Question q,List<String> answers){int[] v=read(q);if(v==null)return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"문제 확인 필요");if(ADD.equals(q.skillId)){if(answers.size()!=2)return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"두 식의 값 입력 필요");for(int i=0;i<2;i++){if(!answers.get(i).trim().matches("[0-9]{1,2}"))return new Checker.Result(Checker.Status.INPUT_NEEDED,i,"식의 값 입력 필요");if(Integer.parseInt(answers.get(i).trim())!=v[0]+v[1])return new Checker.Result(Checker.Status.WRONG_ANSWER,i,"이 식의 값 확인");}return new Checker.Result(Checker.Status.CORRECT,-1,"정답");}if(answers.size()!=1||!options().containsKey(answers.get(0)))return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"비교 선택 필요");return answers.get(0).equals(v[0]>v[1]?"larger":"fits")?new Checker.Result(Checker.Status.CORRECT,-1,"정답"):new Checker.Result(Checker.Status.WRONG_ANSWER,0,"이 비교 확인");}
 public static void attach(Question q){int[] v=read(q);if(v==null)return;StudyGuide g=new StudyGuide().transfer(false);g.teachingVersion=VERSION;if(ADD.equals(q.skillId))g.step("위 식의 첫 수를 쓰세요.","위 식의 첫 수 = ","",""+v[0]).step("위 식의 둘째 수를 쓰세요.","위 식의 둘째 수 = ","",""+v[1]).step("위 식을 계산하세요.","위 식의 첫 수 + 위 식의 둘째 수 = ","",""+(v[0]+v[1])).step("아래 식을 계산하세요.","아래 식의 첫 수 + 아래 식의 둘째 수 = ","",""+(v[0]+v[1]));else{g.step("아래 식의 처음 수를 쓰세요.","처음 수 = ","",""+v[1]).step("아래 식의 뺄 수를 쓰세요.","뺄 수 = ","",""+v[0]).choice("뺄 수를 처음 수와 비교하세요.",options(),v[0]>v[1]?"larger":"fits");}q.studyGuide=g;}
}
