package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;
/** Two-operation contexts and equality as equal values, checked from public givens. */
public final class CombinedEqualityPractice {
 private CombinedEqualityPractice(){}
 public static final String STORY="combinedOperationStories",EQUAL="equalOperationSides";
 public static final List<Catalog.Skill> SKILLS=List.of(new Catalog.Skill(STORY,"두 단계로 구하는 연필 수",5,1,1,"",STORY,1000,"tables,divide,add100,sub100","묶음이나 나눔의 수를 구한 뒤 늘거나 줄어든 수를 계산한다."),new Catalog.Skill(EQUAL,"등호 양쪽을 같게 만들기",5,1,1,"",EQUAL,2000,"tables,divide,add100,sub100","등호는 양쪽 값이 같다는 뜻이다. 왼쪽을 계산하고 오른쪽의 빈 수를 구한다."));
 public static boolean supports(String id){return STORY.equals(id)||EQUAL.equals(id);}
 static final String[] OPS={"+","−","×","÷"};
 static int calculate(int a,int b,int op){return switch(op){case 0->a+b;case 1->a-b;case 2->a*b;case 3->a/b;default->throw new IllegalArgumentException("operation");};}
 static int blank(int target,int k,int op){return switch(op){case 0->target-k;case 1->target+k;case 2->target%k==0?target/k:-1;case 3->target*k;default->-1;};}
 static final Map<String,List<int[]>> DOMAINS=new HashMap<>();
 static {List<int[]> stories=new ArrayList<>(),equations=new ArrayList<>();for(int mode=0;mode<4;mode++)for(int a=2;a<=12;a++)for(int b=1;b<=30;b++){int first=mode<2?a*b:b;for(int c=0;c<=30;c++)if(mode%2==0||c<=first)stories.add(new int[]{mode,a,b,c});}for(int a=1;a<=30;a++)for(int b=2;b<=12;b++)for(int op=0;op<4;op++){if(op==1&&a<b||op==3&&a%b!=0)continue;int target=calculate(a,b,op);for(int k=2;k<=12;k++)for(int right=0;right<4;right++)if(blank(target,k,right)>=0)equations.add(new int[]{a,b,op,k,right});}DOMAINS.put(STORY,List.copyOf(stories));DOMAINS.put(EQUAL,List.copyOf(equations));}
 static int count(String id){return DOMAINS.get(id).size();}
 static String story(int mode,int a,int b,int c){String first=mode<2?"한 봉지에 연필이 "+a+"자루씩, "+b+"봉지 있습니다.":"연필 "+(a*b)+"자루를 "+a+"명에게 똑같이 나누어 줍니다.";String change=mode<2?(mode%2==0?"연필 "+c+"자루를 더 받았습니다.":"연필 "+c+"자루를 사용했습니다."):(mode%2==0?"각자 연필 "+c+"자루를 더 받았습니다.":"각자 연필 "+c+"자루를 사용했습니다.");return first+"\n"+change+"\n"+(mode<2?"남은 연필은 모두 몇 자루인가요?":"한 사람에게 남은 연필은 몇 자루인가요?");}
 static Question at(String id,int index){int[] v=DOMAINS.get(id).get(index);String prompt=STORY.equals(id)?story(v[0],v[1],v[2],v[3]):"양쪽 값이 같도록 빈칸을 채우세요.\n"+v[0]+" "+OPS[v[2]]+" "+v[1]+" = □ "+OPS[v[4]]+" "+v[3];Question q=new Question(id,prompt,"",""+answer(id,v));q.stepSupport=false;attach(q);return q.withInputs(Arrays.stream(v).asLongStream().toArray());}
 public static int[] read(Question q){if(q==null||q.prompt==null||!supports(q.skillId))return null;try{if(EQUAL.equals(q.skillId)){Matcher m=Pattern.compile("양쪽 값이 같도록 빈칸을 채우세요\\.\\n(\\d+) ([+−×÷]) (\\d+) = □ ([+−×÷]) (\\d+)").matcher(q.prompt);if(!m.matches())return null;int a=Integer.parseInt(m.group(1)),b=Integer.parseInt(m.group(3)),op=Arrays.asList(OPS).indexOf(m.group(2)),right=Arrays.asList(OPS).indexOf(m.group(4)),k=Integer.parseInt(m.group(5));if(a<1||a>30||b<2||b>12||k<2||k>12||op==1&&a<b||op==3&&a%b!=0||blank(calculate(a,b,op),k,right)<0)return null;return new int[]{a,b,op,k,right};}
 Matcher m=Pattern.compile("한 봉지에 연필이 (\\d+)자루씩, (\\d+)봉지 있습니다\\.\\n연필 (\\d+)자루를 (더 받았습니다|사용했습니다)\\.\\n남은 연필은 모두 몇 자루인가요\\?").matcher(q.prompt);int mode,a,b,c;if(m.matches()){mode=m.group(4).equals("더 받았습니다")?0:1;a=Integer.parseInt(m.group(1));b=Integer.parseInt(m.group(2));c=Integer.parseInt(m.group(3));}else{m=Pattern.compile("연필 (\\d+)자루를 (\\d+)명에게 똑같이 나누어 줍니다\\.\\n각자 연필 (\\d+)자루를 (더 받았습니다|사용했습니다)\\.\\n한 사람에게 남은 연필은 몇 자루인가요\\?").matcher(q.prompt);if(!m.matches())return null;int total=Integer.parseInt(m.group(1));a=Integer.parseInt(m.group(2));if(a==0||total%a!=0)return null;b=total/a;c=Integer.parseInt(m.group(3));mode=m.group(4).equals("더 받았습니다")?2:3;}if(a<2||a>12||b<1||b>30||c<0||c>30||mode%2==1&&c>(mode<2?a*b:b))return null;return new int[]{mode,a,b,c};}catch(NumberFormatException ex){return null;}}
 static int answer(String id,int[] v){if(EQUAL.equals(id))return blank(calculate(v[0],v[1],v[2]),v[3],v[4]);int first=v[0]<2?v[1]*v[2]:v[2];return v[0]%2==0?first+v[3]:first-v[3];}
 static Question next(String id,Random random,CurriculumLimits limits,Map<String,Integer> recent){return IndexedQuestionSupply.choose(count(id),i->at(id,i),random,limits,recent);}
 static Checker.Result check(Question q,List<String> answers){int[] v=read(q);if(v==null||answers==null||answers.size()!=1||answers.get(0)==null)return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"수 입력 필요");String raw=answers.get(0).trim().replace('−','-');if(!raw.matches("[+-]?\\d{1,6}"))return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"수 입력 필요");boolean same=Integer.parseInt(raw)==answer(q.skillId,v);return new Checker.Result(same?Checker.Status.CORRECT:Checker.Status.WRONG_ANSWER,same?-1:0,same?"계산 확인 완료":"이 수 확인");}
 private static void step(StudyGuide h,String instruction,String relation,int expected){h.step(instruction,relation+" = ","",""+expected);}
 public static void attach(Question q){int[] v=read(q);if(v==null)return;StudyGuide h=new StudyGuide().transfer(false);h.teachingVersion="combined-equality-v1";if(STORY.equals(q.skillId)){boolean group=v[0]<2,add=v[0]%2==0;step(h,group?"한 봉지의 연필 수를 쓰세요.":"나누기 전의 전체 연필 수를 쓰세요.","첫 수 a",group?v[1]:v[1]*v[2]);step(h,group?"봉지 수를 쓰세요.":"연필을 받는 사람 수를 쓰세요.","둘째 수 b",group?v[2]:v[1]);step(h,group?"봉지에 든 전체 연필 수를 구하세요.":"한 사람에게 나누어 준 수를 구하세요.","처음 결과 L = a "+(group?"×":"÷")+" b",group?v[1]*v[2]:v[2]);step(h,"더 받거나 사용한 연필 수를 쓰세요.","변한 수 c",v[3]);step(h,add?"더 받은 수를 더해 남은 수를 구하세요.":"사용한 수를 빼서 남은 수를 구하세요.","남은 수 T = L "+(add?"+":"−")+" c",answer(q.skillId,v));}else{step(h,"왼쪽 식의 첫 수를 쓰세요.","첫 수 a",v[0]);step(h,"왼쪽 식의 둘째 수를 쓰세요.","둘째 수 b",v[1]);step(h,"왼쪽 식의 값을 계산하세요.","왼쪽 값 L = a "+OPS[v[2]]+" b",calculate(v[0],v[1],v[2]));step(h,"오른쪽 식에서 알고 있는 수를 쓰세요.","알고 있는 수 k",v[3]);String inverse=switch(v[4]){case 0->"L − k";case 1->"L + k";case 2->"L ÷ k";default->"L × k";};step(h,"등호 양쪽은 같은 값입니다. 오른쪽 계산을 거꾸로 하여 빈 수를 구하세요.","빈 수 x = "+inverse,answer(q.skillId,v));}q.studyGuide=h;}
 public static String[] referenceLabels(String id){return STORY.equals(id)?new String[]{"첫 수 a","둘째 수 b","처음 결과 L","변한 수 c","남은 수 T"}:new String[]{"첫 수 a","둘째 수 b","왼쪽 값 L","알고 있는 수 k","빈 수 x"};}
 public static int[] referenceIndices(int stage){return stage==2?new int[]{0,1}:stage==4?new int[]{2,3}:new int[0];}
}
