package com.gomgomapps.math.core;
import java.math.BigDecimal;import java.util.*;import java.util.regex.*;
/** Finite power-of-ten calculations reuse public decimal arithmetic frames. */
public final class DecimalPowerTen {
 private DecimalPowerTen(){}
 public static final String MUL="decimalTimesPowersTen",DIV="decimalDividePowersTen";
 public static final List<Catalog.Skill> SKILLS=List.of(new Catalog.Skill(MUL,"10·100·1000을 곱하기",6,1,1,"","decimalPowerTen",1000,"decimalMul","자리 단위의 크기 변화를 곱셈으로 계산한다."),new Catalog.Skill(DIV,"10·100·1000으로 나누기",6,1,1,"","decimalPowerTen",1000,"decimalDivInt","자리 단위의 크기 변화를 나눗셈으로 계산한다."));
 public static boolean supports(String id){return MUL.equals(id)||DIV.equals(id);}
 private static int inputPlaces(int exponent,CurriculumLimits limits){return Math.min(3,Math.max(0,limits.answerDecimalPlaces(3)-exponent));}
 private static int block(int exponent,CurriculumLimits limits){return (limits.wholeMaximum(99)+1)*(int)Math.pow(10,inputPlaces(exponent,limits));}
 static int count(String id,CurriculumLimits limits){int max=limits.wholeMaximum(99);if(!supports(id)||max<0||max>99||limits.answerDecimalPlaces(3)<3)throw new IllegalArgumentException("Selected decimal power bounds");return MUL.equals(id)?(max+1)*3000:block(1,limits)+block(2,limits)+block(3,limits);}
 static Question at(String id,int index,CurriculumLimits limits){if(!supports(id)||index<0||index>=count(id,limits))throw new IllegalArgumentException("Selected decimal power index");int max=limits.wholeMaximum(99),e,units,p;if(MUL.equals(id)){int block=(max+1)*1000;e=index/block+1;units=index%block;p=3;}else{e=1;while(index>=block(e,limits)){index-=block(e,limits);e++;}units=index;p=inputPlaces(e,limits);}BigDecimal value=BigDecimal.valueOf(units,p);return make(id,(limits.answerDecimalPlaces(3)>3?value.stripTrailingZeros():value).toPlainString(),(int)Math.pow(10,e));}
 public static Question make(String id,String raw,int power){BigDecimal x=new BigDecimal(raw);if(!supports(id)||!raw.matches("\\d+(?:\\.\\d{1,3})?")||!Set.of(10,100,1000).contains(power)||x.signum()<0||x.compareTo(new BigDecimal("99.999"))>0)throw new IllegalArgumentException("Selected decimal power givens");BigDecimal y=BigDecimal.valueOf(power),answer=MUL.equals(id)?x.multiply(y):x.divide(y);String op=MUL.equals(id)?" × ":" ÷ ";Question q=new Question(id,raw+op+power,raw+(MUL.equals(id)?" * ":" / ")+power,answer.stripTrailingZeros().toPlainString());q.decimal=true;q.answerFormat="decimalValue";q.stepSupport=false;attach(q);return q.withInputs(Expression.number(raw),Rational.of(power));}
 static Checker.Result check(Question q,List<String> answers){
  try{Matcher m=Pattern.compile("(\\d+(?:\\.\\d{1,3})?) ([×÷]) (10|100|1000)").matcher(q.prompt);if(!m.matches()||!m.group(2).equals(MUL.equals(q.skillId)?"×":"÷"))throw new IllegalArgumentException();Question visible=make(q.skillId,m.group(1),Integer.parseInt(m.group(3)));if(answers.isEmpty()||!answers.get(0).trim().matches("[+-]?\\d+(?:\\.\\d+)?"))return new Checker.Result(Checker.Status.INPUT_NEEDED,-1,"답 입력 필요");boolean same=Expression.number(answers.get(0).trim()).equals(Expression.number(visible.answers[0]));return new Checker.Result(same?Checker.Status.CORRECT:Checker.Status.WRONG_ANSWER,same?-1:0,same?"계산 확인 완료":"이 답 확인");}catch(IllegalArgumentException|ArithmeticException ex){return new Checker.Result(Checker.Status.INPUT_NEEDED,-1,"수식 입력 확인 필요");}
 }
 static Question next(Catalog.Skill s,Random random,CurriculumLimits limits,Map<String,Integer> recent){return IndexedQuestionSupply.choose(count(s.id,limits),i->at(s.id,i,limits),random,limits,recent);}
 public static void attach(Question q){if(q==null||!supports(q.skillId)||q.prompt==null)return;Matcher m=Pattern.compile("(\\d+(?:\\.\\d+)?) ([×÷]) (10|100|1000)").matcher(q.prompt);if(!m.matches()||!m.group(2).equals(MUL.equals(q.skillId)?"×":"÷"))return;Question publicOnly=new Question(MUL.equals(q.skillId)?"decimalMul":"decimalDivInt",q.prompt,"","poison");DecimalArithmeticRelations.attach(publicOnly);q.studyGuide=publicOnly.studyGuide;}
}
