package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;
/** Factor/multiple and square/cube applications, solved from visible quantities. */
public final class FactorPowerStories {
 private FactorPowerStories(){}
 public static final String FACTOR="factorPackingBags",MULTIPLE="multipleProductionTarget",SQUARE="squareTileBoards",CUBE="cubeBlockPacking";
 public static final List<Catalog.Skill> SKILLS=List.of(new Catalog.Skill(FACTOR,"약수로 포장하기",5,1,1,"",FACTOR,999,"el_divisor,divide","남는 물건 없이 포장할 수 있는 크기는 전체 수의 약수이다."),new Catalog.Skill(MULTIPLE,"배수로 생산량 맞추기",5,1,1,"",MULTIPLE,999,"el_multiple,divide","정해진 수씩 생산한 전체 수는 한 번의 생산량의 배수이다."),new Catalog.Skill(SQUARE,"정사각형 판의 타일 수",5,1,1,"",SQUARE,999,"squareWhole,tables","정사각형 한 판의 타일 수에 판 수를 곱한다."),new Catalog.Skill(CUBE,"정육면체 블록 포장",5,1,1,"",CUBE,27000,"cubeWhole,divide","같은 블록으로 만든 정육면체의 전체 수를 포장 크기로 나눈다."));
 static final List<int[]> FACTORS=new ArrayList<>(),CUBES=new ArrayList<>();
 static {for(int n=2;n<=999;n++)for(int a=2;a<=12;a++)for(int b=a+1;b<=12;b++)if((n%a==0)!=(n%b==0))FACTORS.add(new int[]{n,a,b});for(int side=2;side<=30;side++)for(int capacity=2;capacity<=100;capacity++)if(side*side*side%capacity==0)CUBES.add(new int[]{side,capacity});}
 public static boolean supports(String id){return Set.of(FACTOR,MULTIPLE,SQUARE,CUBE).contains(id);}
 static int count(String id){return FACTOR.equals(id)?FACTORS.size():MULTIPLE.equals(id)?11*999:SQUARE.equals(id)?30*99:CUBE.equals(id)?CUBES.size():0;}
 static Question at(String id,int index){if(index<0||index>=count(id))throw new IllegalArgumentException("Factor power story index");if(FACTOR.equals(id)){int[] v=FACTORS.get(index);return make(id,v[0],v[1],v[2]);}if(MULTIPLE.equals(id))return make(id,index/999+2,index%999+1,0);if(SQUARE.equals(id))return make(id,index/99+1,index%99+1,0);int[] v=CUBES.get(index);return make(id,v[0],v[1],0);}
 public static Question make(String id,int a,int b,int c){String prompt=switch(id){case FACTOR->"구슬 "+a+"개를 한 봉지에 "+b+"개 또는 "+c+"개씩 담습니다.\n구슬을 남기지 않고 모두 담을 수 있는 크기를 고릅니다.\n봉지는 몇 개 필요한가요?";case MULTIPLE->"빵을 한 번에 "+a+"개씩 만듭니다.\n적어도 "+b+"개가 필요합니다.\n만들 수 있는 가장 적은 빵 수는 몇 개인가요?";case SQUARE->"정사각형 판 한 장에는 타일이 한 줄에 "+a+"개씩, "+a+"줄 있습니다.\n이런 판이 "+b+"장 있습니다.\n전체 타일은 몇 개인가요?";case CUBE->"작은 블록으로 정육면체를 만듭니다.\n가로·세로·높이에 각각 "+a+"개씩 놓습니다.\n블록을 한 상자에 "+b+"개씩 남김없이 담습니다.\n상자는 몇 개 필요한가요?";default->throw new IllegalArgumentException("Story skill");};Question q=new Question(id,prompt,"","pending");int[] v=read(q);if(v==null)throw new IllegalArgumentException("Story domain");q.answers=new String[]{""+answer(id,v)};q.stepSupport=false;attach(q);return q.withInputs(a,b,c);}
 private static final Pattern F=Pattern.compile("구슬 (\\d+)개를 한 봉지에 (\\d+)개 또는 (\\d+)개씩 담습니다\\.\\n구슬을 남기지 않고 모두 담을 수 있는 크기를 고릅니다\\.\\n봉지는 몇 개 필요한가요\\?"),M=Pattern.compile("빵을 한 번에 (\\d+)개씩 만듭니다\\.\\n적어도 (\\d+)개가 필요합니다\\.\\n만들 수 있는 가장 적은 빵 수는 몇 개인가요\\?"),S=Pattern.compile("정사각형 판 한 장에는 타일이 한 줄에 (\\d+)개씩, (\\d+)줄 있습니다\\.\\n이런 판이 (\\d+)장 있습니다\\.\\n전체 타일은 몇 개인가요\\?"),C=Pattern.compile("작은 블록으로 정육면체를 만듭니다\\.\\n가로·세로·높이에 각각 (\\d+)개씩 놓습니다\\.\\n블록을 한 상자에 (\\d+)개씩 남김없이 담습니다\\.\\n상자는 몇 개 필요한가요\\?");
 public static int[] read(Question q){if(q==null||q.prompt==null||!supports(q.skillId))return null;Matcher m=(FACTOR.equals(q.skillId)?F:MULTIPLE.equals(q.skillId)?M:SQUARE.equals(q.skillId)?S:C).matcher(q.prompt);if(!m.matches())return null;try{int a=Integer.parseInt(m.group(1)),b=Integer.parseInt(m.group(2)),c=(FACTOR.equals(q.skillId)||SQUARE.equals(q.skillId))?Integer.parseInt(m.group(3)):0;if(FACTOR.equals(q.skillId))return a>=2&&a<=999&&b>=2&&b<c&&c<=12&&((a%b==0)!=(a%c==0))?new int[]{a,b,c}:null;if(MULTIPLE.equals(q.skillId))return a>=2&&a<=12&&b>=1&&b<=999?new int[]{a,b}:null;if(SQUARE.equals(q.skillId))return a>=1&&a<=30&&a==b&&c>=1&&c<=99?new int[]{a,c}:null;return a>=2&&a<=30&&b>=2&&b<=100&&a*a*a%b==0?new int[]{a,b}:null;}catch(NumberFormatException ex){return null;}}
 static int answer(String id,int[] v){return FACTOR.equals(id)?v[0]/(v[0]%v[1]==0?v[1]:v[2]):MULTIPLE.equals(id)?((v[1]+v[0]-1)/v[0])*v[0]:SQUARE.equals(id)?v[0]*v[0]*v[1]:v[0]*v[0]*v[0]/v[1];}
 static Question next(String id,Random random,CurriculumLimits limits,Map<String,Integer> recent){return IndexedQuestionSupply.choose(count(id),i->at(id,i),random,limits,recent);}
 static Checker.Result check(Question q,List<String> answers){int[] v=read(q);if(v==null||answers==null||answers.size()!=1)return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"수 입력 필요");String raw=answers.get(0).trim().replace('−','-');if(!raw.matches("[+-]?\\d{1,6}"))return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"수 입력 필요");boolean same=Integer.parseInt(raw)==answer(q.skillId,v);return new Checker.Result(same?Checker.Status.CORRECT:Checker.Status.WRONG_ANSWER,same?-1:0,same?"계산 확인 완료":"이 수 확인");}
 public static void attach(Question q){int[] v=read(q);if(v==null)return;StudyGuide h=new StudyGuide().transfer(false);h.teachingVersion="factor-power-stories-v1";
  if(FACTOR.equals(q.skillId)){int d=v[0]%v[1]==0?v[1]:v[2];step(h,"전체 구슬 수를 쓰세요.","전체 수 N",v[0]);step(h,"작은 포장 크기를 쓰세요.","작은 크기 a",v[1]);step(h,"큰 포장 크기를 쓰세요.","큰 크기 b",v[2]);step(h,"전체 수를 작은 크기로 나눈 나머지를 쓰세요.","나머지 r = N ÷ a의 나머지",v[0]%v[1]);step(h,"전체 수를 큰 크기로 나눈 나머지를 쓰세요.","나머지 s = N ÷ b의 나머지",v[0]%v[2]);step(h,"나머지가 0인 포장 크기를 쓰세요.","남김없는 크기 d",d);step(h,"전체 수를 선택한 크기로 나누세요.","봉지 수 Q = N ÷ d",answer(q.skillId,v));}
  else if(MULTIPLE.equals(q.skillId)){step(h,"한 번에 만드는 빵 수를 쓰세요.","한 번의 수 a",v[0]);step(h,"적어도 필요한 빵 수를 쓰세요.","필요한 수 N",v[1]);step(h,"필요한 수를 한 번의 수로 나눈 정수 몫을 쓰세요.","정수 몫 q = N ÷ a의 정수 몫",v[1]/v[0]);step(h,"정수 몫만큼 만들고도 부족하면 1, 충분하면 0을 쓰세요.","추가 횟수 e",v[1]%v[0]==0?0:1);step(h,"정수 몫에 추가 횟수를 더하고 한 번의 수를 곱하세요.","최소 빵 수 T = (q + e) × a",answer(q.skillId,v));}
  else{step(h,SQUARE.equals(q.skillId)?"한 줄의 타일 수를 쓰세요.":"한 모서리의 블록 수를 쓰세요.","한 변의 수 a",v[0]);step(h,SQUARE.equals(q.skillId)?"판 수를 쓰세요.":"한 상자의 블록 수를 쓰세요.",SQUARE.equals(q.skillId)?"판 수 B":"상자 크기 d",v[1]);step(h,"같은 수 두 개를 곱해 한 층의 수를 구하세요.","한 층의 수 L = a × a",v[0]*v[0]);if(CUBE.equals(q.skillId))step(h,"한 층의 수에 층 수를 곱하세요.","전체 블록 수 V = L × a",v[0]*v[0]*v[0]);step(h,SQUARE.equals(q.skillId)?"한 판의 타일 수에 판 수를 곱하세요.":"전체 블록 수를 상자 크기로 나누세요.",SQUARE.equals(q.skillId)?"전체 타일 수 T = L × B":"상자 수 Q = V ÷ d",answer(q.skillId,v));}q.studyGuide=h;
 }
 private static void step(StudyGuide h,String instruction,String relation,int expected){h.step(instruction,relation+" = ","",""+expected);}
 public static int[] referenceIndices(String id,int stage){if(FACTOR.equals(id)){if(stage==3)return new int[]{0,1};if(stage==4)return new int[]{0,2};if(stage==5)return new int[]{1,2,3,4};if(stage==6)return new int[]{0,5};}if(MULTIPLE.equals(id)&&stage==4)return new int[]{0,2,3};if(SQUARE.equals(id)&&stage==3)return new int[]{1,2};if(CUBE.equals(id)&&stage==3)return new int[]{0,2};if(CUBE.equals(id)&&stage==4)return new int[]{1,3};return java.util.stream.IntStream.range(0,Math.min(stage,referenceLabels(id).length)).toArray();}
 public static String[] referenceLabels(String id){return FACTOR.equals(id)?new String[]{"전체 수 N","작은 크기 a","큰 크기 b","나머지 r","나머지 s","남김없는 크기 d","봉지 수 Q"}:MULTIPLE.equals(id)?new String[]{"한 번의 수 a","필요한 수 N","정수 몫 q","추가 횟수 e","최소 빵 수 T"}:SQUARE.equals(id)?new String[]{"한 변의 수 a","판 수 B","한 층의 수 L","전체 타일 수 T"}:new String[]{"한 변의 수 a","상자 크기 d","한 층의 수 L","전체 블록 수 V","상자 수 Q"};}
}
