package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;
/** One-whole length contexts, checked from their public quantities. */
public final class FractionLengthStories {
 private FractionLengthStories(){}
 public static final String ADD="fractionLengthUsed",SUB="fractionLengthLeft";
 public static final List<Catalog.Skill> SKILLS=List.of(
  new Catalog.Skill(ADD,"끈을 사용한 길이",3,1,6,"","fractionLengthStory",12,"fracAddLike","같은 끈에서 두 번 사용한 길이를 분수로 더한다."),
  new Catalog.Skill(SUB,"끈을 사용하고 남은 길이",3,1,6,"","fractionLengthStory",12,"fracSubLike","가진 끈의 길이에서 사용한 길이를 분수로 뺀다."));
 public static boolean supports(String id){return ADD.equals(id)||SUB.equals(id);}
 public static String template(String id){return ADD.equals(id)?"길이가 1m인 끈에서 오전에 %s/%sm, 오후에 %s/%sm를 사용했어요.\n모두 사용한 길이는 몇 m인가요?":SUB.equals(id)?"길이가 %s/%sm인 끈에서 %s/%sm를 사용했어요.\n남은 길이는 몇 m인가요?":null;}
 private static final Map<String,Pattern> PATTERNS=new HashMap<>();static{for(Catalog.Skill s:SKILLS)PATTERNS.put(s.id,Pattern.compile("^"+Pattern.quote(template(s.id)).replace("%s","\\E([0-9]{1,2})\\Q")+"$"));}
 public static String[] displayed(String id,String prompt){if(!supports(id)||prompt==null)return null;Matcher m=PATTERNS.get(id).matcher(prompt);return m.matches()?new String[]{m.group(1),m.group(2),m.group(3),m.group(4)}:null;}
 static Question make(String id,int d,int a,int b){if(!supports(id)||d<2||d>12||a<1||b<1||a>d||b>d||(ADD.equals(id)?a+b>d:b>a))throw new IllegalArgumentException("Length fraction domain");int result=ADD.equals(id)?a+b:a-b;Question q=new Question(id,String.format(Locale.ROOT,template(id),a,d,b,d),"",Rational.of(result,d).toString());q.labels=new String[]{"길이"};q.answerFormat="fraction";q.stepSupport=false;attach(q);return q;}
 public static int[] read(Question q){if(q==null)return null;String[] s=displayed(q.skillId,q.prompt);if(s==null)return null;int a=Integer.parseInt(s[0]),d=Integer.parseInt(s[1]),b=Integer.parseInt(s[2]),e=Integer.parseInt(s[3]);if(d!=e||d<2||d>12||a<1||b<1||a>d||b>d||(ADD.equals(q.skillId)?a+b>d:b>a))return null;return new int[]{d,a,b,ADD.equals(q.skillId)?a+b:a-b};}
 static Question next(String id,Random random,CurriculumLimits limits,Map<String,Integer> recent){Map<String,Question> pool=new LinkedHashMap<>();for(int d=2;d<=12;d++)for(int a=1;a<=d;a++)for(int b=1;b<=d;b++)if(ADD.equals(id)?a+b<=d:b<=a){Question q=make(id,d,a,b);if(limits.allows(q))pool.put(q.signature(),q);}return FactFoundations.choose(pool,random,recent);}
 static Checker.Result check(Question q,List<String> answers){int[] v=read(q);if(v==null||answers==null||answers.size()!=1||answers.get(0)==null)return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"답 입력 필요");String raw=Expression.normalize(answers.get(0).trim());if(!raw.matches("[+-]?\\d+(?:\\.\\d+)?(?:/[+-]?\\d+)?"))return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"마지막 답은 수로 입력");try{return Expression.number(raw).equals(Rational.of(v[3],v[0]))?new Checker.Result(Checker.Status.CORRECT,-1,"정답"):new Checker.Result(Checker.Status.WRONG_ANSWER,0,"이 답 확인");}catch(IllegalArgumentException|ArithmeticException error){return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"답의 기호 확인 필요");}}
 public static int errorPart(Question q,String raw){int[] v=read(q);String[] parts=raw==null?null:FractionInput.parts(raw);if(v==null||parts==null)return 0;try{java.math.BigInteger n=new java.math.BigInteger(parts[0]),d=new java.math.BigInteger(parts[1]),base=java.math.BigInteger.valueOf(v[0]),num=java.math.BigInteger.valueOf(v[3]);if(d.signum()<=0)return 2;java.math.BigInteger[] scaled=d.multiply(num).divideAndRemainder(base);if(scaled[1].signum()==0)return n.equals(scaled[0])?0:1;if(num.signum()==0)return 1;return n.multiply(base).divideAndRemainder(num)[1].signum()==0?2:0;}catch(NumberFormatException error){return 0;}}
 public static void attach(Question q){int[] v=read(q);if(v==null)return;StudyGuide g=new StudyGuide().transfer(false);g.teachingVersion="fraction-length-stories-v1";String[] roles=ADD.equals(q.skillId)?new String[]{"분모","오전에 사용한 길이의 분자","오후에 사용한 길이의 분자"}:new String[]{"분모","가진 길이의 분자","사용한 길이의 분자"};for(int i=0;i<3;i++)g.step(roles[i]+"를 쓰세요.",roles[i]+" = ","",Integer.toString(v[i]));g.step("같은 분모를 유지하고 분자를 계산하세요.",roles[1]+(ADD.equals(q.skillId)?" + ":" − ")+roles[2]+" = ","",Integer.toString(v[3]));q.studyGuide=g;}
}
