package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;
/** Compose existing mental place/make-ten teaching for larger sums, without answer transfer. */
public final class MentalSumStrategies {
 private MentalSumStrategies(){}
 public static final String ADD="mentalTwoDigitAddition",SUB="mentalTwoDigitSubtraction",THREE="mentalThreeNumberSum",VERSION="mental-sum-strategies-v1";
 public static final List<Catalog.Skill> SKILLS=List.of(new Catalog.Skill(ADD,"십과 일로 나눠 더하기",2,1,1,"","mentalSum",99,"mentalPlaceAddition","둘째 수를 십과 일로 나눠 차례로 더한다."),new Catalog.Skill(SUB,"십과 일로 나눠 빼기",2,1,1,"","mentalSum",99,"mentalPlaceSubtraction","둘째 수를 십과 일로 나눠 차례로 뺀다."),new Catalog.Skill(THREE,"세 수 묶어 더하기",2,1,1,"","mentalSum",9,"addThree9,add20","10을 만드는 두 수가 있으면 먼저 묶고 나머지 수를 더한다."));
 public static boolean supports(String id){return Set.of(ADD,SUB,THREE).contains(id);}
 static Question make(String id,int a,int b,int c){boolean three=THREE.equals(id),add=!SUB.equals(id);if(!supports(id)||(three?a<0||a>9||b<0||b>9||c<0||c>9:a<10||a>99||b<10||b>99||c!=0||!add&&a<b))throw new IllegalArgumentException("mental sum domain");Question q=new Question(id,three?a+" + "+b+" + "+c:a+(add?" + ":" - ")+b,"",""+(three?a+b+c:add?a+b:a-b));q.kind="mentalSum";q.labels=new String[]{"답"};q.stepSupport=false;attach(q);return q;}
 static Question create(Catalog.Skill s,Random r,CurriculumLimits limits){if(THREE.equals(s.id))return make(s.id,r.nextInt(10),r.nextInt(10),r.nextInt(10));int a=10+r.nextInt(90),b=10+r.nextInt(SUB.equals(s.id)?a-9:90);return make(s.id,a,b,0);}
 static Question next(Catalog.Skill s,Random r,CurriculumLimits limits,Map<String,Integer> recent){Map<String,Question> pool=new LinkedHashMap<>();for(int i=0;i<64;i++){Question q=create(s,r,limits);if(limits.allows(q))pool.put(q.signature(),q);}return FactFoundations.choose(pool,r,recent);}
 public static int[] read(Question q){if(q==null||!supports(q.skillId)||q.prompt==null)return null;Matcher m=Pattern.compile(THREE.equals(q.skillId)?"([0-9]) \\+ ([0-9]) \\+ ([0-9])":"([0-9]{2}) ([+−-]) ([0-9]{2})").matcher(q.prompt);if(!m.matches())return null;if(THREE.equals(q.skillId))return new int[]{Integer.parseInt(m.group(1)),Integer.parseInt(m.group(2)),Integer.parseInt(m.group(3))};boolean add=ADD.equals(q.skillId);int a=Integer.parseInt(m.group(1)),b=Integer.parseInt(m.group(3));return (add==m.group(2).equals("+")&&a>=10&&b>=10&&(add||a>=b))?new int[]{a,b,0}:null;}
 static int[] pair(int[] v){int[][] pairs={{0,1,2},{0,2,1},{1,2,0}};for(int[] p:pairs)if(v[p[0]]+v[p[1]]==10)return p;return pairs[0];}
 private static StudyGuide part(int a,int b,boolean add){if(a>=10&&b>0)return MentalPlaceCalculations.make(add?MentalPlaceCalculations.ADD:MentalPlaceCalculations.SUB,a,b).studyGuide;Question q=new Question(add?"add9":"sub9",a+(add?" + ":" - ")+b,"","");WholeNumberRelations.attach(q);return q.studyGuide;}
 private static void append(StudyGuide destination,StudyGuide part,String prefix,String finalInstruction){for(int i=0;i<part.frames.size();i++){StudyGuide.Frame frame=part.frames.get(i);frame.instruction=prefix+" · "+(i==part.frames.size()-1?finalInstruction:frame.instruction);destination.frames.add(frame);}}
 public static void attach(Question q){int[] v=read(q);if(v==null)return;StudyGuide g=new StudyGuide().transfer(false);g.teachingVersion=VERSION;
  if(THREE.equals(q.skillId)){int[] p=pair(v);String[] names={"첫째","둘째","셋째"};int first=v[p[0]],second=v[p[1]],remaining=v[p[2]],subtotal=first+second;append(g,part(first,second,true),names[p[0]]+"·"+names[p[1]]+" 수 묶기","두 수의 합을 쓰세요.");g.step(names[p[2]]+" 수를 쓰세요.","남은 수 = ","",""+remaining);append(g,part(subtotal,remaining,true),"마지막 더하기","최종 계산 결과를 쓰세요.");}
  else{boolean add=ADD.equals(q.skillId);int tens=v[1]/10*10,ones=v[1]%10,intermediate=add?v[0]+tens:v[0]-tens;g.step("둘째 수의 십 자리값을 쓰세요.","십 자리값 = ","",""+tens);g.step("둘째 수에서 십 자리값을 빼세요.","둘째 수 − 십 자리값 = ","",""+ones);append(g,part(v[0],tens,add),"십 계산",ones==0?"최종 계산 결과를 쓰세요.":"십 계산 결과를 쓰세요.");if(ones>0)append(g,part(intermediate,ones,add),"일 계산","최종 계산 결과를 쓰세요.");}q.studyGuide=g;
 }
 static Checker.Result check(Question q,List<String> answers){int[] v=read(q);if(v==null||answers.size()!=1||!answers.get(0).trim().matches("[0-9]{1,3}"))return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"답 입력 필요");int result=THREE.equals(q.skillId)?v[0]+v[1]+v[2]:ADD.equals(q.skillId)?v[0]+v[1]:v[0]-v[1];return Integer.parseInt(answers.get(0).trim())==result?new Checker.Result(Checker.Status.CORRECT,-1,"정답"):new Checker.Result(Checker.Status.WRONG_ANSWER,0,"이 답 확인");}
}
