package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;
/** Selected fraction scaling and constant unit rates, independent of stored answers. */
public final class PrimaryScaleRates {
 private PrimaryScaleRates(){}
 public static final String SCALE="fractionBatchScaling",AMOUNT="constantFlowAmount",TIME="constantFlowTime";
 public static final List<Catalog.Skill> SKILLS=List.of(new Catalog.Skill(SCALE,"분수만큼 바꾸는 반죽의 양",5,1,1,"",SCALE,3000,"tables,divide","원래 양을 분모로 나누고 분자를 곱해 바뀐 양을 구한다."),new Catalog.Skill(AMOUNT,"일정한 흐름에서 물의 양",5,1,1,"",AMOUNT,1000,"tables,divide","한 분 동안 흐르는 물의 양을 구하고 걸린 시간을 곱한다."),new Catalog.Skill(TIME,"일정한 흐름에서 걸리는 시간",5,1,1,"",TIME,1000,"tables,divide","한 분 동안 흐르는 물의 양을 구하고 필요한 양을 그 값으로 나눈다."));
 public static boolean supports(String id){return SCALE.equals(id)||AMOUNT.equals(id)||TIME.equals(id);}
 static final List<int[]> FACTORS=new ArrayList<>();static{for(int d=2;d<=12;d++)for(int n=1;n<2*d;n++)if(gcd(n,d)==1)FACTORS.add(new int[]{n,d});}
 static int gcd(int a,int b){while(b!=0){int t=a%b;a=b;b=t;}return a;}
 static int count(String id){return SCALE.equals(id)?FACTORS.size()*100:9570;}
 static Question at(String id,int i){if(!supports(id)||i<0||i>=count(id))throw new IllegalArgumentException("Scale/rate index");int a,b,c;String prompt;if(SCALE.equals(id)){int[] f=FACTORS.get(i/100);a=f[1]*(i%100+1);b=f[0];c=f[1];prompt="원래 반죽에는 밀가루가 "+a+"g 필요합니다.\n반죽의 분량을 원래의 "+b+"/"+c+"배로 바꿉니다.\n필요한 밀가루는 몇 g인가요?";}else{int t=i%29+1;i/=29;int h=i%11+2,r=i/11+1;if(t>=h)t++;a=r*h;b=h;c=AMOUNT.equals(id)?t:r*t;prompt="물이 일정한 속도로 흐릅니다.\n"+b+"분 동안 물 "+a+"L가 흐릅니다.\n"+(AMOUNT.equals(id)?c+"분 동안 흐르는 물은 몇 L인가요?":"물 "+c+"L가 흐르는 데 몇 분이 걸리나요?");}Question q=new Question(id,prompt,"","pending");int[] v=read(q);if(v==null)throw new IllegalArgumentException("Scale/rate domain");q.answers=new String[]{""+answer(id,v)};q.stepSupport=false;attach(q);return q.withInputs(a,b,c);}
 public static int[] read(Question q){if(q==null||q.prompt==null||!supports(q.skillId))return null;try{if(SCALE.equals(q.skillId)){Matcher m=Pattern.compile("원래 반죽에는 밀가루가 (\\d+)g 필요합니다\\.\\n반죽의 분량을 원래의 (\\d+)/(\\d+)배로 바꿉니다\\.\\n필요한 밀가루는 몇 g인가요\\?").matcher(q.prompt);if(!m.matches())return null;int a=Integer.parseInt(m.group(1)),n=Integer.parseInt(m.group(2)),d=Integer.parseInt(m.group(3));return d>=2&&d<=12&&n>=1&&n<2*d&&gcd(n,d)==1&&a%d==0&&a/d>=1&&a/d<=100?new int[]{a,n,d}:null;}
 String tail=AMOUNT.equals(q.skillId)?"(\\d+)분 동안 흐르는 물은 몇 L인가요\\?":"물 (\\d+)L가 흐르는 데 몇 분이 걸리나요\\?";Matcher m=Pattern.compile("물이 일정한 속도로 흐릅니다\\.\\n(\\d+)분 동안 물 (\\d+)L가 흐릅니다\\.\\n"+tail).matcher(q.prompt);if(!m.matches())return null;int b=Integer.parseInt(m.group(1)),a=Integer.parseInt(m.group(2)),c=Integer.parseInt(m.group(3));if(b<2||b>12||a%b!=0||a/b<1||a/b>30)return null;int t;if(AMOUNT.equals(q.skillId))t=c;else{if(c%(a/b)!=0)return null;t=c/(a/b);}return t>=1&&t<=30&&t!=b?new int[]{a,b,c}:null;}catch(NumberFormatException ex){return null;}}
 static int answer(String id,int[] v){return SCALE.equals(id)?v[0]/v[2]*v[1]:AMOUNT.equals(id)?v[0]/v[1]*v[2]:v[2]/(v[0]/v[1]);}
 static Question next(String id,Random random,CurriculumLimits limits,Map<String,Integer> recent){return IndexedQuestionSupply.choose(count(id),i->at(id,i),random,limits,recent);}
 static Checker.Result check(Question q,List<String> answers){int[] v=read(q);if(v==null||answers==null||answers.size()!=1||answers.get(0)==null)return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"수 입력 필요");String raw=answers.get(0).trim().replace('−','-');if(!raw.matches("[+-]?\\d{1,6}"))return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"수 입력 필요");boolean same=Integer.parseInt(raw)==answer(q.skillId,v);return new Checker.Result(same?Checker.Status.CORRECT:Checker.Status.WRONG_ANSWER,same?-1:0,same?"계산 확인 완료":"이 수 확인");}
 static void step(StudyGuide g,String instruction,String relation,int expected){g.step(instruction,relation+" = ","",""+expected);}
 public static void attach(Question q){int[] v=read(q);if(v==null)return;StudyGuide g=new StudyGuide().transfer(false);g.teachingVersion="primary-scale-rates-v1";if(SCALE.equals(q.skillId)){step(g,"원래 필요한 밀가루의 양을 쓰세요.","원래 양 B",v[0]);step(g,"배율의 분자를 쓰세요.","배율의 분자 n",v[1]);step(g,"배율의 분모를 쓰세요.","배율의 분모 d",v[2]);step(g,"원래 양을 분모로 나누세요.","한 부분의 양 u = B ÷ d",v[0]/v[2]);step(g,"한 부분의 양에 분자를 곱하세요.","바뀐 양 A = u × n",answer(q.skillId,v));}else{step(g,"처음 흐른 물의 양을 쓰세요.","처음 물의 양 V",v[0]);step(g,"처음 걸린 시간을 쓰세요.","처음 시간 h",v[1]);step(g,"물의 양을 시간으로 나누어 한 분의 양을 구하세요.","한 분의 양 r = V ÷ h",v[0]/v[1]);step(g,AMOUNT.equals(q.skillId)?"새로 주어진 시간을 쓰세요.":"필요한 물의 양을 쓰세요.",AMOUNT.equals(q.skillId)?"새 시간 t":"필요한 양 Q",v[2]);step(g,AMOUNT.equals(q.skillId)?"한 분의 양에 시간을 곱하세요.":"필요한 양을 한 분의 양으로 나누세요.",AMOUNT.equals(q.skillId)?"흐른 양 W = r × t":"걸린 시간 t = Q ÷ r",answer(q.skillId,v));}q.studyGuide=g;}
 public static String[] referenceLabels(String id){return SCALE.equals(id)?new String[]{"원래 양 B","배율의 분자 n","배율의 분모 d","한 부분의 양 u","바뀐 양 A"}:new String[]{"처음 물의 양 V","처음 시간 h","한 분의 양 r",AMOUNT.equals(id)?"새 시간 t":"필요한 양 Q",AMOUNT.equals(id)?"흐른 양 W":"걸린 시간 t"};}
 public static int[] referenceIndices(String id,int stage){return stage==4?(SCALE.equals(id)?new int[]{1,3}:new int[]{2,3}):SCALE.equals(id)&&stage==3?new int[]{0,2}:!SCALE.equals(id)&&stage==2?new int[]{0,1}:new int[0];}
}
