package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;
/** Reverse known multiplication/division facts without requiring a fractional quotient. */
public final class ProductOrder {
 private ProductOrder(){}
 public static final String ID="productOrder",VERSION="product-order-v1";
 public static final Catalog.Skill SKILL=new Catalog.Skill(ID,"곱셈·나눗셈 순서 바꾸기",2,1,1,"","productOrder",120,"tables,divide","두 식을 계산하거나 비교하며 순서를 바꾼 결과를 확인한다.");
 static final String MUL_PROMPT="위 식과 아래 식을 각각 계산하세요.",DIV_PROMPT="두 식의 몫을 비교하세요.";
 static final Set<Integer> KNOWN=Set.of(2,5,10);
 public static boolean supports(String id){return ID.equals(id);}
 public static boolean division(Question q){return q!=null&&supports(q.skillId)&&q.prompt!=null&&q.prompt.startsWith(DIV_PROMPT+"\n");}
 static Map<String,String> options(){Map<String,String> m=new LinkedHashMap<>();m.put("same","몫이 같아요");m.put("different","몫이 달라요");m.put("zero","아래 식은 계산할 수 없어요");return m;}
 static Map<String,String> comparisons(){Map<String,String> m=new LinkedHashMap<>();m.put("<","처음 수가 더 작아요");m.put("=","두 수가 같아요");m.put(">","처음 수가 더 커요");return m;}
 static String verdict(int a,int b){return a==0?"zero":a==b?"same":"different";}
 static Question make(boolean div,int a,int b){if(div?b==0||!KNOWN.contains(b)||a<0||a%b!=0||a/b>12:a<0||b<0||a>12||b>12||!KNOWN.contains(a)&&!KNOWN.contains(b))throw new IllegalArgumentException("product order domain");String op=div?" ÷ ":" × ";Question q=new Question(ID,(div?DIV_PROMPT:MUL_PROMPT)+"\n"+a+op+b+"\n"+b+op+a,"",div?new String[]{verdict(a,b)}:new String[]{""+(a*b),""+(a*b)});q.kind="productOrder";q.labels=div?new String[]{"비교"}:new String[]{"위 식의 값","아래 식의 값"};if(div)q.choiceLabels.putAll(options());q.stepSupport=false;return q;}
 static Question next(Random random,CurriculumLimits limits,Map<String,Integer> recent){Map<String,Question> pool=new LinkedHashMap<>();for(int a=0;a<=12;a++)for(int b=0;b<=12;b++)if(KNOWN.contains(a)||KNOWN.contains(b)){Question q=make(false,a,b);if(limits.allows(q))pool.put(q.signature(),q);}for(int b:KNOWN)for(int n=0;n<=12;n++){Question q=make(true,b*n,b);if(limits.allows(q))pool.put(q.signature(),q);}Map<String,Map<String,Question>> groups=new LinkedHashMap<>();for(var e:pool.entrySet())if(!recent.containsKey(e.getKey())){int[] v=read(e.getValue());String group=v[2]==0?"multiply":verdict(v[0],v[1]);groups.computeIfAbsent(group,k->new LinkedHashMap<>()).put(e.getKey(),e.getValue());}Map<String,Question> selected=groups.isEmpty()?pool:new ArrayList<>(groups.values()).get(random.nextInt(groups.size()));Question q=FactFoundations.choose(selected,random,recent);attach(q);return q;}
 public static int[] read(Question q){if(q==null||!supports(q.skillId)||q.prompt==null)return null;boolean div=division(q);String prefix=(div?DIV_PROMPT:MUL_PROMPT)+"\n";if(!q.prompt.startsWith(prefix))return null;String op=div?"÷":"×";Matcher m=Pattern.compile("(\\d{1,3}) "+op+" (\\d{1,3})\\n(\\d{1,3}) "+op+" (\\d{1,3})").matcher(q.prompt.substring(prefix.length()));if(!m.matches())return null;int a=Integer.parseInt(m.group(1)),b=Integer.parseInt(m.group(2));if(Integer.parseInt(m.group(3))!=b||Integer.parseInt(m.group(4))!=a)return null;if(div?b==0||!KNOWN.contains(b)||a%b!=0||a/b>12:a>12||b>12||!KNOWN.contains(a)&&!KNOWN.contains(b))return null;return new int[]{a,b,div?1:0};}
 static Checker.Result check(Question q,List<String> answers){int[] v=read(q);if(v==null)return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"문제 확인 필요");if(v[2]==1){if(answers.size()!=1||!options().containsKey(answers.get(0)))return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"비교 선택 필요");return answers.get(0).equals(verdict(v[0],v[1]))?new Checker.Result(Checker.Status.CORRECT,-1,"정답"):new Checker.Result(Checker.Status.WRONG_ANSWER,0,"이 비교 확인");}if(answers.size()!=2)return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"두 식의 값 입력 필요");for(int i=0;i<2;i++){if(!answers.get(i).trim().matches("[0-9]{1,3}"))return new Checker.Result(Checker.Status.INPUT_NEEDED,i,"식의 값 입력 필요");if(Integer.parseInt(answers.get(i).trim())!=v[0]*v[1])return new Checker.Result(Checker.Status.WRONG_ANSWER,i,"이 식의 값 확인");}return new Checker.Result(Checker.Status.CORRECT,-1,"정답");}
 public static void attach(Question q){int[] v=read(q);if(v==null)return;StudyGuide g=new StudyGuide().transfer(false);g.teachingVersion=VERSION;if(v[2]==0){g.step("위 식의 첫 수를 쓰세요.","위 식의 첫 수 = ","",""+v[0]).step("위 식의 둘째 수를 쓰세요.","위 식의 둘째 수 = ","",""+v[1]).step("위 식을 계산하세요.","위 식의 첫 수 × 위 식의 둘째 수 = ","",""+(v[0]*v[1])).step("아래 식을 계산하세요.","아래 식의 첫 수 × 아래 식의 둘째 수 = ","",""+(v[0]*v[1]));}else{g.step("위 식의 처음 수를 쓰세요.","위 식의 처음 수 = ","",""+v[0]).step("위 식의 나누는 수를 쓰세요.","위 식의 나누는 수 = ","",""+v[1]).step("위 식의 몫을 계산하세요.","위 식의 처음 수 ÷ 위 식의 나누는 수 = ","",""+(v[0]/v[1])).choice("아래 식의 처음 수와 나누는 수를 비교하세요.",comparisons(),v[1]<v[0]?"<":v[1]>v[0]?">":"=").choice("두 식의 몫을 비교하세요.",options(),verdict(v[0],v[1]));}q.studyGuide=g;}
}
