package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;
/** Contextual facts read exclusively from visible givens. */
public final class RatioContextStories {
 private RatioContextStories(){}
 public static final String ANGLE="percentageTurnAngle";
 public static final List<Catalog.Skill> SKILLS=List.of(new Catalog.Skill(ANGLE,"백분율로 회전각 구하기",6,1,1,"","percentageTurnAngle",100,"percent","한 바퀴의 각과 백분율로 회전각을 구한다."));
 static final List<Rational> FRACTIONS=fractions();
 private static List<Rational> fractions(){Set<Rational> all=new LinkedHashSet<>();for(int d=2;d<=12;d++)for(int n=1;n<d;n++)if(2*n!=d)all.add(Rational.of(n,d));return List.copyOf(all);}
 public static int domainSize(String id){return id.equals("proportion")?5760:id.equals("el_proportional_split")?10560:id.equals(ANGLE)?101:0;}
 static Question at(String id,int i){Question q;if(id.equals("proportion")){int side=i%2;i/=2;int unit=i%20+1;i/=20;int b=i%12+1,a=i/12+1,known=(side==0?a:b)*unit,answer=(side==0?b:a)*unit;String colour=side==0?"빨간":"파란",target=side==0?"파란":"빨간";q=new Question(id,"빨간 구슬과 파란 구슬의 수의 비는 "+a+":"+b+"입니다. "+colour+" 구슬이 "+known+"개이면 "+target+" 구슬은 몇 개인가요?","",""+answer);}
 else if(id.equals(ANGLE)){q=new Question(id,"한 바퀴는 360°입니다. 한 바퀴의 "+i+"%만큼 회전한 각은 몇 도인가요?","",Rational.of(360*i,100).decimalText());q.decimal=true;q.answerFormat="decimalValue";}
 else{int mode=i%12;i/=12;int unit=i%20+1;Rational f=FRACTIONS.get(i/20);int group=mode==0?1:mode+1,n=f.n.intValue(),d=f.d.intValue(),total=d*unit*group;String prompt="구슬 "+total+"개 중 전체의 "+f+"을 첫째 주머니에 담고 나머지를 둘째 주머니에 담습니다. ";prompt+=mode==0?"각 주머니의 구슬 수는?":"각 주머니의 구슬을 "+group+"개씩 묶으면 각 주머니에 몇 묶음인가요?";q=new Question(id,prompt,"",""+(n*unit),""+((d-n)*unit));q.labels=mode==0?new String[]{"첫째 주머니","둘째 주머니"}:new String[]{"첫째 묶음 수","둘째 묶음 수"};}
 q.stepSupport=false;attach(q);return q;}
 static Question nextAngle(Random random,CurriculumLimits l,Map<String,Integer> recent){return IndexedQuestionSupply.choose(101,i->at(ANGLE,i),random,l,recent);}
 public record Givens(String id,int a,int b,int c,int group){}
 public static Givens read(Question q){if(q==null||q.prompt==null)return null;Matcher m;if(q.skillId.equals("proportion")){m=Pattern.compile("빨간 구슬과 파란 구슬의 수의 비는 (\\d+):(\\d+)입니다. (빨간|파란) 구슬이 (\\d+)개이면 (파란|빨간) 구슬은 몇 개인가요\\?").matcher(q.prompt);if(!m.matches()||m.group(3).equals(m.group(5)))return null;int a=Integer.parseInt(m.group(1)),b=Integer.parseInt(m.group(2)),count=Integer.parseInt(m.group(4));if(a<=0||b<=0)return null;return new Givens(q.skillId,a,b,count,m.group(3).equals("빨간")?0:1);}
 if(q.skillId.equals(ANGLE)){m=Pattern.compile("한 바퀴는 360°입니다. 한 바퀴의 (\\d+)%만큼 회전한 각은 몇 도인가요\\?").matcher(q.prompt);return m.matches()?new Givens(q.skillId,360,Integer.parseInt(m.group(1)),0,0):null;}
 if(q.skillId.equals("el_proportional_split")){m=Pattern.compile("구슬 (\\d+)개 중 전체의 (\\d+)/(\\d+)을 첫째 주머니에 담고 나머지를 둘째 주머니에 담습니다. (각 주머니의 구슬 수는\\?|각 주머니의 구슬을 (\\d+)개씩 묶으면 각 주머니에 몇 묶음인가요\\?)").matcher(q.prompt);if(!m.matches())return null;int total=Integer.parseInt(m.group(1)),n=Integer.parseInt(m.group(2)),d=Integer.parseInt(m.group(3)),g=m.group(5)==null?1:Integer.parseInt(m.group(5));return total>0&&n>0&&d>n&&g>0?new Givens(q.skillId,total,n,d,g):null;}return null;}
 public static void attach(Question q){Givens v=read(q);if(v==null)return;StudyGuide g=new StudyGuide().transfer(false);g.teachingVersion="ratio-context-stories-v1";if(v.id.equals("proportion")){Rational unit=Rational.of(v.c,v.group==0?v.a:v.b),answer=unit.mul(Rational.of(v.group==0?v.b:v.a));g.step("빨간 구슬에 해당하는 비의 항을 쓰세요.","빨간 비의 항 a = ","",""+v.a);g.step("파란 구슬에 해당하는 비의 항을 쓰세요.","파란 비의 항 b = ","",""+v.b);g.step("문제에서 알려 준 구슬 수를 쓰세요.","알려진 구슬 수 C = ","",""+v.c);g.step("알려진 구슬 수를 그 색의 비의 항으로 나누세요.","한 묶음의 양 u = C ÷ 알려진 비의 항 = ","",unit.toString());g.step("한 묶음의 양에 구할 색의 비의 항을 곱하세요.","구할 구슬 수 = u × 구할 비의 항 = ","",answer.toString());}
 else if(v.id.equals(ANGLE)){g.step("한 바퀴의 각을 쓰세요.","한 바퀴의 각 B = ","°","360");g.step("문제의 백분율을 쓰세요.","백분율 p = ","%",""+v.b);g.step("백분율을 100으로 나누세요.","비율 v = p ÷ 100 = ","",Rational.of(v.b,100).decimalText());g.step("한 바퀴의 각에 비율을 곱하세요.","회전각 A = B × v = ","°",Rational.of(360*v.b,100).decimalText());for(var f:g.frames)f.inputFormat="decimalValue";}
 else{Rational unit=Rational.of(v.a,v.c),first=unit.mul(Rational.of(v.b)),second=Rational.of(v.a).sub(first);g.step("전체 구슬 수를 쓰세요.","전체 B = ","",""+v.a);g.step("첫째 주머니가 받는 분수의 분자를 쓰세요.","분자 n = ","",""+v.b);g.step("첫째 주머니가 받는 분수의 분모를 쓰세요.","분모 d = ","",""+v.c);g.step("전체 수를 분모로 나누세요.","한 부분의 양 u = B ÷ d = ","",unit.toString());g.step("한 부분의 양에 분자를 곱하세요.","첫째 양 A = u × n = ","",first.toString());g.step("전체 수에서 첫째 양을 빼세요.","둘째 양 C = B − A = ","",second.toString());if(v.group>1){g.step("한 묶음의 구슬 수를 쓰세요.","묶음 크기 s = ","",""+v.group);g.step("첫째 양을 묶음 크기로 나누세요.","첫째 묶음 수 = A ÷ s = ","",first.div(Rational.of(v.group)).toString());g.step("둘째 양을 묶음 크기로 나누세요.","둘째 묶음 수 = C ÷ s = ","",second.div(Rational.of(v.group)).toString());}}
 q.studyGuide=g;}
}
