package com.gomgomapps.math.core;
import java.util.*;import java.util.regex.*;
/** Public practical contexts for large counts, signed temperatures and rounding. */
public final class YearFiveNumberStories {
 private YearFiveNumberStories(){}
 public static final String STOCK="bookStockChanges",TEMPERATURE="temperatureChanges",ROUND="populationRounding",COMPARE="populationComparison";
 public static final List<Catalog.Skill> SKILLS=List.of(new Catalog.Skill(STOCK,"책 창고의 수량 변화",5,1,1,"","numberStories",3000000,"powerCountForward,powerCountBackward","매일 같은 수만큼 들어오거나 나가는 책을 센다."),new Catalog.Skill(TEMPERATURE,"시간에 따른 기온 변화",5,1,1,"","numberStories",60,"negativeCountBackward","매시간 같은 만큼 오르거나 내리는 기온을 구한다."),new Catalog.Skill(ROUND,"인구 수 반올림",5,1,1,"","numberStories",1000000,"el_round","보고서에 쓸 인구 수를 주어진 자리까지 반올림한다."));
 public static final Catalog.Skill COMPARE_SKILL=new Catalog.Skill(COMPARE,"두 지역의 인구 비교",5,1,1,"","numberStories",1000000,"el_compare","두 지역의 인구를 비교한다.");
 public static boolean supports(String id){return STOCK.equals(id)||TEMPERATURE.equals(id)||ROUND.equals(id)||COMPARE.equals(id);}
 static int count(String id){return STOCK.equals(id)?10777791:TEMPERATURE.equals(id)?1220:ROUND.equals(id)?5000005:COMPARE.equals(id)?200990101:0;}
 static Question at(String id,int index){if(index<0||index>=count(id))throw new IllegalArgumentException("Story index");
  if(COMPARE.equals(id)){for(int difference=-100;difference<=100;difference++){int size=1000001-Math.abs(difference);if(index<size){int left=Math.max(0,-difference)+index;return compare(left,left+difference);}index-=size;}throw new IllegalStateException("Comparison block");}
  if(ROUND.equals(id)){int step=10;for(int p=index/1000001;p-->0;)step*=10;return rounding(index%1000001,step);}
  if(TEMPERATURE.equals(id)){int move=index/61+1;return temperature(index%61-20,move<=10?move:-(move-10));}
  if(index<6000006){int step=10;for(int p=index/1000001;p-->0;)step*=10;return stock(index%1000001,step);}
  index-=6000006;for(int step=10;step<=100000;step*=10){int size=1000000-2*step+1;if(index<size)return stock(2*step+index,-step);index-=size;}throw new IllegalStateException("Story block");
 }
 static Question next(Catalog.Skill s,Random random,CurriculumLimits limits,Map<String,Integer> recent){return IndexedQuestionSupply.choose(count(s.id),i->at(s.id,i),random,limits,recent);}
 public static Question stock(int start,int change){int step=Math.abs(change);if(start<0||start>1000000||!Set.of(10,100,1000,10000,100000,1000000).contains(step)||start+2*change<0)throw new IllegalArgumentException("Book stock");Question q=new Question(STOCK,"책 창고\n처음 책: "+start+"권\n매일 "+step+"권씩 "+(change>0?"들어옵니다.":"나갑니다.")+"\n첫날과 둘째 날이 지난 뒤의 책 수를 각각 쓰세요.","",""+(start+change),""+(start+2*change));q.labels=new String[]{"첫날 뒤","둘째 날 뒤"};q.stepSupport=false;attach(q);return q;}
 public static Question temperature(int start,int change){if(start< -20||start>40||change==0||Math.abs(change)>10)throw new IllegalArgumentException("Temperature");Question q=new Question(TEMPERATURE,"처음 기온: "+start+" °C\n매시간 "+Math.abs(change)+" °C씩 "+(change>0?"올라갑니다.":"내려갑니다.")+"\n한 시간 뒤와 두 시간 뒤의 기온을 각각 쓰세요.","",""+(start+change),""+(start+2*change));q.labels=new String[]{"한 시간 뒤","두 시간 뒤"};q.stepSupport=false;attach(q);return q;}
 public static Question rounding(int number,int unit){if(number<0||number>1000000||!Set.of(10,100,1000,10000,100000).contains(unit))throw new IllegalArgumentException("Population");Question q=new Question(ROUND,"지역의 인구: "+number+"명\n보고서에는 "+unit+"의 자리까지 반올림하여 적습니다.\n보고서에 적을 인구 수는 몇 명인가요?","",""+((number+unit/2)/unit*unit));q.stepSupport=false;attach(q);return q;}
 public static Question compare(int left,int right){if(left<0||left>1000000||right<0||right>1000000)throw new IllegalArgumentException("Population comparison");Question q=new Question(COMPARE,"왼쪽 지역 인구: "+left+"명\n오른쪽 지역 인구: "+right+"명\n왼쪽 인구 □ 오른쪽 인구\n알맞은 비교 기호를 고르세요.","",left==right?"=":left>right?">":"<");q.kind="symbol";q.stepSupport=false;attach(q);return q;}
 public static int[] read(Question q){if(q==null||q.prompt==null||!supports(q.skillId))return null;Matcher m;
  if(COMPARE.equals(q.skillId)){m=Pattern.compile("왼쪽 지역 인구: (\\d{1,7})명\\n오른쪽 지역 인구: (\\d{1,7})명\\n왼쪽 인구 □ 오른쪽 인구\\n알맞은 비교 기호를 고르세요\\.").matcher(q.prompt);if(!m.matches())return null;int left=Integer.parseInt(m.group(1)),right=Integer.parseInt(m.group(2));return left>1000000||right>1000000?null:new int[]{left,right,Integer.compare(left,right)};}
  if(STOCK.equals(q.skillId)){m=Pattern.compile("책 창고\\n처음 책: (\\d{1,7})권\\n매일 (10|100|1000|10000|100000|1000000)권씩 (들어옵니다|나갑니다)\\.\\n첫날과 둘째 날이 지난 뒤의 책 수를 각각 쓰세요\\.").matcher(q.prompt);if(!m.matches())return null;int start=Integer.parseInt(m.group(1)),change=Integer.parseInt(m.group(2))*(m.group(3).equals("들어옵니다")?1:-1);if(start>1000000||start+2*change<0)return null;return new int[]{start,change,start+change,start+2*change};}
  if(TEMPERATURE.equals(q.skillId)){m=Pattern.compile("처음 기온: (-?\\d{1,2}) °C\\n매시간 (10|[1-9]) °C씩 (올라갑니다|내려갑니다)\\.\\n한 시간 뒤와 두 시간 뒤의 기온을 각각 쓰세요\\.").matcher(q.prompt);if(!m.matches())return null;int start=Integer.parseInt(m.group(1)),change=Integer.parseInt(m.group(2))*(m.group(3).equals("올라갑니다")?1:-1);if(start< -20||start>40)return null;return new int[]{start,change,start+change,start+2*change};}
  m=Pattern.compile("지역의 인구: (\\d{1,7})명\\n보고서에는 (10|100|1000|10000|100000)의 자리까지 반올림하여 적습니다\\.\\n보고서에 적을 인구 수는 몇 명인가요\\?").matcher(q.prompt);if(!m.matches())return null;int number=Integer.parseInt(m.group(1)),unit=Integer.parseInt(m.group(2));if(number>1000000)return null;return new int[]{number,unit,(number+unit/2)/unit*unit};
 }
 public static void attach(Question q){int[] v=read(q);if(v==null)return;if(COMPARE.equals(q.skillId)){StudyGuide g=new StudyGuide().transfer(false);g.teachingVersion="population-comparison-v1";g.step("왼쪽 지역의 인구를 쓰세요.","왼쪽 인구 a = ","",""+v[0]);g.step("오른쪽 지역의 인구를 쓰세요.","오른쪽 인구 b = ","",""+v[1]);Map<String,String> signs=new LinkedHashMap<>();signs.put("<","a < b");signs.put("=","a = b");signs.put(">","a > b");g.choice("두 인구를 비교하세요.",signs,v[2]<0?"<":v[2]>0?">":"=");q.studyGuide=g;return;}if(ROUND.equals(q.skillId)){Question proxy=new Question("el_round",v[0]+"을 "+v[1]+"의 자리까지 반올림하면?","","poison");RoundingRelations.attach(proxy);q.studyGuide=proxy.studyGuide;return;}
  StudyGuide g=new StudyGuide().transfer(false);g.teachingVersion="year-five-number-stories-v1";boolean temperature=TEMPERATURE.equals(q.skillId),up=v[1]>0;g.step(temperature?"처음 기온을 쓰세요.":"처음 책 수를 쓰세요.","처음 값 s = ","",""+v[0]);g.step(temperature?"매시간 변하는 기온의 크기를 쓰세요.":"매일 변하는 책 수를 쓰세요.","변화의 크기 h = ","",""+Math.abs(v[1]));g.step(up?"처음 값에 변화의 크기를 더하세요.":"처음 값에서 변화의 크기를 빼세요.",up?"첫 값 a = s + h = ":"첫 값 a = s − h = ","",""+v[2]);g.step(up?"첫 값에 같은 크기를 더하세요.":"첫 값에서 같은 크기를 빼세요.",up?"둘째 값 b = a + h = ":"둘째 값 b = a − h = ","",""+v[3]);q.studyGuide=g;
 }
 static Checker.Result check(Question q,List<String> answers){int[] v=read(q);int count=ROUND.equals(q.skillId)?1:2;if(v==null||answers==null)return new Checker.Result(Checker.Status.INPUT_NEEDED,-1,"문제 확인 필요");if(COMPARE.equals(q.skillId)){if(answers.size()!=1||!Set.of("<","=",">").contains(answers.get(0)))return new Checker.Result(Checker.Status.INPUT_NEEDED,0,"비교 기호 선택 필요");return answers.get(0).equals(v[2]<0?"<":v[2]>0?">":"=")?new Checker.Result(Checker.Status.CORRECT,-1,"정답"):new Checker.Result(Checker.Status.WRONG_ANSWER,0,"이 비교 확인");}for(int i=0;i<count;i++){if(answers.size()<=i||answers.get(i)==null)return new Checker.Result(Checker.Status.INPUT_NEEDED,i,"수 입력 필요");String raw=Expression.normalize(answers.get(i).trim());if(!raw.matches("[+-]?\\d{1,8}"))return new Checker.Result(Checker.Status.INPUT_NEEDED,i,"정수 입력 필요");if(Integer.parseInt(raw)!=v[i+2])return new Checker.Result(Checker.Status.WRONG_ANSWER,i,"이 수 확인");}return new Checker.Result(Checker.Status.CORRECT,-1,"정답");}
}
